- .env.development
- src/components/dashboard/main-content/DashboardMainContent.jsx
- src/components/enterprise-page/EnterprisePage.jsx
Related PR: https://github.com/edx/edx-internal/pull/1557
* Renames environment variable to `CATALOG_BASE_URL`
> rename and set CATALOG_BASE_URL

- README.md
This set of notes helps users locate learner accounts, enterprise customer slug for use in the URL for learner portal, etc...
> How to login to learner portal as a learner, and related notes

- .env.development
- src/components/app/App.jsx
- src/components/course/CourseHeader.jsx
- src/components/dashboard/main-content/DashboardMainContent.jsx
- src/components/enterprise-page/EnterprisePage.jsx
- src/components/search/Search.jsx
- src/components/search/SearchPage.jsx
- src/components/search/index.js
Initial steps for the "Search" prototype, adding a simple "Search" page placeholder and the navigation to browse there.
Ticket: https://openedx.atlassian.net/browse/ENT-2357
> Add placeholder "Search" page and get search navigation in place

- src/components/course/CourseRunSelector.jsx
Adds some spacing so this looks less bad.
> Fixes styling on course run selector

- README.md
Fixes some typos and makes some changes for clarity; adds periods in sentences and removes them in lists
> Update README for clarity and consistency

- README.md
Since @raq929 ran into this question while onboarding, I thought it would be best placed in this starter README
> update readme on how to create a course and enroll an enterprise learner

- src/components/search/ClearCurrentRefinements.jsx
- src/components/search/CurrentRefinements.jsx
- src/components/search/MobileFilterMenu.jsx
- src/components/search/SearchBox.jsx
- src/components/search/SearchPagination.jsx
- src/components/search/data/constants.js
- src/components/search/data/tests/constants.js
- src/components/search/data/tests/hooks.test.js
- src/components/search/data/tests/utils.test.js
- src/components/search/tests/CurrentRefinements.test.jsx
- src/components/search/tests/MobileFilterMenu.test.jsx
- src/components/search/tests/SearchBox.test.jsx
- src/components/search/tests/SearchPagination.test.jsx
Adds test for the following:
* search utils
* SearchBox
* MobileFilterMenu
* CurrentRefinements
* SearchPagination
> Additional search-related tests

- src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx
- src/components/dashboard/main-content/course-enrollments/CourseSection.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/CompletedCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/SavedForLaterCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/index.js
- src/components/dashboard/main-content/course-enrollments/data/selectors.js
- src/components/dashboard/main-content/course-enrollments/data/tests/selectors.test.js
- src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.enzyme.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js
Sort courses saved for later into a new category
Display them using the new course card
Adds testing for the sort function as it became more complex
> Create a SavedForLaterCourse card

- src/components/course/CoursePage.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/license-activation/LicenseActivationPage.jsx
- src/components/login-redirect/LoginRedirect.jsx
- src/components/search/SearchPage.jsx
- src/index.jsx
> Redirect unauthenticated users to proxy-login

- src/components/course/EnrollButton.jsx
Follow-up from https://github.com/edx/frontend-app-learner-portal-enterprise/pull/67, to handle the case where a subscription license does not exist, the "Enroll" button should not link to the DSC page. This set ups the future implementation work for codes/offers.
> only link to DSC if user has license, otherwise disable enroll btn for now

- src/components/course/CourseContextProvider.jsx
- src/components/course/CourseHeader.jsx
- src/components/course/CreatedBy.jsx
- src/components/course/EnrollButton.jsx
- src/components/course/data/constants.js
- src/components/course/data/hooks.js
- src/components/course/data/utils.jsx
- src/components/course/tests/CourseHeader.test.jsx
- src/components/course/tests/CreatedBy.test.jsx
- src/components/course/tests/EnrollButton.test.jsx
- src/components/course/tests/data/constants.js
- src/setupTest.js
The initial Course page prototyping work did not originally include tests. This PR adds tests for the following course-related components:
* CourseHeader
* EnrollButton
* CreatedBy
More tests coming for other parts of the Course page. Decided to split the PR into 2 to be easier to review.
> add tests for Course page, pt 1

- src/components/course/CourseRunSelector.jsx
- src/components/dashboard/main-content/course-enrollments/CollapsibleIcon.jsx
- src/components/enterprise-page/data/hooks.js
- src/components/enterprise-page/data/tests/customerConfig.test.js
- src/components/layout/data/hooks.js
https://openedx.atlassian.net/browse/ENT-2892
Primary = hot pink
Secondary = lime green
Tertiary = Dark Olive
Hover over "Continue Learning":
Hover over the gears:
Search:
Find a Course:
> Update branding config colors.

- src/components/course/Course.jsx
- src/components/course/CourseRunSelector.jsx
- src/components/course/EnrollButton.jsx
- src/components/course/data/utils.jsx
> Make course run selection consistent with B2C

- src/components/dashboard/Dashboard.jsx
- src/components/license-activation/LicenseActivation.jsx
> Add notification on license activation success

- src/components/license-activation/LicenseActivation.jsx
> Update license activation error message

- src/components/enterprise-page/EnterprisePage.jsx
https://openedx.atlassian.net/browse/ENT-3271
Adds "Dashboard" link to the Learner Portal:
> Add Dashboard link to header

- src/components/search/data/constants.js
Will be testing that the proper courses are getting indexed on stage.
ENT-2992
> Update algolia index name

- src/components/enterprise-banner/OffersAlert.jsx
Update wording and add icon
Remove the zero showing when loading
> Update wording and avoid showing zero while data is loading

- src/components/site-header/SiteHeader.jsx
[ENT-3274](https://openedx.atlassian.net/browse/ENT-3274)
**Testing Instructions**
Pull branch, login to LP, logout and observe the redirect back to the customer branded LP login page.
> ENT-3274: adding next param to logout URL to redirect back to LP login

- src/components/course/EnrollModal.jsx
> Make loading spinner spin

- package-lock.json
- package.json
- src/components/dashboard/Dashboard.jsx
- src/components/dashboard/Dashboard.test.jsx
- src/components/dashboard/main-content/DashboardMainContent.jsx
- src/components/dashboard/sidebar/DashboardSidebar.jsx
- src/components/dashboard/sidebar/DashboardSidebar.test.jsx
- src/components/dashboard/sidebar/SidebarCard.test.jsx
- src/components/layout/Sidebar.jsx
- src/setupTest.js
- src/utils/tests.jsx
Add test utility for mocking window size
> Add testing for dashboard

- src/components/course/DeprecatedEnrollButton.jsx
- src/components/course/EnrollButton.jsx
Enrollment button was previously transparent, primary styling is now applied again:
> fixing style for the enrollment button

- src/components/search/FacetDropdown.jsx
- src/components/search/SearchFilters.jsx
Fixes bolding of titles and adds the Free/all filter to mobile
> Fix issues introduced with Free/All filter

- .gitignore
- package-lock.json
- package.json
JIRA tickets:
* https://openedx.atlassian.net/browse/ENT-3913
verifying locally first then will in stage
the axios dep was already upgraded in prior commit/merged
> feat: upgrade axios and frontend-platform for security audit changes

- README.md
For those who are interested in vscode embedded debugging, it's an alternative that sometimes works well if you want to stay focused in the editor.
> doc: notes on vscode embedded debugging

- .env.development
- package-lock.json
- package.json
- src/components/layout/Layout.jsx
- src/components/system-wide-banner/SystemWideWarningBanner.jsx
- src/components/system-wide-banner/index.js
- src/index.jsx
ENT-4053
_Note: this is using the core Paragon / Open edX theme; it will use edX.org brand theme on stage/prod._
See https://openedx.atlassian.net/wiki/spaces/BPL/pages/2277966053/Page+Banner for design details.
> add and use system-wide warning banner component

- src/components/course/Course.jsx
- src/components/course/CourseContextProvider.jsx
- src/components/course/EnrollButton.jsx
- src/components/course/data/service.js
- src/components/course/data/utils.jsx
- src/components/course/enrollment/hooks.js
- src/components/course/enrollment/tests/hooks.test.jsx
- src/components/course/tests/EnrollButton.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
[ENT-4018](https://openedx.atlassian.net/browse/ENT-4018)
Related PR: https://github.com/edx/edx-enterprise/pull/1134 (must be released first)
> fix: only consider enterprise course enrollments when fetching user enrollments

- src/components/course/EnrollModal.jsx
- src/components/dashboard/sidebar/OfferSummaryCard.jsx
- src/components/dashboard/sidebar/data/constants.js
ENT-3985 Updates to make microcopy clearer for learner portal since we are adding code redemption as a feature.
> Edx abolger/ent 3985 microcopy update

- src/components/course/data/service.js
- src/components/course/data/tests/utils.test.jsx
- src/components/course/data/utils.jsx
Doc or style as commit type? idk.
Added a test to verify the empty catalog list doesn't break things in the findOfferForCourse util.
> style: Rename param, add documentation for clarity, handle catalogList not existing

- src/components/enterprise-user-subsidy/data/hooks.jsx
- src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
So that users only see valid coupons
> Add is_active to request querystring

- package-lock.json
- package.json
Bumps frontend-enterprise to bring in the new "Language" search facet.
> feat: introduce Language search facet

- .env.development
- package-lock.json
- package.json
Upgrade frontend-enterprise to 5.4.0 | Facet on the title of the program instead of the type of the program. ENT-4365
https://openedx.atlassian.net/browse/ENT-4365
> feat: facet course search results by title

- src/components/course/CourseSkills.jsx
- src/components/course/tests/CourseSkills.test.jsx
Link can be seen at the bottom left in the image.
> Clickable skills tags

- package-lock.json
- package.json
`@edx/frontend-enterprise` v5.5.1 fixes some search styles; upgrading Paragon to latest to bring in new components and some upstream fixes.
> fix: bump frontend-enterprise to 5.5.1 and paragon to 14.6.1

- package-lock.json
- package.json
>= 1.8.5 causes https://openedx.atlassian.net/browse/ENT-4484
> fix: roll @edx/frontend-platform back to 1.8.4

- src/components/course/CourseSkills.jsx
- src/components/course/data/constants.js
- src/components/course/data/utils.jsx
- src/components/course/tests/CourseSkills.test.jsx
- src/components/course/tests/testUtils.js
JIRA: https://openedx.atlassian.net/browse/ENT-4621
> fix: added character limit for skills Popover

- package-lock.json
- package.json
Pulls in the changes noted here: https://github.com/edx/frontend-build/pull/179
> build: bump frontend-build to pull in New Relic source map uploads

- src/components/skills-quiz/GoalDropdown.jsx
- src/components/skills-quiz/SearchJobDropdown.jsx
- src/components/skills-quiz/SearchResults.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/tests/SkillsDropdown.test.jsx
* Goal Dropdown:
* The Search Jobs dropdown and Search Results card are shown when "I want to get better at my current role" is not selected
* The Search Jobs dropdown and Search Results card are hidden when "I want to get better at my current role" is selected
> added goal Dropdown in SkillQuizStepper

- src/components/course/enrollment/components/ToCoursewarePage.jsx
- src/components/course/enrollment/components/ToDataSharingConsent.jsx
> fix: correct enroll button styles when using hyperlink

- package-lock.json
- package.json
- src/colors.scss
- src/components/course/enrollment/components/DisabledEnroll.jsx
- src/components/course/enrollment/components/ToVoucherRedeemPage.jsx
- src/components/course/enrollment/components/ViewOnDashboard.jsx
* Upgrades to Webpack 5.
* Minor style fixes
Depends on https://github.com/edx/frontend-build/pull/191
> build: upgrade frontend-build to v7 for webpack 5

- src/components/TagCloud/index.jsx
- src/components/TagCloud/styles/TagCloud.scss
- src/components/skills-quiz/SkillsQuizPage.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx
**JIRA Ticket:** [ENT-4671](https://openedx.atlassian.net/browse/ENT-4671)
As skills are selected from the Skills dropdown list, each skill name should appear in this filter card. 
Skills may be removed from the filter card by clicking the 'x' box next to the filter name.
As skills are added to the filter card, these skills should be applied to the filter on the Search Jobs dropdown list.
As skills are removed from the filter card, the Search Jobs filter should be updated.
> ENT-4671: Added a new component to show selected skills.

- src/components/skills-quiz/SearchResults.jsx
- src/components/skills-quiz/SelectJobCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/styles/_SearchResults.scss
- src/components/skills-quiz/tests/SelectJobCard.test.jsx
JIRA Link
https://openedx.atlassian.net/browse/ENT-4767
Test cases are added but since they are related to jobs and commented out at the moment, so it's showing a coverage difference of -0.1%
Here is the google drive video file link of this functionality
https://drive.google.com/file/d/1-jWYWD1i7mNQmN_-8BmvPcBTHo9wsWc_/view
> feat: Select Job card to show courses

- src/components/skills-quiz/SearchCourseCard.jsx
- src/components/skills-quiz/SearchResults.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/styles/_SearchCourseCard.scss
- src/components/skills-quiz/styles/_SearchResults.scss
- src/components/skills-quiz/styles/index.scss
- src/components/skills-quiz/tests/SearchCourseCard.test.jsx
- src/components/skills-quiz/tests/SearchResults.test.jsx
**Changes**: 
- Display course card with recommended course at the second step of skills quiz
- Set a limit to display # of skills in a course card
- Set a character limit on the skill name so the characters don't pop out of the card
JIRA: https://openedx.atlassian.net/browse/ENT-4768
> feat: Show Top 3 Recommended Courses

- src/components/skills-quiz/SearchJobCard.jsx
- src/components/skills-quiz/SearchResults.jsx
- src/components/skills-quiz/SelectJobCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/styles/_SearchJobCard.scss
- src/components/skills-quiz/tests/SearchJobCard.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-4816
https://user-images.githubusercontent.com/55431213/130646760-9b88303d-bb11-4327-9885-761db0e89ffa.mov
> feat: Replace skills data with jobs data in SearchJobCards skill quiz component

- src/components/TagCloud/styles/TagCloud.scss
- src/components/skills-quiz/SkillsQuizStepper.jsx
> change layout of skills-quiz

- .gitignore
- src/components/course/CoursePage.jsx
- src/components/license-activation/data/service.js
- src/utils/common.js
https://openedx.atlassian.net/browse/ENT-4885
> fix: Make a call to login_refresh from the course page if no roles are present

- src/components/skills-quiz/SearchCourseCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/styles/_SearchCourseCard.scss
- src/components/skills-quiz/tests/SearchCourseCard.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-4769
> feat: Determine top 3 courses based on skills and job skills

- src/components/skills-quiz/SearchCourseCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/data/hooks.js
- src/utils/common.js
- src/utils/tests/common.test.js
JIRA: https://openedx.atlassian.net/browse/ENT-4790
> feat: See More Courses Button should also include skills linked to jobs

- src/components/skills-quiz/SkillsQuizStepper.jsx
ENT4876: Applied checks to show courses only when users have selected skills or jobs.
> feat: Adding check for showing recommended courses

- src/components/skills-quiz/GoalDropdown.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/data/hooks.js
- src/components/skills-quiz/styles/SkillsQuizDropdowns.scss
In this PR, I've renamed one of the dropdown options and also increase the dropdown width, so that text will not cutoff anymore.
For more Context:
JIRA Ticket: https://openedx.atlassian.net/browse/ENT-4925
> refactor: increase the dropdown width and change text

- src/components/skills-quiz/styles/SkillsQuizDropdowns.scss
In this PR, I've restored the dropdown width.
For more Context:
JIRA Ticket: https://openedx.atlassian.net/browse/ENT-4925
> refactor: restore the dropdown width to old state

- src/components/enterprise-banner/EnterpriseBanner.jsx
- src/components/enterprise-banner/styles/EnterpriseBanner.scss
ENT4585: Adding Skills Quiz button on Courses Search Page.
> feat: Adding Skills Quiz button on course search page

- src/components/skills-quiz/SkillsQuizStepper.jsx
Added the ability to navigate to the course search page by clicking on Cancel, Done, and * icon.
ENT-4950, ENT4976, ENT4977
> feat: close skills page ability added

- package-lock.json
- package.json
- src/components/skills-quiz/CurrentJobDropdown.jsx
- src/components/skills-quiz/SearchJobDropdown.jsx
**JIRA**: https://openedx.atlassian.net/browse/ENT-4928
**Description**: Remove (1) count from all jobs in search
https://user-images.githubusercontent.com/55431213/134495066-b48a0329-823e-4136-9066-1228e9e169e1.mov
> fix: show count on dropdown items only when showBadge is true

- src/components/skills-quiz/JobCardComponent.jsx
- src/components/skills-quiz/SelectJobCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/data/hooks.js
- src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx
- src/components/utils/skills-quiz.js
- src/components/utils/test/skills-quiz.test.jsx
[Ticket](https://openedx.atlassian.net/browse/ENT-4949)
> feat: make continue button disable until required values not selected

- src/components/skills-quiz/SearchCourseCard.jsx
- src/components/skills-quiz/SearchCurrentJobCard.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/styles/_SearchCourseCard.scss
- src/components/skills-quiz/tests/SearchCourseCard.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-4815
> feat: Only show skills on course card relevant to search

- src/components/skills-quiz/SearchCourseCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/tests/SearchCourseCard.test.jsx
- src/components/skills-quiz/tests/SearchFilters.test.jsx
- src/components/skills-quiz/tests/SkillsQuiz.test.jsx
- src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx
Description: This PR adds tracking events to the skills_quiz
JIRA: https://openedx.atlassian.net/browse/ENT-5023
> feat: Added tracking events for skills quiz

- src/components/program/ProgramCourses.jsx
- src/components/program/ProgramMainContent.jsx
- src/components/program/tests/Program.test.jsx
- src/components/program/tests/ProgramCourses.test.jsx
__JIRA Ticket:__ [ENT-4861](https://openedx.atlassian.net/browse/ENT-4861)
The Program courses section needs to be added to the container page created as part of ENT-4859. Use the vanilla Collapsible component provided by Paragon.
> ENT-4861: Added courses section in program details page.

- src/components/program/ProgramCourses.jsx
> fix: Fixed UI issues with program course section.

- src/components/program/ProgramHeader.jsx
- src/components/program/ProgramSidebar.jsx
- src/components/program/data/constants.js
- src/components/program/data/utils.jsx
- src/components/program/tests/Program.test.jsx
- src/components/program/tests/ProgramHeader.test.jsx
- src/components/program/tests/ProgramSidebar.test.jsx
> fix: Fixed pacing description and add course Header.

- src/components/program/ProgramCourses.jsx
> fix: Fixed a UI issue on production.

- src/components/program/ProgramInstructors.jsx
- src/components/program/ProgramMainContent.jsx
- src/components/program/styles/_ProgramInstructors.scss
- src/components/program/styles/index.scss
https://user-images.githubusercontent.com/6767924/139643745-c29d2137-f576-44b4-bdd6-41eaf0e0dd06.mov
> feat: refactor program instructors section and move after courses section

- src/components/course/CourseAssociatedPrograms.jsx
- src/components/course/tests/CourseAssociatedPrograms.test.jsx
> feat: redirect associated program to b2b program

- src/components/search/SearchProgramCard.jsx
> fix: truncate program title to avoid text overlap

- package-lock.json
- package.json
- src/components/program/ProgramHeader.jsx
- src/components/program/styles/_programDetail.scss
- src/components/program/styles/index.scss
- src/components/program/tests/Program.test.jsx
- src/components/program/tests/ProgramHeader.test.jsx
[ENT5102](https://openedx.atlassian.net/browse/ENT-5102): Top Banner image is added for the program detail page.
> feat: add banner at the top of B2B Program Detail page

- .env.development
- package-lock.json
- package.json
Reverts edx/frontend-app-learner-portal-enterprise#368
> Revert "fix: removed FEATURE_PROGRAM_TITLES_FACET flag and upgraded @edx/fron…"

- src/components/site-header/SiteHeader.jsx
> fix: add the logo class to the customer image element

- src/components/program/Program.jsx
- src/components/program/ProgramCourses.jsx
- src/components/program/data/hooks.jsx
- src/components/program/data/service.js
- src/components/program/data/tests/service.test.js
- src/components/program/styles/_ProgramCourses.scss
- src/components/program/styles/index.scss
- src/components/program/tests/ProgramCourses.test.jsx
> feat: add view course link in program page course accordion

- src/components/program/ProgramHeader.jsx
- src/components/program/styles/_programDetail.scss
- src/components/program/tests/ProgramHeader.test.jsx
> feat: add breadcrumbs to program detail page

- src/components/program/ProgramCTA.jsx
- src/components/program/styles/_programDetail.scss
> ENT-5075: fix: Fixed text overflow issue in links of menu items.

- src/components/program/ProgramCTA.jsx
- src/components/program/data/utils.jsx
- src/components/program/tests/ProgramCTA.test.jsx
> ENT-5075: refactor: removed duplicate code and fixed some UI issues.

- src/components/program/ProgramEndorsements.jsx
- src/components/program/styles/_endorsements.scss
> fix: resolve issue with no individual endorsements and margin

- src/components/program/ProgramHeader.jsx
> refactor: added urlencoding for subjects

- src/components/program/ProgramCTA.jsx
- src/components/program/ProgramCourses.jsx
- src/components/program/tests/Program.test.jsx
- src/components/program/tests/ProgramCTA.test.jsx
- src/components/program/tests/ProgramCourses.test.jsx
- src/components/program/tests/ProgramMainContent.test.jsx
- src/components/search/SearchProgramCard.jsx
- src/components/search/tests/SearchProgramCard.test.jsx
> feat: add events on program page

- src/components/skills-quiz/SearchJobDropdown.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/tests/SearchCurrentJobCard.test.jsx
- src/components/skills-quiz/tests/SearchFilters.test.jsx
- src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx
https://user-images.githubusercontent.com/49611774/141963139-eeefb53e-2d7d-49cd-8be4-0c1715af935e.mov
> feat: add interactive display of skills quiz drop-downs and tests

- src/components/skills-quiz/SkillsQuizStepper.jsx
https://user-images.githubusercontent.com/49611774/142184615-74975d14-7bdc-4d3c-970d-c3af06ed7844.mov
> fix: add support for link sharing of skills quiz page with some selections

- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
> refactor: Change the skills quiz course page title and stepper name

- src/components/skills-quiz/JobCardComponent.jsx
- src/components/skills-quiz/SelectJobCard.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/styles/SkillsQuizDropdowns.scss
- src/components/skills-quiz/tests/SelectJobCard.test.jsx
> refactor: Show N/A if labor market data is not available, and display complete job name

- src/components/skills-quiz/SelectJobCard.jsx
> Refactor: Adjust the column size

- src/components/system-wide-banner/SystemWideWarningBanner.jsx
> fix: use PageBanner from Paragon

- src/components/skills-quiz/SelectJobCard.jsx
> refactor: Re adjust the sizing in select job card

- src/components/search/SearchProgramCard.jsx
- src/components/skills-quiz/SearchProgramCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/data/utils.jsx
- src/components/skills-quiz/styles/_SearchContentCard.scss
- src/components/skills-quiz/styles/index.scss
- src/components/skills-quiz/tests/SearchProgramCard.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-5142
> feat: Programs on Skills Quiz Result Page

- src/components/skills-quiz/SelectedJobSkills.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/styles/SelectedJobSkills.scss
- src/components/skills-quiz/styles/index.scss
- src/components/skills-quiz/tests/SelectedJobSkills.test.jsx
> feat: Show skills for selected job on recommended course page

- src/components/skills-quiz/SelectedJobSkills.jsx
> fix: Skills quiz page was crashing when goal is to improve at current role

- src/components/search/popular-courses/PopularCoursesIndex.jsx
- src/components/search/tests/SearchResults.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-5157
> fix: Most popular courses show courses inside catalog

- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/tests/SearchFilters.test.jsx
- src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx
https://openedx.atlassian.net/browse/ENT-5288
> fix: set distinct on skills quiz dropdown facet to remove duplication

- src/components/pathway/SearchPathwayCard.jsx
- src/components/pathway/styles/_SearchContentCard.scss
- src/components/pathway/styles/index.scss
- src/components/pathway/tests/SearchPathwayCard.test.jsx
- src/components/pathway/tests/constants.js
- src/index.scss
This PR creates a card style for a pathway.
Here is the screenshot of the new component.
> ENT-5258: Added a new component to show pathway discovery card.

- src/components/dashboard/Dashboard.jsx
- src/components/dashboard/main-content/DashboardMainContent.jsx
- src/components/dashboard/tests/Dashboard.test.jsx
Ticket: [ENT-5132](https://openedx.atlassian.net/browse/ENT-5132)
Updates the zero state messaging for when user has no course enrollments.
> fix: update zero enrollments messaging on dashboard

- src/components/skills-quiz/styles/_SkillsQuizHeader.scss
> fix: add max-height to contain background image height

- src/components/skills-quiz/styles/_SkillsQuizHeader.scss
> fix: fix height with min-height to prevent resize on step change

- src/components/skills-quiz/SkillsQuizStepper.jsx
> style: add Margin top for skills-quiz steps

- src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
- src/components/enterprise-user-subsidy/data/hooks.js
- src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
- src/components/enterprise-user-subsidy/tests/hooks.test.jsx
- use subscription plan from customer agreement rather than license
> feat: use subscription plan from customer agreement

- src/components/dashboard/main-content/course-enrollments/course-cards/email-settings/data/service.js
The url got updated a month ago and it's been broken 😢 .
> fix: update change email settings url

- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx
> feat: add currently a student checkbox

- src/components/skills-quiz/CourseCard.jsx
- src/components/skills-quiz/SearchCourseCard.jsx
- src/components/skills-quiz/SkillsCourses.jsx
> refactor: single source of truth for skills quiz course cards

- src/components/course/Course.jsx
- src/components/course/CourseHeader.jsx
- src/components/course/LicenseRequestedAlert.jsx
- src/components/course/data/constants.js
- src/components/course/tests/CourseHeader.test.jsx
- src/components/course/tests/LicenseRequestedAlert.test.jsx
- src/components/enterprise-subsidy-requests/data/service.js
- src/components/enterprise-user-subsidy/UserSubsidy.jsx
https://openedx.atlassian.net/browse/ENT-5326
- Show alert on course about page if user has a pending license request, has an applicable subscription, and has not dismissed the alert before
> feat: add license requested alert to course about page

- src/components/skills-quiz/SkillsCourses.jsx
- src/components/skills-quiz/data/tests/utils.test.jsx
- src/components/skills-quiz/data/utils.jsx
Skills are first ranked based on # of courses in descending order and then on significance. 
https://openedx.atlassian.net/browse/ENT-5375
https://user-images.githubusercontent.com/55431213/153414615-d106b79d-8315-4ced-9df9-3cecfbc41714.mov
> feat: Rank skills based on # of courses on see more courses page

- package-lock.json
- package.json
- src/components/search/Search.jsx
> feat: bump catalog search version and pass relevant props

- src/components/Toasts/Toasts.jsx
- src/components/Toasts/ToastsProvider.jsx
- src/components/Toasts/index.js
- src/components/app/App.jsx
- src/components/course/CourseHeader.jsx
- src/components/course/CourseRunCard.jsx
- src/components/course/CourseRunCards.jsx
- src/components/course/SubsidyRequestButton.jsx
- src/components/course/enrollment/EnrollAction.jsx
- src/components/course/enrollment/constants.js
- src/components/course/enrollment/utils.js
- src/components/course/tests/CourseHeader.test.jsx
- src/components/course/tests/CourseRunCard.test.jsx
- src/components/enterprise-subsidy-requests/SubsidyRequestsContextProvider.jsx
- src/components/enterprise-subsidy-requests/data/hooks.js
- src/components/enterprise-subsidy-requests/data/service.js
- src/components/enterprise-subsidy-requests/data/tests/hooks.test.jsx
Adds the ability to request subsidy in learner portal when configured.
> Subsidy request button

- src/components/app/App.jsx
- src/components/program-progress/ProgramProgressContextProvider.jsx
- src/components/program-progress/ProgramProgressPage.jsx
- src/components/program-progress/data/hooks.jsx
- src/components/program-progress/data/service.js
- src/components/program/ProgramContextProvider.jsx
This is Skeleton page with context provider.
> feat: added Provider for ProgramProgress

- src/components/enterprise-subsidy-requests/data/hooks.js
- src/components/enterprise-subsidy-requests/data/tests/hooks.test.jsx
> fix: fix usage of subsidiesRequestContext in hook

- src/components/program-progress/ProgramListingCard.jsx
- src/components/program-progress/index.js
- src/components/program-progress/styles/_ProgramListingCard.scss
- src/components/program-progress/styles/index.scss
> style: fix card style and add program type icon

- src/components/program-progress/ProgramListingCard.jsx
- src/components/program-progress/tests/ProgramListing.test.jsx
- src/components/program-progress/tests/ProgramListingCard.test.jsx
> fix: change logoImage to logoImageUrl

- src/components/app/App.jsx
- src/components/dashboard/sidebar/OfferSummaryCard.jsx
- src/components/dashboard/sidebar/SidebarCard.jsx
- src/components/dashboard/sidebar/SubscriptionSummaryCard.jsx
- src/components/dashboard/sidebar/SubsidiesSummary.jsx
- src/components/dashboard/sidebar/data/constants.js
- src/components/dashboard/sidebar/styles/_SidebarCard.scss
- src/components/dashboard/sidebar/tests/SubscriptionSummaryCard.test.jsx
- src/components/program-progress/CouponCodesWarningModal.jsx
- src/components/program-progress/ProgramProgress.jsx
- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/program-progress/ProgramProgressPage.jsx
- src/components/program-progress/SubscriptionExpiringWarningModal.jsx
- src/components/program-progress/data/constants.js
- src/components/program-progress/data/utils.jsx
- src/components/program-progress/styles/ProgramProgressCourses.scss
- src/components/program-progress/styles/index.scss
- src/components/program-progress/tests/ProgramProgressCourses.test.jsx
- src/components/search/tests/constants.js
[ENT-5387](https://openedx.atlassian.net/browse/ENT-5387)
[ENT-5388](https://openedx.atlassian.net/browse/ENT-5388)
https://user-images.githubusercontent.com/11922730/161525600-9ce29060-43ee-4638-9827-73a2521cb525.mp4
> feat: create subsidy message page and add course detail for program progress page

- package-lock.json
- package.json
- src/components/pathway/PathwayModal.jsx
- src/components/pathway/SearchPathwayCard.jsx
- src/components/pathway/constants.js
- src/components/pathway/styles/_SearchContentCard.scss
- src/components/pathway/tests/PathwayModal.test.jsx
- src/components/pathway/tests/SearchPathwayCard.test.jsx
- src/components/pathway/tests/constants.js
- src/components/search/SearchResults.jsx
- src/components/search/popular-results/PopularResults.jsx
- src/components/search/tests/SearchResults.test.jsx
**[ticket](https://openedx.atlassian.net/browse/ENT-5637)**
https://user-images.githubusercontent.com/49611774/163144163-b5d8d0db-68ac-49a6-a237-8ed7d5634d8d.mov
> fix: resolve issues with pathway feature

- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/program-progress/data/constants.js
- src/components/program-progress/data/utils.jsx
- src/components/program-progress/styles/ProgramProgressCourses.scss
- src/components/program-progress/tests/ProgramProgressCourses.test.jsx
> refactor: Remove the expired course runs from dropdown

- src/components/program-progress/ProgramProgressHeader.jsx
- src/components/program-progress/ProgramProgressPage.jsx
- src/components/program-progress/ProgramProgressSidebar.jsx
- src/components/program-progress/data/tests/utils.test.jsx
- src/components/program-progress/data/utils.jsx
- src/components/program-progress/styles/_ProgramProgressCircle.scss
- src/components/program-progress/styles/_ProgramProgressHeader.scss
> refactor: Design related small changes for program progress feature

- src/components/program-progress/ProgramProgressCircle.jsx
- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/program-progress/styles/_ProgramProgressCircle.scss
> refactor: Design changes for program progress page sidebar

- src/components/program-progress/ProgramProgressCircle.jsx
- src/components/program-progress/styles/_ProgramProgressCircle.scss
> refactor: Design changes for program progress page sidebar circle

- src/components/pathway/PathwayModal.jsx
- src/components/pathway/SearchPathwayCard.jsx
- src/components/pathway/tests/SearchPathwayCard.test.jsx
- src/components/pathway/tests/constants.js
> feat: change banner_img to card_img, render course description html

- public/index.html
https://openedx.atlassian.net/browse/ENT-5715
[Local testing notes](https://openedx.atlassian.net/browse/ENT-5715?focusedCommentId=610516)
> feat: add optimizely token

- src/components/course/Course.jsx
- src/components/course/CourseContextProvider.jsx
- src/components/course/CourseRecommendationCard.jsx
- src/components/course/CourseRecommendations.jsx
- src/components/course/data/hooks.jsx
- src/components/course/data/service.js
- src/components/course/styles/CourseRecommendationCard.scss
- src/components/course/styles/CourseRecommendations.scss
- src/components/course/tests/CourseRecommendationCard.test.jsx
- src/components/course/tests/CourseRecommendations.test.jsx
- src/index.scss
https://user-images.githubusercontent.com/55431213/163983271-a4bc825c-6859-4590-9665-8fe7f3ce0502.mov
> feat: Show Course Recommendations in Course About Page

- src/components/pathway/PathwayModal.jsx
- src/components/pathway/styles/_PathwayModal.scss
https://user-images.githubusercontent.com/49611774/164457889-9ea6b5d1-1034-4ed0-ae65-41e63f3e7421.mov
> style: change style of pathway modal banner image

- src/components/program-progress/CouponCodesWarningModal.jsx
- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/program-progress/SubscriptionExpiringWarningModal.jsx
- src/components/program-progress/data/constants.js
- src/components/program-progress/data/utils.jsx
- src/components/program-progress/styles/ProgramProgressCourses.scss
- src/components/program-progress/tests/ProgramProgressCourses.test.jsx
> feat: Show upgrade to verified message for in progress course

- src/components/app/App.jsx
- src/components/pathway/SearchPathwayCard.jsx
- src/components/pathway/constants.js
- src/components/pathway/styles/_SearchContentCard.scss
- src/components/pathway/tests/SearchPathwayCard.test.jsx
- src/components/search/Search.jsx
- src/components/skills-quiz/SearchPathways.jsx
- src/components/skills-quiz/SearchProgramCard.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/tests/SearchPathways.test.jsx
> feat: Show Pathways on Skills Quiz Results Page

- src/components/dashboard/sidebar/OfferSummaryCard.jsx
- src/components/dashboard/sidebar/SubsidiesSummary.jsx
- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/program-progress/ProgramProgressPage.jsx
- src/components/program-progress/data/tests/utils.test.jsx
- src/components/program-progress/data/utils.jsx
> feat: Show Coupon and subscription warning modal for enrolled upgradable courses

- src/components/course/data/service.js
https://2u-internal.atlassian.net/browse/ENT-5816
> fix: same course recommendations do not appear under both headers

- src/components/course/CourseRecommendationCard.jsx
- src/components/course/CourseRunCard.jsx
- src/components/pathway/SearchPathwayCard.jsx
- src/components/pathway/styles/_SearchContentCard.scss
- src/components/search/SearchCourseCard.jsx
- src/components/search/SearchProgramCard.jsx
- src/components/search/styles/_SearchResults.scss
- src/components/skills-quiz/CourseCard.jsx
- src/components/skills-quiz/JobCardComponent.jsx
- src/components/skills-quiz/SearchProgramCard.jsx
- src/components/skills-quiz/SelectJobCard.jsx
- src/components/skills-quiz/styles/_SearchContentCard.scss
> fix: fix some problems with Paragon 19 cards

- src/components/dashboard/sidebar/SubscriptionSummaryCard.jsx
> fix: check subscription exists before showing expiration warning modal

- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/program-progress/styles/ProgramProgressCourses.scss
> Increase space between text and course count

- src/components/course/CoursePage.jsx
- src/components/course/data/service.js
- src/components/course/data/tests/service.test.js
- src/components/course/tests/constants.js
> feat: filter recommendations based on subsidy request catalogs

- src/components/course/data/hooks.jsx
> feat: add source query param in data sharing consent url

- .github/workflows/ci.yml
- package-lock.json
- package.json
- src/components/app/App.jsx
> fix: downgrade hotjar temporarily

- src/components/course/CoursePage.jsx
JIRA: https://2u-internal.atlassian.net/browse/ENT-5847
> feat: trigger segment event when course page hits 404

- package-lock.json
- package.json
- src/components/app/App.jsx
Removed react-use-hotjar in favor of @edx/frontend-enterprise-hotjar
> feat: switch to using frontend-enterprise hotjar library

- src/components/app/App.jsx
> fix: pass bool for hotjarDebug instead of empty string

- src/components/course/CourseSidebarPrice.jsx
- src/components/course/data/tests/utils.test.jsx
- src/components/course/data/utils.jsx
- src/components/enterprise-page/data/hooks.js
- src/components/enterprise-user-subsidy/UserSubsidy.jsx
- src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/hooks.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/service.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/tests/hooks.test.jsx
- src/components/enterprise-user-subsidy/enterprise-offers/data/tests/service.test.js
https://2u-internal.atlassian.net/browse/ENT-5892
> feat: hook up enerprise offers api

- src/components/enterprise-user-subsidy/enterprise-offers/data/hooks.js
> feat: add additional logging, add enableOffers to dependency array

- src/components/course/CourseSidebarPrice.jsx
- src/components/course/EnrollModal.jsx
- src/components/course/data/tests/utils.test.jsx
- src/components/course/data/utils.jsx
- src/components/course/tests/CourseSidebarPrice.test.jsx
- src/components/course/tests/EnrollModal.test.jsx
- src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/hooks.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/service.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/tests/hooks.test.jsx
- src/components/enterprise-user-subsidy/enterprise-offers/data/tests/service.test.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/tests/utils.test.js
- src/components/enterprise-user-subsidy/enterprise-offers/data/utils.js
- Handle offers that have no limits
- Handle offers with max enrollments limit instead of bookings limit
> feat: support offers with enrollments limit & no limits

- src/components/dashboard/sidebar/EnterpriseOffersSummaryCard.jsx
- src/components/dashboard/sidebar/tests/EnterpriseOffersSummaryCard.test.jsx
> fix: don't show infinite credit

- src/components/course/CourseEnrollmentFailedAlert.jsx
- src/components/course/CourseHeader.jsx
- src/components/course/data/constants.js
- src/components/course/data/hooks.jsx
- src/components/course/data/utils.jsx
- src/components/course/tests/CourseEnrollmentFailedAlert.test.jsx
- src/components/course/tests/CourseHeader.test.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.js
To merge against base branch for 5828.
- Update alert messaging for when an upgrade fails.
- Added alert to the dashboard.
> feat: add alert for upgrade error

- src/components/course/CourseEnrollmentFailedAlert.jsx
- src/components/course/CourseHeader.jsx
- src/components/course/CourseRunCard.jsx
- src/components/course/EnrollModal.jsx
- src/components/course/data/constants.js
- src/components/course/data/hooks.jsx
- src/components/course/data/service.js
- src/components/course/data/tests/hooks.test.jsx
- src/components/course/data/utils.jsx
- src/components/course/enrollment/components/ToDataSharingConsent.jsx
- src/components/course/tests/CourseEnrollmentFailedAlert.test.jsx
- src/components/course/tests/CourseHeader.test.jsx
- src/components/course/tests/EnrollModal.test.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/dashboard/main-content/course-enrollments/CourseSection.jsx
- src/components/dashboard/main-content/course-enrollments/UpgradeableCourseEnrollmentContextProvider.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx
- src/components/dashboard/main-content/course-enrollments/data/hooks.js
- src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.js
- src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/CourseSection.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js
- src/components/dashboard/sidebar/tests/EnterpriseOffersSummaryCard.test.jsx
- src/constants/course.js
- src/constants/index.js
https://2u-internal.atlassian.net/browse/ENT-5828
- support upgrading a course using a license from the dashboard - only applicable to audit courses in progress
- added common constants folder
- minor clean ups
> feat: support upgrading course with license from dashboard

- src/components/app/EnterpriseAppPageRoutes.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/dashboard/main-content/DashboardMainContent.jsx
- src/components/dashboard/tests/DashboardPage.test.jsx
- src/components/program-progress/ProgramListingPage.jsx
- src/components/site-header/SiteHeader.jsx
[Ticket](https://2u-internal.atlassian.net/browse/ENT-5975)
https://user-images.githubusercontent.com/49611774/179753511-f63351b5-0153-4106-aa02-d64d65042681.mov
> feat: change layout of dashboard page to accommodate all progress types

- package-lock.json
- package.json
> chore: upgrade @edx/frontend-build to v12

- src/components/app/EnterpriseAppPageRoutes.jsx
- src/components/program-progress/ProgramListingCard.jsx
- src/components/program-progress/ProgramProgressRedirect.jsx
- src/components/program-progress/index.js
- src/components/program-progress/tests/ProgramListingCard.test.jsx
> ENT-6075: Updated the program progress page url path to match the conventions.

- src/components/executive-education-2u/ExecutiveEducation2UPage.jsx
- src/components/executive-education-2u/ExecutiveEducation2UPage.test.jsx
- src/components/executive-education-2u/UserEnrollmentForm.jsx
- src/components/executive-education-2u/UserEnrollmentForm.test.jsx
- src/components/executive-education-2u/data/service.js
https://2u-internal.atlassian.net/browse/ENT-6164
> feat: integrate with POST checkout for exec ed enrollment

- src/components/executive-education-2u/data/service.js
> fix: remove trailing slash as a test

- src/components/executive-education-2u/data/service.js
This reverts commit 2274db8794e48561db29b0308e9071b46d4a72da.
> Revert "fix: remove trailing slash as a test (#609)"

- src/components/executive-education-2u/UserEnrollmentForm.jsx
- src/components/executive-education-2u/UserEnrollmentForm.test.jsx
> fix: ensure DOB is passed in POST payload

- src/components/enterprise-user-subsidy/UserSubsidy.jsx
- src/components/enterprise-user-subsidy/data/hooks.js
- src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6182
> fix: check is enterprise learner before getting auto applied license

- package-lock.json
- package.json
- src/components/pathway-progress/PathwayNode.jsx
- src/components/pathway-progress/PathwayProgressContextProvider.jsx
- src/components/pathway-progress/PathwayProgressHeader.jsx
- src/components/pathway-progress/PathwayProgressPage.jsx
- src/components/pathway-progress/PathwayRequirements.jsx
- src/components/pathway-progress/constants.js
- src/components/pathway-progress/data/service.js
- src/components/pathway-progress/data/utils.js
- src/components/pathway-progress/styles/_PathwayRequirements.scss
- src/components/pathway-progress/utils.js
__Jira Ticket:__ [ENT-6076](https://2u-internal.atlassian.net/browse/ENT-6076)
This PR is for integrating learner pathway progress details page with the backend API. This PR also fixes some of the UI/UX issues after the backend integration.
> ENT-6076: Integrated pathway progress details page with the backend.

- src/components/executive-education-2u/UserEnrollmentForm.jsx
- src/components/executive-education-2u/UserEnrollmentForm.test.jsx
> feat: add complete state for exec ed enrollment button

- src/components/pathway-progress/PathwayNode.jsx
- src/components/pathway-progress/data/__mocks__/PathwayProgressListData.json
- src/components/pathway-progress/styles/_PathwayRequirements.scss
- src/components/pathway-progress/tests/PathwayNode.test.jsx
__Jira Ticket:__ [ENT-6077](https://2u-internal.atlassian.net/browse/ENT-6077)
This PR fixes some UI/UX issues for the pathway progress details page. Changes are small and are to conform the page with the mockups provided on the ticket.
> fix: Fixed UI issues with pathway progress details page.

- package-lock.json
- package.json
Guided dependency upgrade to fix errors
> chore: Dependency Upgrade

- .github/workflows/ci.yml
> build: add codecov back to CI

- src/components/program/data/tests/utils.test.jsx
- src/components/program/data/utils.jsx
- src/components/program/tests/ProgramCTA.test.jsx
- src/components/program/tests/ProgramSidebar.test.jsx
> fix: Change the program length calculation method

- src/components/pathway-progress/PathwayNode.jsx
- src/components/pathway-progress/PathwayProgressHeader.jsx
- src/components/pathway-progress/styles/_PathwayProgressHeader.scss
- src/components/pathway-progress/styles/index.scss
Fixes for visual inconsistencies. More details can be found in the comments of https://2u-internal.atlassian.net/browse/ENT-6282
> fix: Fixes for visual inconsistencies.

- package-lock.json
- package.json
Pulls in the following style fix: https://github.com/openedx/paragon/pull/1863
> chore: upgrade @edx/paragon to bring in style fix

- src/components/search/SearchCourseCard.jsx
- src/components/search/data/hooks.js
> feat: delay before sending event on optimizely

- src/components/search/SearchResults.jsx
> fix: ensure .search-results has .my-5

- src/components/search/Search.jsx
- src/components/search/SearchProgramCard.jsx
- src/components/search/SearchResults.jsx
- src/components/search/data/hooks.js
- src/components/skills-quiz/SearchProgramCard.jsx
> fix: address style issues and resolve JS errors

- src/components/search/content-highlights/data/utils.js
> fix: fix typo in search

- package-lock.json
- package.json
Pulls in https://github.com/openedx/paragon/pull/1910 and https://github.com/edx/brand-edx.org/pull/50 (resolves https://github.com/openedx/paragon/issues/1903, among other found button style discrepancies).
> chore: upgrade @edx/paragon to latest to pull in button style fixes

- src/components/search/content-highlights/data/service.js
Fix to enterprise curations URL `getEnterpriseCuration`
> fix: curations URL

- src/components/course/data/hooks.jsx
- src/components/course/data/tests/hooks.test.jsx
Ticket:https://2u-internal.atlassian.net/browse/ENT-6728
Updates logic for weeks to complete to take into account 0 weeks.
Adds corresponding tests.
> fix: update weeks to complete logic

- src/components/my-career/MyCareerTab.jsx
- src/components/my-career/VisualizeCareer.jsx
- src/components/my-career/data/service.js
- src/components/my-career/data/tests/service.test.jsx
- src/components/my-career/data/utils.jsx
- src/components/my-career/styles/_MyCareer.scss
- src/components/my-career/styles/_MyCareerChart.scss
Made changes according to these skills quiz API changes in taxonomy connector https://github.com/openedx/taxonomy-connector/pull/143. Fixed width for plotly chart.
> fix: skill quiz fixes for my career tab

- src/components/skills-quiz/TopSkillsOverview.jsx
- src/components/skills-quiz/styles/TopSkillsOverview.scss
> fix: fixed text overflow issue on skills quiz

- src/components/search/Search.jsx
[Ticket](https://2u-internal.atlassian.net/browse/ENT-6683)
Adds a conditional to hasRefinements to check contentTypes length individually on top of the current facet filters filter that exist.
> fix: Adds additional conditional for contentType

- src/components/my-career/CategoryCard.jsx
- src/components/my-career/LevelBars.jsx
- src/components/my-career/data/hooks.jsx
- src/components/my-career/data/utils.jsx
- src/components/my-career/tests/Hooks.test.jsx
Here is a screenshot after resolving the bugs.
- Remove Chart tools
- Filled skill bars on Completion data
- Show that skills too in a subCategory that the learner does not acquire
- Replace a Chip with a Button Component
> fix: resolve issues in career chart

- src/components/course/CourseHeader.jsx
> fix: Change course review section visibility

- package-lock.json
- package.json
- src/components/executive-education-2u/UserEnrollmentForm.jsx
- src/components/stateful-enroll/StatefulEnroll.jsx
- src/components/stateful-enroll/data/hooks/useTransactionStatus.js
- src/components/stateful-enroll/data/service.js
> fix: typo in `UserEnrollmentForm` form validation and use actual course run in courseware redirect in mock api response

- src/components/course/CourseContextProvider.jsx
- src/components/course/CoursePage.jsx
- src/components/course/CourseReview.jsx
- src/components/course/course-header/CourseHeader.jsx
- src/components/course/course-header/tests/CourseHeader.test.jsx
- src/components/course/data/constants.js
- src/components/course/data/hooks.jsx
- src/components/course/data/service.js
- src/components/course/data/tests/service.test.js
- src/components/course/data/utils.jsx
- src/components/course/tests/CoursePage.test.jsx
- src/components/course/tests/constants.js
> feat: Called the course review api to show course reviews

- src/components/course/CourseReview.jsx
- src/components/course/course-header/tests/CourseHeader.test.jsx
- src/components/course/data/hooks.jsx
> fix: fix the count related message issues

- src/components/course/course-header/CourseHeader.jsx
- src/components/course/course-header/tests/CourseHeader.test.jsx
- src/index.jsx
Description: This PR adds an Optimizely experiment for the CourseReview component.
JIRA: [ENT-6797](https://2u-internal.atlassian.net/browse/ENT-6797)
> feat: added Optimizely experiment for CourseReview component

- src/components/site-header/SiteHeaderLogos.jsx
- src/components/site-header/styles/_Header.scss
Related PR: https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/724
> chore: header logo styles refactor

- src/components/skills-quiz/JobDescriptions.jsx
- src/components/skills-quiz/TopSkillsOverview.jsx
- src/components/skills-quiz/constants.js
- src/components/skills-quiz/data/hooks.js
- src/components/skills-quiz/data/service.js
- src/components/skills-quiz/tests/JobDescriptions.test.jsx
> feat: ai generated job descriptions

- src/components/skills-quiz/TopSkillsOverview.jsx
> fix: resolve bug with showing similar jobs

- src/components/course/course-header/data/hooks/useCourseRunCardAction.jsx
- src/components/course/course-header/data/hooks/useCourseRunCardData.js
- src/components/course/data/hooks.jsx
- src/components/course/enrollment/tests/utils.test.js
- src/components/course/enrollment/utils.js
Ticket: https://2u-internal.atlassian.net/browse/ENT-7256
Reverts https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/753
> fix: update CTA for exec ed enrollments on course page

- src/components/executive-education-2u/components/CourseSummaryCard.jsx
Strikethrough on price for exec ed enrollment flow as per this [ticker](https://2u-internal.atlassian.net/browse/ENT-7292)
> feat: adds strikethrough on price for exec ed

- package-lock.json
- package.json
> ENT-7171: upgrade @edx/frontend-enterprise-catalog-search to 4.4.0

- src/components/course/course-header/CourseHeader.jsx
**Description** This PR adds a segment event that is sent when a learner views a course with the course reviews variation
**JIRA** [ENT-7245](https://2u-internal.atlassian.net/browse/ENT-7245)
> feat: Added segment event for course view with reviews

- src/components/my-career/AddJobRole.jsx
- src/components/my-career/MyCareerTab.jsx
- src/components/my-career/SearchJobRole.jsx
- src/components/my-career/VisualizeCareer.jsx
- src/components/my-career/data/constants.js
- src/components/my-career/data/hooks.jsx
- src/components/my-career/data/service.js
- src/components/my-career/data/tests/service.test.jsx
- src/components/my-career/data/utils.jsx
- src/components/my-career/tests/MyCareerTab.test.jsx
- src/components/my-career/tests/SearchJobRole.test.jsx
- src/utils/hooks.jsx
> feat: improve job edit flow career chart

- src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/styles/_CourseCard.scss
> fix: Updated text color for the CTA link to white.

- src/components/dashboard/DashboardPage.jsx
- src/components/my-career/SkillsRecommendationCourses.jsx
- src/components/my-career/VisualizeCareer.jsx
- src/components/my-career/tests/VisualizeCareer.test.jsx
- src/components/search/SearchCourseCard.jsx
> feat: Add Segment event for career chart

- src/components/course/data/tests/utils.test.jsx
- src/components/course/data/utils.jsx
> fix: ensure cases for exhausted subs works with multiple subs

- package-lock.json
- package.json
- src/components/course/data/tests/utils.test.jsx
- src/components/course/data/utils.jsx
> fix: fast follow to 7223 coupon codes

- src/components/skills-quiz-v2/ClosingAlert.jsx
- src/components/skills-quiz-v2/SkillsQuiz.jsx
- src/components/skills-quiz-v2/constants.js
> feat: added course card, job card and alert modal

- src/components/course/data/hooks.jsx
- src/components/course/data/tests/hooks.test.jsx
- src/components/course/data/tests/utils.test.jsx
- src/components/course/data/utils.jsx
In this PR, the order of logic when choosing an applicable subsidy should be this:
1. Subscriptions
2. Coupon Codes
3. Learner Credit
4. Enterprise offers
Additionally, the priority of disabled enrollment reasons are:
1. Course not in catalog
2. Subscriptions related disabled enrollment reason
3. Coupon codes related disabled enrollment reason
4. Learner Credit related disabled enrollment reason.
5. Enterprise offers related disabled enrollment reason# For all changes
> ENT-7663: Refactor applicable subsidy

- src/components/course/course-header/tests/CourseRunCard.test.jsx
> fix: test fix-up for CourseRunCard

- src/components/dashboard/sidebar/SupportInformation.jsx
- src/components/enterprise-page/data/hooks.js
> feat: Added Career Engagement Network sidebar message

- src/components/course/course-header/data/hooks/tests/useCourseRunCardAction.test.jsx
- src/components/course/course-header/data/hooks/useCourseRunCardAction.jsx
Remove  FEATURE_ENABLE_EMET_AUTO_UPGRADE_ENROLLMENT_MODE feature flag.
> chore: remove FEATURE_ENABLE_EMET_AUTO_UPGRADE_ENROLLMENT_MODE

- src/components/search/content-highlights/ContentHighlightSet.jsx
**Description:** Remove highlight subtitle for now.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-7744
> chore: remove highlight subtitle

- package-lock.json
- package.json
Continuation of the https://2u-internal.atlassian.net/browse/ENT-7747 ticket and removing the `Free/All` filter
> fix: updating catalog-search

- src/components/course/CourseSidebar.jsx
- src/components/course/tests/CourseSidebar.test.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/dashboard/tests/DashboardPage.test.jsx
- src/components/enterprise-page/data/hooks.js
> feat: disable pathways for VSF

- src/components/course/CourseSidebar.jsx
- src/components/course/tests/CourseSidebar.test.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/dashboard/tests/DashboardPage.test.jsx
- src/components/enterprise-page/data/hooks.js
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-7766
> feat: disable programs and associated programs for vsf

- src/components/dashboard/main-content/course-enrollments/CourseSection.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/AssignedCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/index.js
- src/components/dashboard/main-content/course-enrollments/course-cards/tests/AssignedCourseCard.test.jsx
- src/components/dashboard/main-content/course-enrollments/data/constants.js
- src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.js
- src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js
- src/components/dashboard/main-content/course-enrollments/tests/CourseSection.test.jsx
- src/constants/course.js
__Jira Ticket:__ [ENT-7665](https://2u-internal.atlassian.net/browse/ENT-7665)
This PR adds a new component `AssignedCourseCard` that will be used by assigned courses functionality later on.
__Screenshot:__
> ENT-7665: Added a new component AssignedCourseCard to show user course assignments.

- src/components/app/AuthenticatedPage.jsx
This reverts commit 0c2987025ef67a7a078f59e8d1a0aba23f3e3b79.
> Revert "fix: temporarily remove caching from customer config (#848)"

- src/components/enterprise-page/EnterprisePage.jsx
> fix: re-render EnterprisePage component by subscribing to AppContext

- src/components/enterprise-invite/EnterpriseInvitePage.jsx
- src/components/enterprise-invite/EnterpriseInvitePage.test.jsx
- webpack.dev.config.js
> fix: resolve universal link

- src/components/enterprise-redirects/EnterpriseLearnerFirstVisitRedirect.jsx
- src/components/enterprise-redirects/tests/EnterpriseLearnerFirstVisitRedirect.test.jsx
> fix: first visit redirect

- src/components/course/course-header/data/hooks/useCourseRunCardAction.jsx
- src/components/course/course-header/data/hooks/useCourseRunCardData.js
- src/components/dashboard/main-content/course-enrollments/course-cards/AssignedCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/tests/AssignedCourseCard.test.jsx
> ENT-7668: Enabled enroll button on assigned course cards.

- src/components/dashboard/main-content/course-enrollments/course-cards/AssignedCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/CompletedCourseCard.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/ContinueLearningButton.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/styles/_CourseCard.scss
- src/components/dashboard/main-content/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-7843
**Figma Designs**: https://www.figma.com/file/8da9TyEpEzgxQld3DZE67w/LC2---Top-down-Assignment?type=design&node-id=2620%3A103165&mode=design&t=fIDwm0YtvXr5FUcy-1
**Description**: Updated all course card designs (Exec-ed and Non Exec-ed) as per figma designs.
**UI Screenshots**:
> feat: Updated course cards design

- src/components/dashboard/main-content/course-enrollments/course-cards/ContinueLearningButton.jsx
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-7843
**Description**: Changed course card resume/start button variant from "primary" to "outline-primary" so that its not overridden by theme colors.
> fix: updated course card resume button variant

- src/components/dashboard/main-content/course-enrollments/CourseSection.jsx
> fix: badge with bubble component for assigned courses count

- src/components/academies/AcademyDetailPage.jsx
- src/components/academies/AcademyPage.jsx
- src/components/academies/CourseCard.jsx
- src/components/academies/data/constants.js
- src/components/academies/data/hooks.js
- src/components/academies/data/service.js
- src/components/academies/data/tests/hooks.test.js
- src/components/academies/data/tests/service.test.js
- src/components/academies/index.js
- src/components/academies/tests/AcademyDetailPage.test.jsx
- src/components/course/CoursePage.jsx
- src/components/course/course-header/CourseHeader.jsx
- src/components/course/course-header/tests/CourseHeader.test.jsx
- src/components/course/tests/CoursePage.test.jsx
- src/components/search/SearchCourseCard.jsx
**Description:** Add an academy detail page.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-7687
> feat: add academies detail page

- src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx
> fix: empty courses state when top-down-assignment feature is disable

- src/components/academies/SearchAcademyCard.jsx
- src/components/academies/index.js
- src/components/academies/styles/Academy.scss
- src/components/app/EnterpriseAppPageRoutes.jsx
__Jira Ticket:__ [ENT-7686](https://2u-internal.atlassian.net/browse/ENT-7686)
This PR adds a missing route and small UI adjustments for academies related components.
> fix: Fixed some UX issues with academies pages.

- src/components/dashboard/sidebar/SubsidiesSummary.jsx
- src/components/enterprise-user-subsidy/UserSubsidy.jsx
- src/components/enterprise-user-subsidy/enterprise-offers/data/hooks.js
> feat: ENT-8091 hide course search in subsidy summary

- src/components/course/CourseSidebar.jsx
- src/components/course/tests/CourseSidebar.test.jsx
https://2u-internal.atlassian.net/browse/ENT-7916
> feat: keeping course sidebar hyperlinks within the enterprise environment

- src/components/course/CourseSidebar.jsx
> fix: encoding values passed into redirect

- src/components/skills-quiz/SkillsQuiz.jsx
- src/components/skills-quiz/tests/SkillsQuiz.test.jsx
- src/components/skills-quiz/tests/SkillsQuizPage.test.jsx
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-7367
**Description**: Switched to skill quiz builder v1 since some features were missing in v2
> fix: ENT-7367 Switched to skill quiz builder v1

- src/components/academies/data/constants.js
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-8199
> fix: typo on academy detail page

- src/components/skills-quiz/SkillsQuiz.jsx
- src/index.jsx
This PR adds an Optimizely experiment for two different skill quiz components.
Jira -> [[ENT-7371]](https://2u-internal.atlassian.net/browse/ENT-7371)
> feat: added Optimizely experiment for skill quiz components

- src/components/skills-quiz-v2/styles/_Header.scss
JIRA -> [ENT-8285](https://2u-internal.atlassian.net/browse/ENT-8256)
> fix: H2 Styling for Skills Builder leaked into Learner Portal

- src/components/utils/search.js
Fixed a typo in error message.
> fix: Fixed a typo in error message.

- src/components/academies/AcademyContentCard.jsx
- src/components/academies/data/constants.js
> feat: display and configure pathways section on academy detail page

- src/components/app/App.jsx
> fix: use named export

- src/components/course/routes/ExternalCourseEnrollment.jsx
- src/components/course/routes/ExternalCourseEnrollmentConfirmation.jsx
- src/components/executive-education-2u/EnrollmentCompletedSummaryCard.test.jsx
- src/components/executive-education-2u/UserEnrollmentForm.jsx
- src/components/executive-education-2u/UserEnrollmentForm.test.jsx
- src/components/executive-education-2u/components/CourseSummaryCard.jsx
- src/components/executive-education-2u/components/EnrollmentCompletedSummaryCard.jsx
- src/components/executive-education-2u/components/RegistrationSummaryCard.jsx
Jira -> [ENT-8350](https://2u-internal.atlassian.net/browse/ENT-8350)
> feat: mark static strings for i18n on EE course enrollment pages

- src/components/app/App.jsx
> fix: use * for not found page

- src/components/pathway-progress/PathwayNode.jsx
- src/components/pathway-progress/PathwayProgressHeader.jsx
- src/components/pathway-progress/PathwayRequirements.jsx
- src/components/pathway-progress/PathwayStep.jsx
- src/components/pathway-progress/SubscriptionStatusCard.jsx
- src/components/pathway-progress/tests/PathwayNode.test.jsx
- src/components/pathway-progress/tests/PathwayRequirements.test.jsx
- src/components/pathway-progress/tests/PathwayStep.test.jsx
- src/components/pathway-progress/tests/SubscriptionStatusCard.test.jsx
- src/components/pathway/PathwayModal.jsx
- src/components/pathway/tests/PathwayModal.test.jsx
Jira Ticket: https://2u-internal.atlassian.net/browse/ENT-8342
Description: Marked all pathways related strings for i18n
> ENT-8342 feat: marked pathways strings for i18n

- src/components/enterprise-page/EnterprisePage.test.jsx
- src/components/pathway-progress/tests/PathwayProgressListingCard.test.jsx
- src/components/program-progress/ProgramListingPage.jsx
- src/components/program-progress/ProgramPathwayOpportunity.jsx
- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/program-progress/ProgramProgressPage.jsx
- src/components/program-progress/ProgramProgressSidebar.jsx
- src/components/program-progress/data/constants.js
- src/components/program-progress/tests/ProgramListingCard.test.jsx
- src/components/program-progress/tests/ProgramListingPage.test.jsx
- src/components/program-progress/tests/ProgramPathwayOpportunity.test.jsx
- src/components/program-progress/tests/ProgramProgressCircle.test.jsx
- src/components/program-progress/tests/ProgramProgressCourses.test.jsx
- src/components/program-progress/tests/ProgramProgressSidebar.test.jsx
- src/components/progress-category-bubbles/ProgressCategoryBubbles.jsx
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-8341
**Description**: Marked all programs related strings for i18n
> ENT-8341 feat: marked programs strings for i18n

- src/components/search/Search.jsx
- src/components/search/SearchCourse.jsx
- src/components/search/SearchCourseCard.jsx
- src/components/search/SearchPathway.jsx
- src/components/search/SearchProgram.jsx
- src/components/search/SearchProgramCard.jsx
- src/components/search/SearchResults.jsx
- src/components/search/data/constants.js
- src/components/search/tests/SearchCourseCard.test.jsx
- src/components/search/tests/SearchProgramCard.test.jsx
- src/components/search/tests/SearchResults.test.jsx
- src/components/search/tests/SearchSections.test.jsx
> feat: mark static strings for i18n on search page

- src/components/search/SearchResults.jsx
- src/components/search/tests/SearchSections.test.jsx
> fix: change Results to results (typo)

- src/styles/nprogress.scss
> fix: update nprogress color and height styles

- src/components/app/data/constants.js
- src/components/app/data/hooks/useIsAssignmentsOnlyLearner.js
- src/components/app/data/index.js
- src/components/app/data/utils.js
- src/components/app/data/utils.test.js
- src/components/app/routes/data/services.js
- src/components/app/routes/data/utils.js
- src/components/course/course-header/tests/CourseHeader.test.jsx
- src/components/course/routes/CourseAbout.jsx
- src/components/course/routes/tests/CourseAbout.test.jsx
- src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx
- src/components/course/routes/tests/ExternalCourseEnrollmentConfirmation.test.jsx
- src/components/dashboard/main-content/DashboardMainContent.test.jsx
- src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
- src/components/dashboard/sidebar/SubsidiesSummary.jsx
- src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx
- src/components/dashboard/tests/DashboardPage.test.jsx
- src/components/enterprise-redirects/tests/EnterpriseLearnerFirstVisitRedirect.test.jsx
- src/components/enterprise-user-subsidy/data/constants.js
- src/components/enterprise-user-subsidy/data/hooks/hooks.js
- src/components/enterprise-user-subsidy/data/utils.js
- src/components/enterprise-user-subsidy/data/utils.test.js
- src/components/my-career/tests/CategoryCard.test.jsx
- src/components/my-career/tests/VisualizeCareer.test.jsx
- src/components/search/data/hooks.js
- src/components/search/data/tests/hooks.test.jsx
> fix: ensure find a course header nav is hidden for assignments-only

- public/index.html
Currently, optimizely is enabled on development mode and production mode. We want to also add a support for it in a staging environment. 
https://2u-internal.atlassian.net/browse/ENT-8555
> feat: add support for optimizely experiments on stage

- src/components/skills-quiz-v2/JobCardComponent.jsx
- src/components/skills-quiz-v2/SkillsQuiz.jsx
- src/components/skills-quiz-v2/SkillsQuizForm.jsx
- src/components/skills-quiz-v2/SkillsQuizHeader.jsx
- src/components/skills-quiz-v2/constants.js
- src/components/skills-quiz-v2/tests/SkillsQuiz.test.jsx
- src/components/skills-quiz-v2/tests/SkillsQuizForm.test.jsx
- src/components/skills-quiz-v2/tests/SkillsQuizHeader.test.jsx
- src/components/skills-quiz/JobCardComponent.jsx
- src/components/skills-quiz/SearchCourseCard.jsx
- src/components/skills-quiz/SearchPathways.jsx
- src/components/skills-quiz/SearchProgramCard.jsx
- src/components/skills-quiz/SelectJobCard.jsx
- src/components/skills-quiz/SkillsCourses.jsx
- src/components/skills-quiz/SkillsQuizHeader.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/components/skills-quiz/tests/SearchCourseCard.test.jsx
- src/components/skills-quiz/tests/SearchCurrentJobCard.test.jsx
- src/components/skills-quiz/tests/SearchFilters.test.jsx
- src/components/skills-quiz/tests/SearchJobCard.test.jsx
- src/components/skills-quiz/tests/SearchPathways.test.jsx
- src/components/skills-quiz/tests/SearchProgramCard.test.jsx
- src/components/skills-quiz/tests/SelectJobCard.test.jsx
- src/components/skills-quiz/tests/SkillsCourses.test.jsx
- src/components/skills-quiz/tests/SkillsQuiz.test.jsx
- src/components/skills-quiz/tests/SkillsQuizHeader.test.jsx
- src/components/skills-quiz/tests/SkillsQuizPage.test.jsx
- src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-8343
**description**: Marked skills-quiz strings for i18n
> [ENT-8343] feat: marked skills-quiz strings for i18n

- .tx/config
- Makefile
- package-lock.json
- package.json
This PR fixes some issues in the `Makefile`, introduces a required dependency and also update transfix config to use a different account for translations.
> ENT-8221: Used open-edx transifex account for translations.

- src/components/dashboard/sidebar/CouponCodesSummaryCard.jsx
- src/components/dashboard/sidebar/LearnerCreditSummaryCard.jsx
- src/components/dashboard/sidebar/SubscriptionSummaryCard.jsx
- src/components/dashboard/sidebar/tests/CouponCodesSummaryCard.test.jsx
- src/components/dashboard/sidebar/tests/SubscriptionSummaryCard.test.jsx
> feat: ENT-8344 Added i18n formatted strings for dashboard sidebar

- src/components/license-activation/LicenseNotFound.jsx
> fix: Change the dummy email to loggedin user email

- src/components/enterprise-page/EnterprisePage.jsx
- src/components/enterprise-page/EnterprisePage.test.jsx
> fix: merge conflict

- src/components/program/data/service.js
Updates function parameters to look for the object `course` as opposed to the argument course for [getAvailableCourseRuns
](https://github.com/openedx/frontend-app-learner-portal-enterprise/blob/33652b9dd38631d0e07573f6fc833b406fa64f08/src/components/course/data/utils.jsx#L141)
> fix: Update course reference in getAvailableCourseRuns

- src/components/license-activation/LicenseNotFound.jsx
> fix: Change the license not found page text

- Makefile
- package.json
- src/components/course/CourseReview.jsx
- src/components/dashboard/sidebar/SubscriptionSummaryCard.jsx
- src/components/pathway-progress/PathwayStep.jsx
- src/components/pathway/PathwayModal.jsx
- src/components/program-progress/ProgramProgressCourses.jsx
- src/components/site-header/menu/Menu.jsx
- src/components/skills-quiz/SkillsQuizStepper.jsx
- src/i18n/index.js
- src/index.jsx
- Fix duplicate string ids
- fix extract_translations script
Jira -> [ENT-8651](https://2u-internal.atlassian.net/browse/ENT-8651)
> fix: make extract_translations command

- src/components/app/data/services/subsidies/subscriptions.js
- src/components/app/data/utils.js
- src/components/course/LicenseRequestedAlert.jsx
> fix: handle null customer agreement

- src/components/course/course-header/deprecated/CourseRunCard.jsx
- src/components/course/data/utils.jsx
Fix for bug reported in https://2u-internal.atlassian.net/browse/ENT-8730
> fix: ensure license_uuid is passed in enrollment url

- src/components/academies/data/academiesLoader.test.js
- src/components/app/data/services/academies.js
- src/components/app/data/services/academies.test.js
- src/components/app/data/services/pathways.js
- src/components/app/data/services/pathways.test.js
- src/components/course/LicenseRequestedAlert.jsx
- src/components/pathway-progress/PathwayProgressCard.jsx
- src/components/pathway-progress/data/pathwayProgressLoader.test.js
- src/components/pathway-progress/tests/PathwayNode.test.jsx
- src/components/pathway-progress/tests/PathwayProgressListingCard.test.jsx
- src/components/pathway-progress/tests/PathwayRequirements.test.jsx
- src/components/pathway-progress/tests/SubscriptionStatusCard.test.jsx
> feat: update existing tests for program progress

- src/components/app/data/utils.js
- src/components/course/SubsidyRequestButton.jsx
- src/components/dashboard/main-content/course-enrollments/CourseEnrollmentsContextProvider.jsx
https://2u-internal.atlassian.net/browse/ENT-8731
https://onenr.io/0bRmE9knYRy
> fix: handle null bnr config

- src/components/course/data/hooks.jsx
> fix: support expired offers messaging on course page

- src/components/site-header/AvatarDropdown.jsx
> fix: null enterprise customer bug in AvatarDropdown pt2

- src/components/app/data/queries/extractEnterpriseId.js
- src/components/app/data/services/subsidies/subscriptions.js
- src/components/app/routes/data/utils.js
> fix: null enterprise customer bug pt3 in route loaders

- src/components/app/routes/RouteErrorBoundary.jsx
> fix: console.error in RouteErrorBoundary

- src/components/app/data/hooks/usePassLearnerCsodParams.js
- src/components/app/data/services/enterpriseCustomerUser.js
- src/components/app/data/services/enterpriseCustomerUser.test.js
- src/components/course/course-header/CourseHeader.jsx
> fix: pass CSOD learner params upon landing on course page

- src/components/app/data/utils.js
- src/components/app/routes/data/utils.js
> fix: handle missing enterpriseCustomer when traversing linked customers

- src/components/academies/AcademyContentCard.jsx
https://2u-internal.atlassian.net/browse/ENT-8680
> [ENT-8680] fix: handled self-paced courses in toggle button label

- .github/workflows/ci.yml
> chore: bump codecov-action to v4 and supply CODECOV_TOKEN secret

- README.md
Through #1069, we were able to successfully ensure a coverage report is uploaded and available in CodeCov for the most recent merged commit in `master`, rather than the previous stale base commit (11 months old).
This PR (a small README change) will test whether we _always_ need to upload CodeCov coverage reports for `master` directly, or whether we can rely on the coverage reports generated within the PR now that CodeCov's base commit is updated.
This will be especially tested with the "Squash & Merge" to test the behavior when the merged commit SHA is different from the commit SHAs within the PR itself.
> docs: formatting README as test commit for codecov

- src/components/academies/AcademyContentCard.jsx
- src/components/academies/AcademyDetailPage.jsx
- src/components/academies/PathwaysSection.jsx
- src/components/academies/data/hooks.js
- src/components/academies/data/tests/hooks.test.js
- src/components/academies/tests/AcademyDetailPage.test.jsx
- src/components/academies/tests/PathwaysSection.test.jsx
- src/components/app/data/utils.js
- Integrate the new PathwaySection on the Academy detail page
- Handle zero pathway state
- remove the previously rendered pathway content
JIra ->[ ENT-8678](https://2u-internal.atlassian.net/browse/ENT-8678)
> feat: integrate new pathway section in academy detail page

- src/components/academies/styles/Academy.scss
> fix: pathway title opacity issue on prod

- src/components/course/course-header/CourseHeader.jsx
- src/components/course/routes/CourseAbout.jsx
- src/components/course/routes/tests/CourseAbout.test.jsx
> fix: change CSOD params capturing location

- src/components/app/data/hooks/useHasAvailableSubsidiesOrRequests.js
- src/components/app/data/hooks/useHasAvailableSubsidiesOrRequests.test.jsx
- src/components/dashboard/sidebar/SubsidiesSummary.jsx
- src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx
> fix: handle multi-use codes in 2 more spots

- src/components/dashboard/sidebar/LearnerCreditSummaryCard.jsx
> chore: example i18n defineMessages

- package-lock.json
- package.json
- src/components/search/SearchPage.jsx
- src/components/search/tests/utils.test.js
- src/components/search/utils.js
- src/components/skills-quiz-v2/tests/SkillsQuiz.test.jsx
- src/components/skills-quiz/tests/SkillsQuiz.test.jsx
- src/components/skills-quiz/tests/SkillsQuizPage.test.jsx
- src/components/skills-quiz/tests/utils.jsx
__Jira Ticket:__ [ENT-8580](https://2u-internal.atlassian.net/browse/ENT-8580)
This PR adds i18n support for search header component.
> feat: Added i18n for search header component.

- src/components/dashboard/sidebar/tests/LearnerCreditSummaryCard.test.jsx
Updates format for dates in tests to display the correct format to fix flaky tests
> fix: update date format on flaky tests

- src/components/academies/AcademyDetailPage.jsx
- src/components/academies/data/academiesLoader.js
- src/components/academies/data/academiesLoader.test.js
- src/components/app/data/hooks/useAcademyDetails.js
- src/components/app/data/hooks/useAcademyDetails.test.jsx
- src/components/app/data/queries/queries.js
- src/components/app/data/queries/queryKeyFactory.js
- src/components/app/data/services/academies.js
- src/components/app/data/services/academies.test.js
- src/components/search/tests/SearchAcademy.test.jsx
> feat: Added enterprise customer parameter for academies detail api

- src/components/academies/AcademyContentCard.jsx
- src/components/academies/AcademyDetailPage.jsx
- src/components/academies/PathwaysSection.jsx
- src/components/academies/styles/Academy.scss
- src/components/academies/tests/PathwaysSection.test.jsx
> feat: post launch cleanup in academy detail page

- .github/workflows/ci.yml
- package.json
- src/components/budget-expiry-notification/data/hooks/useExpiryThresholds.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/dashboard/main-content/course-enrollments/CourseAssignmentAlert.jsx
- src/components/site-header/data/hooks/useContentDiscoveryNavLink.jsx
> feat: add github check to validate i18n string extraction

- package-lock.json
- package.json
> chore: upgrade @edx/frontend-enterprise-catalog-search to 10.4.0

- package-lock.json
- package.json
> chore: upgrade @edx/frontend-enterprise-catalog-search to 10.5.0

- src/components/search/SearchVideoCard.jsx
- src/components/search/tests/SearchResults.test.jsx
- src/components/search/tests/SearchVideoCard.test.jsx
The duration of the videos was not showing in the right format so created a fix for it.
> fix: duration format on video cards

- src/components/app/data/services/subsidies/subscriptions.js
- src/components/app/data/services/subsidies/subscriptions.test.js
- src/components/app/routes/data/utils.js
> fix: remove computed `isCurrent` property for subscription plans

- src/components/microlearning/data/utils.js
- src/components/microlearning/data/utils.test.js
> [ENT-8962] fix: made changes to cater updated video detail api response

- src/components/microlearning/VideoDetailPage.jsx
> [ENR-8962] fix: hide skills label when skills are not present

- src/components/course/enrollment/components/ToEcomBasketPage.jsx
> fix: ensure codes confirmation modal closes on course about page route

- src/components/dashboard/SubscriptionExpirationModal.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/email-settings/EmailSettingsModal.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/email-settings/tests/EmailSettingsModal.test.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/MarkCompleteModal.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/tests/MarkCompleteModal.test.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/move-to-in-progress-modal/MoveToInProgressModal.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/styles/_EmailSettingsModal.scss
- src/components/dashboard/main-content/course-enrollments/course-cards/styles/index.scss
- src/components/dashboard/main-content/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
- src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js
- src/components/dashboard/tests/DashboardPage.test.jsx
- src/components/integration-warning-modal/IntegrationWarningModal.jsx
- src/styles/index.scss
> chore: Migrate deprecated Paragon components

- src/components/microlearning/BetaBadge.jsx
-> Fix padding around Beta Badge.
> fix: padding around video beta badge

- src/components/microlearning/VideoDetailPage.jsx
- src/components/microlearning/data/utils.js
- src/components/microlearning/data/utils.test.js
- src/components/microlearning/tests/VideoDetailPage.test.jsx
- [NA] Ensure English strings are marked for translation. See [documentation](https://openedx.atlassian.net/wiki/spaces/LOC/pages/3103293538/MFE+Translation+How+To+s#How-to-internationalize-your-React-App) for more details.
> chore: Add video_usage_key to video microlearning segment events

- package-lock.json
- package.json
> chore: updating frontend-enteprise version

- src/components/microlearning/VideoDetailPage.jsx
- src/components/microlearning/VideoFeedbackCard.jsx
- src/components/microlearning/constants.js
- src/components/microlearning/data/utils.js
- src/components/microlearning/styles/VideoDetailPage.scss
- src/components/microlearning/tests/VideoFeedbackCard.test.jsx
**Ticket**
https://2u-internal.atlassian.net/browse/ENT-9485
Added `VideoFeedbackCard` component to track user feedback using segment events
**UI Recordings**
https://github.com/user-attachments/assets/1b2f2f0b-ed58-42f5-8fb0-6b5646c9e40b
https://github.com/user-attachments/assets/4d2c871c-3e81-4eaa-8168-612a93dbbedc
> [ENT-9485]: Add video feedback component to track user feedback via segment events

- src/components/app/data/utils.js
> temp: hide restricted runs before we're ready to show them

- src/components/expired-subscription-modal/index.jsx
- src/components/expired-subscription-modal/tests/ExpiredSubscriptionModal.test.jsx
Resolved these comments suggested by Adam: https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1209/files#r1810670109
> refactor: improve the sanitization for expiration modal

- src/components/app/data/services/subsidies/subscriptions.js
- src/components/app/data/services/subsidies/subscriptions.test.js
- src/components/course/course-header/CourseRunCardStatus.jsx
- src/components/course/course-header/tests/CourseRunCardStatus.test.jsx
- src/components/course/routes/tests/CourseAbout.test.jsx
- src/components/dashboard/DashboardPage.jsx
- src/components/expired-subscription-modal/index.jsx
- src/components/expired-subscription-modal/tests/ExpiredSubscriptionModal.test.jsx
Backend PR: https://github.com/openedx/license-manager/pull/734#pullrequestreview-2408086093
> fix: vsf expired messaging issue

- src/components/microlearning/VideoBanner.jsx
- src/components/microlearning/tests/VideoBanner.test.jsx
**Ticket**: 
https://2u-internal.atlassian.net/browse/ENT-9788
Added a segment event for "Beta Video Banner" page views.
> [ENT-9788] Add segment event for "Beta Video Banner" page views

- src/components/app/data/hooks/useCourseRedemptionEligibility.js
- src/components/app/data/hooks/useCourseRedemptionEligibility.test.jsx
> fix: Redeemed restricted run should remain available

- .github/workflows/update-browserslist-db.yml
Adds a GitHub Action workflow file (`update-browserslist-db.yml`) to enable automatically managing the `browserslist` DB updates on a weekly cron.
See workflow behavior [here](https://github.com/openedx/.github/blob/master/.github/workflows/update-browserslist-db.yml).
> build: update browserslist db on weekly cron

- src/components/app/data/utils.js
> fix: JS exception on initial render for some courses

- renovate.json
Update renovate config to be able to consolidate renovate PRs into a single PR for minor/patch versions.
> chore: update renovate config to consolidate PRs

- src/components/app/data/utils.js
- src/components/app/data/utils.test.js
Fast follow. to this [PR](https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1264) to add relevant tests.
> chore: add tests related to isMarketableExternal

- src/components/app/data/queries/utils.js
- src/components/app/data/services/enterpriseCustomerUser.test.js
- src/components/app/data/services/enterpriseCustomerUser.ts
- src/components/app/data/utils.js
- src/components/app/routes/data/utils.js
- src/components/app/routes/data/utils.test.js
- src/components/app/routes/loaders/rootLoader.ts
> fix: ensure redirects to active EnterpriseCustomerUser, where appropriate; otherwise, show 404

- src/components/app/data/queries/extractEnterpriseCustomer.ts
- src/components/app/routes/data/utils.js
- src/components/app/routes/loaders/rootLoader.ts
> fix: change logError to logInfo

- src/components/app/routes/data/utils.js
- src/components/app/routes/data/utils.test.js
- src/components/app/routes/loaders/tests/rootLoader.test.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/UnenrollModal.jsx
- src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/UnenrollModal.test.jsx
- src/components/dashboard/main-content/course-enrollments/data/hooks.js
- src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx
- src/utils/common.js
https://2u-internal.atlassian.net/browse/ENT-10056
> fix: ensure optimistic cache updates for unenroll and saved for later

- public/index.html
- src/components/app/data/services/bffs.ts
> fix: instantiate enterprise customer as null

- src/components/course/course-header/tests/DeprecatedCourseRunCard.test.jsx
- src/components/course/data/hooks/tests/useUserSubsidyApplicableToCourse.test.jsx
- src/components/course/data/hooks/useUserSubsidyApplicableToCourse.js
> feat: extend useUserSubsidyApplicableToCourse to include can_request response
