openedx/frontend-app-learner-portal-enterprise

package-lock.json, package.json, src/components/dashboard/main-content/DashboardMainContent.jsx, src/components/dashboard/sidebar/DashboardSidebar.jsx
This PR ensures enterprise learner portal homepage doesn't skip heading levels. This relies on this update in `frontend-learner-portal-base` (https://github.com/edx/frontend-learner-portal-base/pull/4), so once that update is published to NPM, will need to version bump the package here as well.
=> fix(a11y): avoid skipping heading levels

gatsby-config.js, gatsby-node.js, package-lock.json, package.json, src/components/dashboard/DashboardPage.jsx, src/components/dashboard/Hero.jsx
Ticket: [ENT-2351](https://openedx.atlassian.net/browse/ENT-2351)
This PR does the following:
* Only fetches for EnterprisePage pages during build
* Retrieves the banner_background_color value, if it exists.
* Adds a custom `Hero` component in place of the common one
Note: This depends on https://github.com/edx/gatsby-source-portal-designer/pull/5.
=> enterprise-specific hero banner

.travis.yml
As part of the upgrade efforts to Node 12, this PR updates this repo from Node 8 to 12. Once this PR lands, we can update the column for this repo with a 🍑 😄- https://openedx.atlassian.net/wiki/spaces/FEDX/pages/931561855/Frontend+Repos.
=> fix: upgrade to Node 12 in .travis.yml

src/components/NotFoundPage/index.jsx, src/components/app/App.jsx, src/components/enterprise-page/EnterprisePage.jsx, src/components/enterprise-page/data/hooks.js
We show the "Not found/404" page for the following cases:
* A user hits the route for an enterprise that doesn't exist
* A user hits the route for an enterprise that does not have the
learner portal enabled
* A user hits the application root "/"
* A user hits the route for an enterprise that does have the learner
portal enabled, but the learner is not linked to that enterprise
[ENT-2655](https://openedx.atlassian.net/browse/ENT-2655)
=> Add NotFoundPage component

src/components/enterprise-page/EnterprisePage.jsx, src/components/layout/Layout.jsx
Adds in a check to make sure the additional user emtadata has been
fetched before rendering the Layout component.
ENT-2652
=> Don't render Layout until metadata is fetched

src/components/course/CourseHeader.jsx, src/components/course/EnrollButton.jsx
Right now, the `CourseService` in `EnrollButton` components is instantiated outside of the component. This means that the authenticated apiClient will not be set as is.
This PR moves that instantiation of `CourseService` inside of the component such that the authenticated apiClient will be present
=> Initialize CourseService inside of component

docs/decisions/0001-record-architecture-decisions.rst, docs/decisions/0002-no-longer-rely-on-portal-designer.rst, docs/decisions/0003-static-builds-to-client-side-react.rst
This PR includes 2 ADRs, documenting why we are:
1. Moving away from the `portal-designer` service
2. No longer using Gatsby (static site generator), and instead transitioning to a standard microfrontend.
It also adds an initial ADR documenting what an ADR is (noticed other repos have this, too).
=> Add 2 ADRs to document decisions related to Gatsby and portal-designer

src/components/course/CourseHeader.jsx, src/components/enterprise-page/EnterprisePage.jsx
The Learner Portal header contains a link to the list of courses. Previously, the link was titled 'Catalog' and it has now been renamed to 'Find a course' (links to B2C page for now).
Updated Title:
Link to associated ticket: https://openedx.atlassian.net/browse/ENT-2989
=> Change 'Catalog' Link

package-lock.json, package.json, src/components/course/CourseRunSelector.jsx, src/components/course/CourseSidebar.jsx, src/components/course/data/utils.jsx, src/components/dashboard/main-content/DashboardMainContent.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/email-settings/EmailSettingsModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/MarkCompleteModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/unarchive-modal/UnarchiveModal.jsx, src/components/enterprise-banner/EnterpriseBanner.jsx, src/components/enterprise-banner/styles/EnterpriseBanner.scss, src/components/enterprise-page/EnterprisePage.jsx, src/components/enterprise-page/data/hooks.js, src/components/enterprise-page/data/tests/customerConfig.test.js, src/components/layout/Layout.jsx, src/components/layout/data/hooks.js, src/utils/common.js
This PR expands on the branding configurations that were already in place, and sets up the code base nicely for future remaining work on [ENT-2892](https://openedx.atlassian.net/browse/ENT-2892).
Instead of using inline styles for each UI element, pulling from `enterpriseConfig` in `AppContext`, we can utilize `react-helmet` to inject `<styles>` into the `<head>`. These styles include CSS overrides for `background-color`, `color`, and `border-color`. For example:
* A button that should have the primary brand background color: `<button className="btn btn-primary brand-btn-primary"`
* A banner that should have a secondary brand background color: `<div className="brand-bg-secondary" />`
This PR also includes logic to create versions of each custom color (i.e., primary, secondary, tertiary) …
=> Add support for customizable colors, including choosing appropriate text color

.eslintrc, package-lock.json, package.json, src/__mocks__/reactResponsive.mock.js, src/components/course/CourseHeader.jsx, src/components/course/CourseMainContent.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/ContinueLearningButton.jsx, src/components/dashboard/main-content/course-enrollments/data/selectors.js, src/components/dashboard/main-content/course-enrollments/data/tests/service.test.js, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx, src/components/dashboard/sidebar/offers/data/tests/actions.test.js, src/components/enterprise-page/data/tests/customerConfig.test.js, src/components/enterprise-user-subsidy/SubscriptionSubsidy.jsx, src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/enterprise-user-subsidy/data/constants.js, src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx, src/components/search/SearchPagination.jsx, src/utils/tests.jsx
* Upgrades `@edx/frontend-build` from v3 to v5 to pull in the latest `babel-jest` version, which supports MutationObserver in tests. Also, removes our local installation of `babel-jest` in favor of the one provided by `@edx/frontend-build`.
** Had to fix linting issues that arose after the upgrade.
* Upgrades `@edx/paragon` to pull in a fix for the `SearchField` component.
* Adds tests for the `UserSubsidy` and `SubscriptionSubsidy` components, which deal with redirecting the user to the Dashboard page when accessing a route without an activated license (assuming the Enterprise has a subscription plan) and rendering the appropriate status alert.
=> tests for subscription subsidy access messaging and redirects

src/components/search/Search.jsx, src/components/search/data/hooks.js, src/components/search/data/tests/hooks.test.js
Adds tests for the search-related custom React hooks uses throughout the Search page.
=> add tests for search-related React hooks

src/components/search/SearchCourseCard.jsx, src/components/search/data/tests/constants.js, src/components/search/tests/SearchCourseCard.test.jsx
Ticket: https://openedx.atlassian.net/browse/ENT-3061
The Algolia search index currently does not contain the partner logo; [this PR](https://github.com/edx/enterprise-catalog/pull/150) addresses this issue by adding it to the course records along with the correct course card image.
This PR updates the code to reflect these changes,
=> display partner logo from algolia

src/components/course/CourseSidebar.jsx, src/utils/common.js, src/utils/tests/common.test.js
This PR fixes the conditional logic to no longer render the "Effort" details if either of the `minEffort` or `maxEffort` fields are `null` in order to address this bug.
=> fix course sidebar null effort bug

src/components/search/SearchCourseCard.jsx
Noticed this JS error on the "Search" UI: 
Turns out it was due to missing data from Algolia (see https://github.com/edx/enterprise-catalog/pull/155 for context / a fix). Even though the linked PR should address this issue, this particular PR makes the logic a bit more resilient to not error again if/when the `partners` field is missing from an Algolia object.
=> prevent JS error on Search page

README.md, src/components/course/EnrollButton.jsx, src/components/enterprise-user-subsidy/UserSubsidy.jsx
Link to the Data Sharing Consent (DSC) view for learners enrolling with
a license.
Note that this commit assumes that the user has access to the content
through their subscription and is using a license to enroll. The logic
around calling the license subsidy view will be implemented by:
https://openedx.atlassian.net/browse/ENT-2685. Additionally, this
enrollment url will need to be updated in the future to support codes
and offers.
=> Update EnrollButton to link to DSC for licenses 

src/components/dashboard/main-content/course-enrollments/CourseSection.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/CompletedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/MarkCompleteModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/data/service.js, src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/tests/MarkCompleteModal.test.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/move-to-in-progress-modal/MoveToInProgressModal.jsx, src/components/dashboard/main-content/course-enrollments/data/actions.js, src/components/dashboard/main-content/course-enrollments/data/reducer.js, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.enzyme.test.jsx, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx, src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js
For clarity. Gets us ready to finalize the column name change on the backend.
=> Change marked done to saved for later

src/components/course/CourseAssociatedPrograms.jsx, src/components/course/CourseHeader.jsx, src/components/course/CourseSidebar.jsx, src/components/course/CreatedBy.jsx, src/components/course/data/hooks.js
Right now, there are some links that are double-prefixed with the marketing site's hostname (e.g., `https://stage.edx.org/https://stage.edx.org/some-link`). This PR fixes that to use the full absolute URL we get from the API instead of prefixing it with a hostname from configuration.
=> fix external links to prospectus from Course page

src/components/app/App.jsx, src/components/enterprise-user-subsidy/SubscriptionSubsidy.jsx, src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/license-activation/LicenseActivation.jsx, src/components/license-activation/LicenseActivationPage.jsx, src/components/license-activation/data/hooks.js, src/components/license-activation/data/service.js, src/components/license-activation/index.js, src/components/license-activation/tests/LicenseActivation.test.jsx, src/components/login-redirect/LoginRedirect.jsx, src/components/login-redirect/index.js, src/components/login-redirect/tests/LoginRedirect.test.jsx, src/index.jsx, src/utils/hooks.jsx
Also adds a login redirect component that redirects any unauthenticated
learners to our new (yet to be implemented) proxy login view in edx
enterprise. The login redirect component is currently not used anywhere
but will be enabled in a follow up PR once the proxy login view is
implemented by https://openedx.atlassian.net/browse/ENT-3141.
ENT-3097
=> Add license activation page

src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/MarkCompleteModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/tests/MarkCompleteModal.test.jsx, src/components/dashboard/main-content/course-enrollments/data/constants.js, src/components/dashboard/main-content/course-enrollments/data/selectors.js, src/components/dashboard/main-content/course-enrollments/data/tests/selectors.test.js, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx, src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js
Ensures that we're consistent in what we call things, makes tests less brittle when names change.
=> Remove 'magic strings' from the code

src/components/course/CourseSidebar.jsx, src/components/course/CourseSidebarPrice.jsx, src/components/course/data/constants.js, src/components/course/data/hooks.js, src/components/course/data/service.js, src/components/course/data/utils.jsx, src/components/enterprise-page/data/hooks.js, src/components/enterprise-user-subsidy/SubscriptionSubsidy.jsx, src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx, src/components/license-activation/LicenseActivation.jsx, src/components/license-activation/tests/LicenseActivation.test.jsx, src/utils/common.js
This PR updates the course sidebar to include the pacing type of the course (self or instructor paced), and also adds logic to show the correct price as well.
While our current use case is to only support licenses, support for codes/offers will be coming soon in the LP. So, I tried to ensure the price messaging has a decent starting point when that work gets picked up.
Takes into account whether the EnterpriseCustomer has `hide_course_original_price` enabled.
This PR also adds date validation when retrieving whether the Enterprise Customer has an active subscription. Before, the validation was only around the `is_active` attribute. Now, it factors in whether today's date is between the subscription plan's start and expiration dates.
_**Note: Course page Tests coming in follow-up PR.**_ …
=> add pacing type, discounted price in sidebar, date validation for subscription plan

src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
This PR addresses an issue where the page content flashes prior to loading the subscription plan/license subsidy.
1. With an active subscription plan and an unassigned license, browse to the LP search page.
2. You should **NOT** see a flash of the "Search" page before getting redirected to the home page. Instead, you _should_ see a loading spinner below the branded enterprise banner.
=> fix page load before subsidy check resolves

src/components/course/EnrollButton.jsx
After a recent change, there was a certain scenario that would render "EnrollEnroll" in the button label. This PR introduces a fix for this logic to properly render just "Enroll".
[Example](https://enterprise.stage.edx.org/pied-piper/course/edx+jpm_cred103)
The `useMemo` hook for generating the "Enroll" button's `enrollmentUrl` returns `null` when the user's subscription license is not yet loaded. This is due to missing items in the dependency list for the `useMemo` hook, which will now properly re-generate the `enrollmentUrl` when the subscription license has loaded in, or any of the other dependent variables are changed.
=> fix double enroll and missing hook dependencies

src/components/search/SearchCourseCard.jsx
This PR fixes the issue where a white box is displayed on course cards when there is no partner logo to show, as in the case described by ENT-3266.
=> hide partner logo wrapper if there's no logo to display

src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/CourseSection.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/CompletedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/SavedForLaterCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/data/constants.js, src/components/dashboard/main-content/course-enrollments/data/selectors.js, src/components/dashboard/main-content/course-enrollments/data/tests/selectors.test.js, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.enzyme.test.jsx, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx, src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js, src/components/enterprise-user-subsidy/UserSubsidy.jsx
Ticket: https://openedx.atlassian.net/browse/ENT-2891
This PR refactors the logic around the "saved for later" course run status to reflect the changes in this related edx-enterprise PR: https://github.com/edx/edx-enterprise/pull/914/.
Before, "Saved for later" courses were returning as "completed" and logic existed to change the course run status from "completed" to "saved for later" based on the `saved_for_later` flag on the enterprise course enrollment. However, in the linked edx-enterprise PR, a new `saved_for_later` status is introduced that can be used instead of the logic within the UI.
Additionally, this PR does some UX clean up to prevent moving a "revoked" course enrollment back to in-progress (hides the "Move to In Progress" option in the gear), and updates the …
=> refactor for new saved_for_later course status and is_revoked flag

src/components/dashboard/sidebar/DashboardSidebar.jsx, src/components/enterprise-banner/EnterpriseBanner.jsx, src/components/enterprise-banner/OffersAlert.jsx, src/components/enterprise-banner/OffersAlert.test.jsx
Alert is for 100% enterprise offers only
Ensures that the API call is only made once on pages where the sidebar is present
Miro Board: https://miro.com/app/board/o9J_kp-7aks=/?moveToWidget=3074457348784458838&cot=13
*Note* I made the decision to include this on the learner portal dashboard because the sidebar that shows the coupon count currently disappears on mobile.
Instructions for creating offers: https://github.com/edx/ecommerce/pull/3082
=> Add alert for enterprise offers

src/components/dashboard/sidebar/DashboardSidebar.jsx
The 'no coupons' card could create confusion for subscription users.
*Testing*
When a user with 100% coupons logs in, they should see a sideboard card with the number of coupons
When a user with no 100% coupons logs in, no card should appear. (They may see a spinner briefly.)
=> Remove sidebar card if user has no coupons

src/components/course/CourseRunSelector.jsx
The course run selector's "more dates" button is currently using the `.btn-brand-primary` class when it should just remain as `.btn-link`:
=> remove .btn-brand-primary class from course run selector

src/components/course/DeprecatedEnrollButton.jsx, src/components/course/EnrollButton.jsx
Now that the paragon `Button` component accepts the `variant` prop, the `btn-success` style class shouldn't be passed as part of `className` to any `Button` with `variant="success"`. 
Since `btn-success` is no longer part of `enrollLinkClass` it must be passed as an additional argument to `classNames()` when `enrollLinkClass` is used for anchor tags and `Link` components.
=> (EnrollButton) fixing redundant use of button success style class

src/components/course/data/constants.js, src/components/course/data/utils.jsx, src/components/search/styles/_MobileSearchFilters.scss, src/index.scss
Viewing a course on stage that only has a "honor" track, a JS error was being thrown due to not considering honor seats when choosing which seat the user should enroll in for offer (code) enrollments. Now, it factors in honor seats and avoids the JS error from occuring.
After some recent renaming of SCSS files, we lost our import of the MobileSearchFilters.scss file, so the mobile search filter styles weren't present.
<table>
<thead>
<tr>
<th><i><u>Before</u></i></th>
<th><i><u>After</u></i></th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://user-images.githubusercontent.com/2828721/97438681-827cb180-18fb-11eb-82c8-b60ccfa5f77b.png" width="300" />
</td>
<td><img src="https://user-images.githubusercontent.com/2828721/97438577-5c571180-18fb-11eb-8a34-fa9d3a4aa3eb.png" width="300" /> …
=>  fix mobile search filters styles and prevent JS error

src/components/search/FacetListFreeAll.jsx, src/components/search/SearchFilters.jsx, src/components/search/tests/FacetListFreeAll.test.jsx, src/components/search/tests/FacetListRefinement.test.jsx
Adding the pagination reset makes the two filter components similar enough that I kiiiind of want to refactor into one component again, but since this ticket is way overdue, I figure we can do that the next time we touch the filters.
This also makes small changes to the filter labels.
=> Fix pagination and filter labels

.github/workflows/ci.yml, .travis.yml
This moves us off of travis and uses github actions instead. You can see the check on this PR below.
SRE will need to remove travis from this repo entirely before this can be merged
Note: this doesn't address the numerous `console.error` that are **not** failing the build but probably should be, but this is the same as it was for travis.
=> Creates new github action to replace travis file

src/components/course/EnrollButton.jsx, src/components/course/data/hooks.js
JIRA: https://openedx.atlassian.net/browse/ENT-3715
Fixes two issues:
1. when subscription is not valid for course (as checked by userSubsidy), modal was not shown to warn usre before taking to basket page. Now it does.
2. when subscription is not valid and user tries to enroll with codes (whether or not they have any left), the feature switch did not disable the Enroll button, now it does
The bug fix is entirely in EnrollButton.jsx. The hooks file change is meant for upcoming refactor and has no impact right now but will be used once refactoring starts.
Tested with two courses:
A: Course 1 : is in subscription catalog: got no modal and got taken to data consent page
B: Course 2: is not in subscription catalog but is in a non-subscription catalog: got a modal and got taken to basket page …
=> bug: ENT-3715 enroll button cta bug fix for codes

src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/data/service.js, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
Frontend ticket to leverage new license-manager endpoint for fetching Learner License data created in https://github.com/edx/frontend-app-learner-portal-enterprise/pull/176
=> feat: use new license manager endpoint to fetch license data

src/components/enterprise-user-subsidy/data/service.js
This PR removes the frontend caching on the `learner-licenses` API request.
Previously, if a learner's license is pending on initial page visit, followed by the learner activating their license via the activation email, we had stale data in the client's cache about the user's pending license when we really want to fetch the latest license data instead.
=> fix: remove frontend caching on learner-licenses endpoint

src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/offers/data/actions.js, src/components/enterprise-user-subsidy/offers/data/service.js, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
Added missing query param. @raq929 and @adamstankiewicz I welcome suggestions on how to test/regression test this because it's not testable by frontend unit test and also the backend is fine. This seems like an e2e candidate perhaps? 
Addresses ENT-3950 and ENT-3951
=> ENT-3950 and ENT-3951 Bug fix: passing in missing filter for user offers by uuid.

src/components/course/Course.jsx, src/components/course/CourseContextProvider.jsx, src/components/course/CourseSidebarPrice.jsx, src/components/course/EnrollButton.jsx, src/components/course/data/constants.js, src/components/course/data/hooks.js, src/components/course/data/service.js, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/utils.jsx, src/components/course/tests/CourseSidebarPrice.test.jsx, src/components/course/tests/EnrollButton.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-3632
this mainly changes how the price display look for non subscription  (offer) cases, adds test cases etc.
pre-merge checklist:
Added test cases for:
feature flag off (should show original price)
feature flag on (should hide original price)
And test cases both scenarios:
- With an offer code that applies to the course:
- With a subscription that includes the course
- With no offers that apply to the course and no subscription
Screenshots:
only shows message, no price (since it would be $0)
=> Show offer discounted price if subscription does not apply, ENT-3632

src/components/enterprise-user-subsidy/offers/data/service.js
[Jira Ticket](https://openedx.atlassian.net/browse/ENT-3952)
Situation: when a user spends their coupon on a course and then are assigned a new code and refresh the page, they do not see the new code assigned to them.
Problem: default caching expiries meant that the request for user coupons was stale for 5 minutes. So if a user is assigned a new code after using another one, they wouldn't rerequest their number of codes until the 5 minutes is/was up.
Solution: Remove the cache
=> Changing the cache time for code requests to 30 seconds

src/components/course/data/hooks.js, src/components/course/tests/CourseSidebarPrice.test.jsx
really that the backend response contains 
```
usage_type: Percentage
```
while the code checks for 'percentage', so making the check case-insensitive is probably the best idea.
=> bug: ENT-3997 make discountType check case-safe

src/components/course/data/hooks.js, src/components/course/enrollment/constants.js, src/components/course/enrollment/hooks.js, src/components/course/enrollment/tests/hooks.test.jsx
https://openedx.atlassian.net/browse/ENT-3889
Just two hook functions that handle enrollment data, and subsidy data respectively. These outputs will be used in the main logic flow that is coming up in the next PR. Ref: https://openedx.atlassian.net/wiki/spaces/SOL/pages/2178875970/Enroll+Button+logic+for+Enterprise+Learner+Portal
No ui component work here, second PR will handle that and cleaning out the use of the old component as well.
Also incorporates hooks related feedback I already got from @adamstankiewicz on this [older, bulkier PR ](https://github.com/edx/frontend-app-learner-portal-enterprise/pull/171/files)(not going to submit it, other than to ensure I take care of any feedback from there)
I am pulling out enrollment url calculation from the user subsidy hook since it's …
=> Refactor enroll button part I: hook functions ENT-3889

src/components/enterprise-page/EnterprisePage.jsx, src/components/enterprise-page/data/hooks.js, src/components/enterprise-page/data/tests/customerConfig.test.js
When the enterprise config came back as null the spinner on the page would keep spinning, this change makes the page display a 404 instead.
=> set subscriptionPlan to null if the enterprise config comes back as null

src/components/course/EnrollButton.jsx, src/components/course/data/hooks.js, src/components/course/data/tests/hooks.test.jsx, src/components/course/enrollment/hooks.js, src/components/course/enrollment/tests/hooks.test.jsx, src/components/course/tests/EnrollButton.test.jsx
__JIRA__: ENT-4185
Fixes the bug as reported during bug bash when no learner subscription is active, subscription plan is active for enterprise, and there exists at least one offer
when there are offers, but no active license, the useCourseEnrollmentUrl fails, due to absence of the offers parameter. It does not have a default value right now so it fails when checking `offers.length`
This PR includes:
* adds a default empty array as a default value so absence is treated as if there are no offers, just for defensive coding
* passes the offers param from useSubsidyData hook into the above hook for proper operation of the logic
* tests that the component renders correctly without an error in the absence of license subsidy, but presence of offers in the context
Reproduced bug using ticket …
=> ENT-4185: pass offers to useCourseEnrollmentUrl hook, tests

src/components/course/data/hooks.js
To support ticket ENT-4024, in which we want the ability to override the explanatory text that appears in the sidebar with a query option. Note: requires edx-enterprise change that accepts this parameter or nothing will happen. Screenshot attached. 
Requires: https://github.com/edx/edx-enterprise/pull/1161
=> Pass in override to blank out sidebar text in our flow.

src/components/NotFoundPage/index.jsx, src/components/app/App.jsx, src/components/course/CourseHeader.jsx, src/components/dashboard/Dashboard.jsx, src/components/enterprise-banner/EnterpriseBanner.jsx, src/components/enterprise-customer-redirect/EnterpriseCustomerRedirect.jsx, src/components/enterprise-customer-redirect/data/hooks.js, src/components/enterprise-customer-redirect/data/service.js, src/components/enterprise-customer-redirect/index.js, src/components/enterprise-customer-redirect/tests/EnterpriseCustomerRedirect.test.jsx, src/components/enterprise-page/EnterprisePage.jsx, src/components/enterprise-page/data/hooks.js, src/components/enterprise-page/data/service.js, src/components/enterprise-page/data/tests/customerConfig.test.js, src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/license-activation/LicenseActivation.jsx, src/components/search/SearchCourseCard.jsx, src/components/search/SearchResults.jsx, src/components/search/styles/_SearchCourseCard.scss, src/components/search/tests/SearchCourseCard.test.jsx, src/components/site-header/AvatarDropdown.jsx, src/components/site-header/SiteHeader.jsx, src/index.jsx
Ticket: [ENT-3349](https://openedx.atlassian.net/browse/ENT-3349)
Creates a new route to handle when learners go to https://enterprise.edx.org. Currently, we simply show a 404 not found but is confusing as some learners are going to this route, expecting to see their learner portal.
Additionally, by having a root route that intelligently redirects learners, ECS and other internal stakeholders will be able to provide a generic link to the Learner Portal without considering what slug the associated enterprise has.
This PR handles visits to this route by determining which enterprise customers a learner is linked to, and proceeding with the following checks:
1. If learner is linked to 0 customers, continue to show 404 not found.
1. If learner is linked to 1 customer, redirect to that …
=> feat: create root route that redirects to appropriate slug, if any

src/components/dashboard/Dashboard.jsx, src/components/dashboard/SubscriptionExpirationModal.jsx, src/components/dashboard/sidebar/DashboardSidebar.jsx, src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx, src/components/dashboard/tests/Dashboard.test.jsx, src/components/enterprise-page/EnterprisePage.jsx, src/components/enterprise-page/data/hooks.js, src/components/enterprise-page/data/service.js, src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/enterprise-user-subsidy/UserSubsidyAlerts.jsx, src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/data/service.js, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx, src/components/search/Search.jsx
Noticed this JS error on stage, potentially related to some recent updates:
This PR prevents the error from occurring and also moves `subscriptionPlan` from `AppContext` into `UserSubsidyContext`, and updated all the places where we previously expected `subscriptionPlan` in `AppContext`. The rationale for this change is to colocate where all subscriptions data (both subscription plan and subscription licenses) are fetched/stored.
=> fix: resolve JS error when license loads before subs plan + move where subscriptionPlan lives in context

src/components/course/enrollment/EnrollAction.jsx, src/components/course/enrollment/components/ToEcomBasketPage.jsx, src/components/course/enrollment/components/ToVoucherRedeemPage.jsx, src/components/course/enrollment/tests/EnrollAction.test.jsx
Use cases broken were: to_ecom_basket, and to_voucher_redeem_page
__Why bug was inserted?__
these were getting enrollmentUrl from useSubsidyDataForCourse() instead of the passed in enrollmentUrl prop which has been resolved by prior business logic in a hook
Was introduced in https://github.com/edx/frontend-app-learner-portal-enterprise/pull/198/files
__Why not detected?__
There was no automated test capturing the rendered url inside the modals in these cases.
Fix includes:
* fix
* test cases that are confirmed/verified to fail when I re introduce the code bug
=> ENT-4217: enrollmentUrl was sourced from incorrect place in two EnrollAction use cases

package-lock.json, package.json, src/components/search/Search.jsx, src/components/search/data/hooks.js, src/components/search/data/tests/hooks.test.jsx
This function is only relevant to this repo
Uses the user's license instead of the subscription plan to determine if user has a license
=> Move useDefaultSearchFilters back to learner portal

package.json, src/utils/common.js, src/utils/tests/common.test.js
While doing manual end to end testing for Learner Portal with Codes, we found the prices were not showing correctly, particularly in the case of enterprises that had both offers and subscriptions.
The expected behaviour: A user in an enterprise - that has a subscription - with a coupon/code/offer for a non-subscription catalog should see the original price crossed out (or not present in the case of the hide original price flag) and see "Sponsored by <Enterprise Name>".
The actual behaviour: They saw the original price as though they had no offer.
Through a lot of debugging, it was realized this behaviour was inconsistent and we figured out there was a race condition somewhere, ultimately leading us back to this `hasValidStartExpirationDates` function. In trying to debug this, we also …
=> bug: fix race condition in hasValidStartExpirationDates

src/components/course/CoursePage.jsx, src/components/enterprise-user-subsidy/OffersAlert.jsx, src/components/enterprise-user-subsidy/UserSubsidyAlerts.jsx, src/components/enterprise-user-subsidy/tests/OffersAlert.test.jsx, src/components/search/SearchPage.jsx
While testing Learner Portal with Codes, we noticed the Learner Dashboard showed the voucher banner. This is redundant since we already have the cards on the right that show your subscription and codes.
- OffersAlert component moved out from under UserSubsidyAlerts.
- Offer context called directly from OffersAlert.
- Updated the language from `course redemption vouchers` to `enrollment codes`
The banner correctly missing from the dashboard:
The updated language:
=> Remove unnecessary banner from dashboard.

src/components/course/data/hooks.js, src/components/course/enrollment/common.jsx, src/components/course/enrollment/components/DisabledEnroll.jsx, src/components/course/enrollment/components/ToCoursewarePage.jsx, src/components/course/enrollment/components/ToDataSharingConsent.jsx, src/components/course/enrollment/components/ToVoucherRedeemPage.jsx, src/components/course/enrollment/components/ViewOnDashboard.jsx, src/components/enterprise-user-subsidy/OffersAlert.jsx
- Fix for ENT-4276 (Note: requires sister ecommerce PR as well to redirect data sharing parameters)
- Desire to modify feature to apply to subscription redemptions when called from within learner portal as well as when codes are redeemed.
- Fixed bug where left sidebar override parameter got lost when ecommerce reconstructed the Data Sharing Consent url and performed a redirect.
- Small other nits: a typo in the 'you have x codes' banner
- Fixed PropTypes warning (after doing investigation into correct PropType)
-
=> ENT-4276 lp codes bugfixes

src/components/course/CourseHeader.jsx, src/components/course/CourseSkills.jsx, src/components/course/data/constants.js, src/components/course/styles/_CourseSkills.scss, src/components/course/tests/CourseHeader.test.jsx, src/components/course/tests/CourseSkills.test.jsx, src/index.scss
JIRA: https://openedx.atlassian.net/browse/ENT-4105
**Changes made:**
- Added Skills in Course Header
- Moved Partners logo to top and set its heigh to 44px as suggested in [Figma](https://www.figma.com/file/vN7K50kRSbxoby1nMJpppD/Skills-filter?node-id=103%3A2792)
- Changed margins as suggested [here](https://www.figma.com/file/vN7K50kRSbxoby1nMJpppD/Skills-filter?node-id=103%3A2792) 
**Screen Recording:** 
https://user-images.githubusercontent.com/55431213/111431312-74e68d80-871d-11eb-94cf-f90bfcd69f7d.mov
=> ENT-4105: Dispaly skills tags in Course Header

src/components/course/CourseHeader.jsx, src/components/course/CourseSkills.jsx
=> ENT-4105: small UX improvements

package-lock.json, package.json
Devs locally are getting errors and having MFEs actually just crash due to the webpack hot reload dev server. Frontend-build was updated to include a necessary config flag to fix this. This PR just updates to the latest frontend-build to get that change.
=> fix: update frontend-build to fix sockjs errors

src/components/course/CourseAssociatedPrograms.jsx, src/components/course/CourseHeader.jsx, src/components/course/CourseMainContent.jsx, src/components/course/CourseSidebar.jsx, src/components/course/CreatedBy.jsx, src/components/course/tests/CourseHeader.test.jsx
[ENT-4364](https://openedx.atlassian.net/browse/ENT-4364)
Updates all course page links leading to B2C URLs to open in new tab. These include:
* Course page school link
* Course page instructor link
* Course page sidebar subject link
* Course page sidebar institution link
* Course page sidebar program link
The course page breadcrumbs have been refactored to exclude the course subject and include the course title as an active label.
Visit the course page and test all links mentioned above. Observe described changes in breadcrumbs.
=> refactor: opens all B2C course page links in a new tab

package-lock.json, package.json, src/components/search/Search.jsx
- upgrades frontend-enterprise to 5.4.2
- adds `containerSize` prop to `SearchHeader`
This PR is basically just a version bump for frontend-enterprise:
- 5.4.1 adds a `containerSize` prop to `SearchHeader` with default value of `null`
- 5.4.2 fixes an issue with the functionality of the `SearchHeader` submit and clear actions
[ENT-4382](https://openedx.atlassian.net/browse/ENT-4382)
=> fix: upgrade frontend-enterprise to fix search clear button

src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/data/service.js, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
**NOTE**: https://github.com/edx/license-manager/pull/211 has to be merged first.
We previously obtained license and subscriptionPlan information from 2 separate API calls. This meant we weren't ensuring the subscriptionPlan foreign key on the license object actually matched the subscriptionPlan we were returning. To make matters worse, when there are multiple subscription Plans we just returned a random one.
We now associate license to subscription in a one to one relationship by pulling the subscription plan information associated with the license in the backend API call.
Thus, this mostly just removes the subscription plan fetch call and everything upstream(down? idk, everything defined in the `useEnterpriseCustomerSubscriptionPlan` method was only used in that method and thus can also …
=> fix: remove subscription plan API call; use new license subscriptionPlan attribute

src/components/course/CourseHeader.jsx
Previously, if a course had no listed skills, the page would error. This prevents us from trying to access the length of an array that does not exist.
=> fix: page does not fail if course has no skills

package-lock.json, package.json, src/index.jsx
Treat Axios errors and third-party script errors as NewRelic page actions instead of JS errors, so they don't affect our alerting.
See https://openedx.atlassian.net/wiki/spaces/PT/pages/2796617772/MFE+JS+Error+and+Info+Logging#Summary for more details on this works.
=> fix: reduce noisy JS errors

package-lock.json, package.json
Upgrades `@edx/frontend-build` to v6.0.0 to pull in an upgrade to a NewRelic plugin such that we should now get the "Core web vitals" metrics for this MFE.
=> build: upgrade frontend-build to v6

package-lock.json, package.json, src/components/course/Course.jsx, src/components/course/CourseHeader.jsx, src/components/course/EnrollModal.jsx, src/components/course/data/hooks.js, src/components/course/enrollment/components/ToCoursewarePage.jsx, src/components/course/enrollment/components/ToDataSharingConsent.jsx, src/components/course/enrollment/components/ViewOnDashboard.jsx, src/components/course/tests/EnrollModal.test.jsx, src/components/dashboard/Dashboard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/email-settings/EmailSettingsModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/mark-complete-modal/ModalError.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/move-to-in-progress-modal/ModalError.jsx, src/components/enterprise-page/EnterprisePage.jsx, src/components/enterprise-page/EnterprisePage.test.jsx, src/components/license-activation/LicenseActivation.jsx, src/components/search/Search.jsx, src/components/search/SearchCourseCard.jsx, src/utils/hooks.jsx, src/utils/tests.jsx
ENT-4549
This PR primarily dispatches Segment events on course search result clicks and enroll button clicks to track Algolia click-thru and conversion rates along with other insights.
I enabled the "Algolia Insights" destination in Segment for the learner portal source and configured it to rename the above custom event names to the Segment spec so they get picked up by Algolia analytics:
* `Product Clicked` (click-thru rate)
* `Order Completed` (conversions)
The following Segment events are added:
* `edx.ui.enterprise.learner_portal.search.card.clicked` (Product Clicked)
* `edx.ui.enterprise.learner_portal.course.enroll_button.to_courseware.clicked` (Order Completed)
* `edx.ui.enterprise.learner_portal.course.enroll_button.to_dsc.clicked` (Order Completed)
* …
=> fix: add segment and Algolia events for search CTR and conversions

src/components/skills-quiz/SkillsQuiz.jsx, src/components/skills-quiz/SkillsQuizStepper.jsx, src/components/skills-quiz/__mocks__/react-instantsearch-dom.jsx, src/components/skills-quiz/constants.js, src/components/skills-quiz/tests/SearchFilters.test.jsx, src/components/skills-quiz/tests/SkillsQuiz.test.jsx, src/components/skills-quiz/tests/utils.jsx
[ENT4670](https://openedx.atlassian.net/browse/ENT-4670): Dropdown for selecting relevant skills is added in this PR. All the skills selected are added in URL as query param and can be accessed through Context. Styling of the component is not covered in this PR.
=> feature: Typeahead algolia skills search dropdown

src/components/dashboard/Dashboard.jsx, src/components/dashboard/tests/Dashboard.test.jsx, src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/enterprise-user-subsidy/data/hooks.jsx, src/components/enterprise-user-subsidy/data/service.js, src/components/enterprise-user-subsidy/tests/UserSubsidy.test.jsx
ENT-4544. Use the CustomerAgreement API to determine if we should show or hide expiration modals. This is designed to be used with Trials, where the fact that a Trial will expire in 14 days isn't something that needs giant modal warnings about during the experience.
=> feat((learner_portal)): :sparkles: Use config to hide expiration modals

package-lock.json, package.json
Going from `@edx/frontend-build@7` to `@edx/frontend-build@8` has no breaking changes for this repo as we are using React 16.14.0 which meets the new peer dependency in v8.
=> build: upgrade to frontend-build@8.0.2 to fix new relic source maps

src/components/skills-quiz/SearchJobDropdown.jsx, src/components/skills-quiz/SkillsQuizStepper.jsx
If it is desired to not refine the data from Algolia on the basis of user selection but only mark the checkboxes and save his selections.
https://openedx.atlassian.net/browse/ENT-4843
https://openedx.atlassian.net/browse/ENT-4844
=> (feat) ENT4816- Add jobs dropdown

package-lock.json, package.json
Upgrades to `@edx/frontend-build` v8.0.4 to resolve the following error when starting the Webpack Dev Server:
> [webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
=> build: upgrade to frontend-build v8.0.4

src/components/enterprise-user-subsidy/offers/data/actions.js, src/components/enterprise-user-subsidy/offers/data/tests/actions.test.js, src/components/enterprise-user-subsidy/offers/data/tests/utils.test.js, src/components/enterprise-user-subsidy/offers/data/utils.jsx
In order to make the UI less confusing for users we wanted to incorporate multi-use codes into the count returned in the learner portal.
Previously, we were using the count which is the total number of offers (aka unique codes). This means a multi-use code which may have many redemptions associated only shows as a count of 1.
This PR swaps `offerCount` from this count variable (which comes from what exactly I don't know. Seems like a default/standard part of the response that just counts objects (it's on the same level as nextPage, etc.)) to a calculation based on the actual `redemptions_remaining` attribute that is on each coupon.
I updated an existing test that utilized counts and also added a test for the new utility calculation redemptions remaining.
- These show the result of 2 …
=> Fix: Update Enrollment Codes count to use redemptions_remaining instead of count from backend.

src/index.jsx
We had previously ignored specific errors to reduce JS error noise in the Enterprise Learner Portal. The previously-ignored errors were causing lots of erroneous error spikes due to lower traffic at the time. But with a higher traffic volume now, these errors likely will be useful again 🤞 
Since we're investigating a JS error related to an Axios error, let's remove the `IGNORED_ERROR_REGEX` such that we should get more visibility into how often these 401 errors on course about pages are occurring.
=> fix: remove ignored errors regex

README.md, src/components/dashboard/SubscriptionExpirationModal.jsx, src/components/dashboard/tests/Dashboard.test.jsx, src/config/constants.js
[ENT-4628](https://openedx.atlassian.net/browse/ENT-4628)
The 30 day expiration modal was not being shown in the learner portal previously. This change adds it.
**Testing instructions**
1. Open the learner portal with a subscription expiring in <= 60 days.
2. Check that an expiration modal is shown
3. Close the modal and verify that a cookie has been set
4. Refresh the page and verify that the modal does not show up again
5. Update the subscription expiry date to be <= 30 days
6. Repeat steps 2-4
=> fix: add 30 day expiration modal

src/components/app/AuthenticatedUserSubsidyPage.jsx, src/components/app/AuthenticatedUserSubsidyPage.test.jsx, src/components/dashboard/Dashboard.jsx, src/components/enterprise-user-subsidy/ActivateLicenseAlert.jsx, src/components/enterprise-user-subsidy/index.js, src/components/enterprise-user-subsidy/tests/ActivateLicenseAlert.test.jsx
Back in June, we unintentionally removed an alert that informed the learner they had an assigned license that needed to be activated. This PR adds it back in, with some improvements. Before, it told the learner to go click the link in their activation email. This banner, however, includes a CTA button with the link itself (i.e., no need to refer to their email).
The alert will show on the Dashboard, Search, or Course pages to handle all the possible entry points to the app for the learner (e.g., SSO users land on course page directly).
Also fixes a bug where the license activation alert would persist even after a full page refresh.
**Screenshots:**
**Note: Copy is being reviewed by UX.**
=> feat: add alert to inform learner to activate license

src/components/app/AuthenticatedPage.jsx, src/components/app/LoginRefresh.jsx, src/components/app/LoginRefresh.test.jsx, src/components/course/CoursePage.jsx
https://openedx.atlassian.net/browse/ENT-4885
Wrapping course page in authenticated page route. It seems like we have redirect login logic in both AuthenticatedPageRoute and AuthenticatedPage and there might opportunity for clean up.
=> fix: add login refresh component 

src/components/enterprise-user-subsidy/ActivateLicenseAlert.jsx, src/components/enterprise-user-subsidy/tests/ActivateLicenseAlert.test.jsx
The alert that informs the learner they must activate their license currently includes an "Activate now" CTA that depends on the `activation_key` associated with the assigned license. However, it turns out `activation_key` is only available in the license serializer in `license-manager` in development and stage environment, but not production.
This caused learners who clicked the "Activate now" CTA on production to have an error during license activation since we were passing `undefined` to the license activation API endpoint.
As a quick fix, this PR updates the copy and removes the "Activate now" CTA to avoid these errors, and encourage the learner to click the activation link sent to their email.
=> fix: remove activation CTA from banner

package.json, src/components/course/CourseEnrollmentFailedAlert.jsx, src/components/course/CourseHeader.jsx, src/components/course/data/constants.js, src/components/course/data/hooks.jsx, src/components/course/tests/CourseHeader.test.jsx
[ENT-4564](https://openedx.atlassian.net/browse/ENT-4564)
Currently, if enrollment via data sharing consent (DSC) fails for any reason, an alert banner with the same copy is used, regardless of the reason for the failure.
This PR takes in an additional query parameter `failure_reason` to determine which alert messaging to use depending on why the enrollment failed. This is primarily to help distinguish the following failure reason messaging:
1. Denying DSC
1. Accepting DSC but verification deadline has passed
Note, the alert messaging for the verification deadline failure case was run by UX and deemed "good enough" while they check on any similar messaging on the B2C side of things. We may need to come back and update the copy for this alert if/when the similar messaging …
=> feat: handle multiple course enrollment failure reasons

src/components/course/CourseEnrollmentFailedAlert.jsx, src/components/course/tests/CourseHeader.test.jsx
In testing ENT-4564 on stage, I noticed that the only `failure_reason` that gets added to the `failure_url` is when the verified mode is unavailable. Ideally, we'd have a failure reason for `dsc_denied` as well so we can have messaging specific to that failure mode ([added via this PR](https://github.com/edx/edx-enterprise/pull/1349)). For broad failures, the `failure_reason` is nonexistent, so no error alert gets shown at all.
This PR adds a default error message to catch when an enrollment is failed, but has no explicit reason specified so an alert still appears to inform the learner that something went wrong.
Another PR will be written to add `dsc_denied` as a failure mode on the edx-enterprise side of things.
=> fix: render enrollment failed alert even with no failure reason

src/components/skills-quiz/CurrentJobDropdown.jsx, src/components/skills-quiz/JobCardComponent.jsx, src/components/skills-quiz/SearchCourseCard.jsx, src/components/skills-quiz/SearchCurrentJobCard.jsx, src/components/skills-quiz/SelectJobCard.jsx, src/components/skills-quiz/SkillsQuizStepper.jsx, src/components/skills-quiz/data/hooks.js
[ENT-4932](https://openedx.atlassian.net/browse/ENT-4932): 
Functionality added in this PR:
1- Learners have to select search job or the current job to see recommended courses. they can't see recommended courses only on the basis of skills.
2- Added key for course card
3- Fix for current job title as refinement is returning array not string
4- when the user selects current job with the goal type `I want to improve my current role` then show him the job card with the job details he selected. Also, allow him to move to the second page to see the recommended courses. 
4- Create a new component named `JobCardComponent` which will be used with both `SearchJobs` and `CurrentJob`
**Test Cases Failure:**
Test cases are failing due to COVERALLS api failure
https://status.coveralls.io/
.
=> feat: added current dropdown functionality to show recommended courses

src/components/skills-quiz/SearchCourseCard.jsx, src/components/skills-quiz/SkillsQuizStepper.jsx, src/components/skills-quiz/data/hooks.js, src/components/skills-quiz/data/tests/hooks.test.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-4940
Top 3 courses should be shown based on the jobs that learner selected or their current job, but when the "See More Courses" button is clicked, it should show courses based on job-skills AND skills selected by learner in the skills dropdown.
=> fix: show top 3 courses based on job-skills only

src/components/skills-quiz/JobCardComponent.jsx, src/components/skills-quiz/SelectJobCard.jsx, src/components/skills-quiz/tests/SearchJobCard.test.jsx, src/components/skills-quiz/tests/SelectJobCard.test.jsx, src/utils/common.js
JIRA: https://openedx.atlassian.net/browse/ENT-4926
Changes: 
- Bolded Median Salary and Job Postings text for Search and Select job cards
- Text color for non-head text is set to "text-gray-700"
- Formatted median salary with separated commas and $ symbol
- Made the header sizes for "Recommended Courses" and "Related jobs and skills" consistent, set to "h3"
- Fixed failing test cases
=> fix: style changes in job card components 

src/components/course/tests/testUtils.js, src/components/search/data/hooks.js, src/components/search/data/tests/hooks.test.jsx
Description: This PR removes Algolia objects with contenttype:program from the search results. This change will be removed once Program cards and Program pages are available in the learner portal via ENT-4858
Jira: https://openedx.atlassian.net/browse/ENT-4865
=> feat: ENT-4865: Filter out programs from search page.

src/components/skills-quiz/SkillsQuizStepper.jsx
**Issue**: Duplicate calls were being made to Algolia from the first step of Skills Quiz page.
**Cause**: The reason was that the search client was initialized inside the Stepper component which was re-initializing on every render and thus losing already cached search data. 
**Solution**: Use React hook useMemo() to initialize the client only once on the first render only which significantly reduced the calls to Algolia. 
**JIRA**: https://openedx.atlassian.net/browse/ENT-4937
=> fix: reduce calls to Algolia from skill quiz

src/components/course/CourseHeader.jsx, src/components/course/tests/CourseHeader.test.jsx, src/components/dashboard/main-content/DashboardMainContent.jsx, src/components/dashboard/sidebar/DashboardSidebar.jsx, src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx, src/components/dashboard/tests/Dashboard.test.jsx
Don't show a "Find a course" button if the enterprise has search disabled; adjust in following places:
1. Dashboard main content
2. Dashboard sidebar
3. Course header breadcrumb.
https://openedx.atlassian.net/browse/ENT-5101
Dashboard for an enterprise with search disabled now:
Course page before:
Course page after this change:
=> fix: Remove links to `/search` if customer has search disabled.

package-lock.json, package.json, src/components/site-header/SiteHeader.jsx, src/components/site-header/tests/SiteHeader.test.jsx
Don't link back to the learner portal dashboard from a LP course page if the customer has search disabled.
ENT-5101
The logo is still there, but it's not a link.
=> fix: no link back to dashboard when the customer has search disabled

src/components/skills-quiz/styles/SkillsQuizDropdowns.scss
=> style: added image style changes on skills quiz page

src/components/skills-quiz/SearchCourseCard.jsx, src/components/skills-quiz/SelectJobCard.jsx
Before
Now
- [x ] Ensure adequate tests are in place (or reviewed existing tests cover changes)
- [x ] Ensure to attach screenshots
- [x ] Ensure to have UX team confirm screenshots
=> fix: center align course result cards and job cards

src/components/program/ProgramCourses.jsx, src/components/program/tests/ProgramCourses.test.jsx
when course is self paced
When course is instructor led
=> feat: hide course start date when course isnt instructor led

src/components/skills-quiz/CardLoadingSkeleton.jsx, src/components/skills-quiz/SearchCourseCard.jsx, src/components/skills-quiz/SkillsCourses.jsx, src/components/skills-quiz/SkillsQuizStepper.jsx, src/components/skills-quiz/constants.js, src/components/skills-quiz/data/hooks.js, src/components/skills-quiz/data/tests/hooks.test.jsx, src/components/skills-quiz/data/utils.jsx, src/components/skills-quiz/styles/_SearchContentCard.scss, src/components/skills-quiz/tests/SkillsCourses.test.jsx
**Tickets**: [ENT5275](https://openedx.atlassian.net/browse/ENT-5275), [ENT5276](https://openedx.atlassian.net/browse/ENT-5276)
=> feat: added new step to show courses grouped with skills user selected and job skills

package-lock.json, package.json, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js
Current enrollments accordion was not updating because the dependency array for usememo was pointing to the same array reference. Deep cloning courseEnrollmentsByStatus as a solution. Also fix a blatant typo.
=> fix: fix course enrollments useMemo bug

src/components/skills-quiz/SkillsQuizStepper.jsx
JIRA: https://openedx.atlassian.net/browse/ENT-5374
**Changes**: Added an outer `<div>` to center align all elements in step 2 of skills-quiz 
**BEFORE:**
**AFTER:**
=> fix: Center align content in step 2 of skills quiz

package-lock.json, package.json, src/components/app/AuthenticatedPage.jsx, src/components/app/AuthenticatedPage.test.jsx, src/components/error-page/ErrorPage.jsx, src/components/error-page/ErrorPageHeader.jsx, src/components/error-page/__snapshots__/ErrorPage.test.jsx.snap, src/components/site-header/AvatarDropdown.jsx, src/components/site-header/tests/SiteHeader.test.jsx, src/setupTest.js
if IDP found and if logout=true url param, then don't redirect to proxy login flow
when an IDP is detected, the logout button now sets `next` to http://<logoutURL_from_today>/?logout=true to make this work
only if idp is present, the logout button will add logout=true to the next param which in turns ends up as the url param when we are redirected after logout concludes, hence the learner portal can use this flag (plus the fact that user is not currently logged in), to show the logout page instead of going back into the redirect system. This fixes the issue that when an IDP is present, a user can't really logout because of the self-loop-back to the IDP which is automatic today
the link there takes user to the learner portal main url such as https://localhost:8734/test-enterprise
=> fix: when logging out, enable user to stay on logged out page ENT-5369

src/components/course/CourseSidebarPrice.jsx, src/components/course/tests/CourseSidebarPrice.test.jsx
Closes [Closes 5380](https://openedx.atlassian.net/browse/ENT-5380)
When displaying browse and request pricing we also check customer configuration. Added test to check we properly display it.
=> fix: proper browse and request condition and testings

src/components/course/CourseRunCard.jsx, src/components/course/CourseRunCards.jsx, src/components/course/SubsidyRequestButton.jsx, src/components/course/enrollment/utils.js, src/components/course/tests/CourseRunCard.test.jsx, src/components/course/tests/SubsidyRequestButton.test.jsx, src/components/enterprise-invite/EnterpriseInvitePage.jsx, src/components/enterprise-invite/EnterpriseInvitePage.test.jsx, src/components/enterprise-subsidy-requests/data/hooks.js
- Handles the case when a user is already logged and links to a new enterprise using an invite key. We need to refresh login so that the new enterprise learner role gets populated in the jwt. 
- Fix subsidy request button behavior, add tests.
=> fix: add login refresh after linking enterprise & fix subsidy request button 

src/components/course/CourseHeader.jsx
The `RequestEnrollment` button now lives below the `CourseRunCards` on the course page.
=> fix: Subsidy Request button is now below the course run cards.

src/components/course/CourseRunCard.jsx, src/components/course/enrollment/utils.js, src/components/course/tests/CourseRunCard.test.jsx
This is to prevent having "competing" calls-to-action on the course page; 1 to enroll, and
another to request enrollment.  We insist that the user must request enrollment if the browse
and request feature is enabled, on for the customer, and the user has no available subsidy applicable to the course.
Admin-portal:
Learner-portal:
Admin-portal:
Learner-portal:
=> fix: Do not render an enrollment button in course card if user must request enrollment

src/components/enterprise-subsidy-requests/data/service.js
To avoid any potential problems/confusion during launch, lets not cache the subsidy request configuration.
=> feat: don't cache subsidy request configuration for launch

src/components/course/CourseRunCard.jsx, src/components/course/tests/CourseRunCard.test.jsx
https://openedx.atlassian.net/browse/ENT-5701
We already have the configuration loaded so we don't need to call useSubsidyRequestConfiguration, which causes each course run card to individually fetch the configuration again.
=> fix: pull subsidy request configuration from context

src/components/dashboard/main-content/course-enrollments/course-cards/RequestedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/data/utils.js, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
=> fix: add partner org names to requested course cards on dashboard

src/components/course/CourseRunCard.jsx, src/components/course/SubsidyRequestButton.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/tests/CourseRunCard.test.jsx, src/components/enterprise-subsidy-requests/data/hooks.js, src/components/enterprise-subsidy-requests/data/tests/hooks.test.jsx
In a [PR that upgrades to frontend-build 9.2.0](https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/508), I've got a couple of new eslint dependency cycle errors:
```
/Users/adusenbery/code/frontend-app-learner-portal-enterprise/src/components/enterprise-subsidy-requests/SubsidyRequestsContextProvider.jsx
5:1  error  Dependency cycle detected  import/no-cycle
/Users/adusenbery/code/frontend-app-learner-portal-enterprise/src/components/enterprise-subsidy-requests/data/hooks.js
9:1  error  Dependency cycle detected  import/no-cycle
```
This PR just moves the `useUserHasSubsidyRequestForCourse` hook from the `enterprise-subsidy-requests` component over to the `course` component, because it's only used by the `course` component.
=> fix: untangle dependency cycle in subsidy request contexts/hooks.

src/components/program-progress/ProgramListingCard.jsx, src/components/program-progress/ProgramProgressPage.jsx, src/components/program-progress/styles/_ProgramListingCard.scss
- Title of the card is truncated if it increases from 2 lines to avoid ugly card row on large text
- Bottom margins of the cards is short now
- Progress details of card are stick to bottom
- Cards have shorter width
-------------------------------------
- Everything in the page is centred and it looks better
=> style: fix style issues with program progress page

src/components/course/CourseRunCard.jsx, src/components/course/tests/CourseRunCard.test.jsx
https://openedx.atlassian.net/browse/ENT-5789
Fix showing 'Course started' when the course run hasn't started yet.
=> fix: fix course run card status display

src/components/dashboard/main-content/DashboardMainContent.jsx, src/components/dashboard/main-content/DashboardPopularCourses.jsx, src/components/dashboard/main-content/data/constants.js, src/components/layout/MainContent.jsx, src/components/layout/Sidebar.jsx, src/components/search/popular-results/PopularResults.jsx, src/components/search/popular-results/PopularResultsIndex.jsx
https://2u-internal.atlassian.net/browse/ENT-5759
https://2u-internal.atlassian.net/wiki/spaces/SOL/pages/15144464/Experiment+1+Do+static+popular+courses+on+dashboard+increase+enterprise+learner+engagement
This makes use of a very convenient, existing component called `PopularResults`, which is what's shown by default when a search in learner portal returns no results.  
* The "Popular Courses" will only render if the learner has 0 course enrollments.
* It's currently set to show the 4 most popular courses that are available to a learner in some customer/catalog/subsidy state.  We can change `4` to be any other number on the Dashboard.
* After consulting with UX, changed the number of columns on MainContent to 8, removing the offset from the Sidebar and gave it a `pl-5` - this is so the …
=> Experiment 1 | Add popular courses to dashboard

src/components/pathway/SearchPathwayCard.jsx, src/components/search/styles/_SearchResults.scss
Extends the fixed height of search result cards just a touch and throws an `h-100` onto the pathway `Card`.
=> fix: fix pathway search card height

package-lock.json, package.json
ENT-5800 - this brings in a change to use a MediaQuery to toggle the mobile view for SearchFilter.
The interesting change: https://github.com/openedx/frontend-enterprise/pull/259
=> fix: upgrade catalog-search to 3.0.3

src/components/pathway/SearchPathwayCard.jsx, src/components/skills-quiz/styles/_SearchContentCard.scss
Fixes the following problems:
* Card heights for pathway cards in the search page, with long titles and 4 long skills names, overran their allocated height.  We fixed this be removing some extraneous padding from the card section.
* Pathway cards in skills builder were too short and not taking up allocated space.  Fixed this by removing (?!) `h-100` when the pathway card is for the skills quiz (and relatedly setting the card image cap height to 100% so there's no dead space before the header)
=> fix: make pathway card heights consistent.

src/components/program-progress/data/utils.jsx, src/components/program-progress/tests/ProgramProgressCourses.test.jsx
[ticket](https://2u-internal.atlassian.net/browse/ENT-5846)
Before:
After:
=> fix: show only recent course run when multiple enrolled

src/components/enterprise-user-subsidy/coupons/data/service.js, src/components/enterprise-user-subsidy/enterprise-offers/data/hooks.js, src/components/enterprise-user-subsidy/enterprise-offers/data/service.js, src/components/enterprise-user-subsidy/enterprise-offers/data/tests/hooks.test.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/tests/service.test.js
- query only for current coupons & offers
- check for active subscriptions specifically when determining if an enterprise can use offers
=> fix: only check for active coupons, offers, and subs for offers usage

src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx
=> fix: add failure url to ecommerce url query params

src/components/course/data/utils.jsx, src/components/course/tests/CourseSidebarPrice.test.jsx, src/components/dashboard/sidebar/EnterpriseOffersSummaryCard.jsx, src/components/dashboard/sidebar/SubsidiesSummary.jsx, src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx, src/components/dashboard/sidebar/tests/EnterpriseOffersSummaryCard.test.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js, src/components/enterprise-user-subsidy/enterprise-offers/data/service.js, src/components/enterprise-user-subsidy/enterprise-offers/data/tests/utils.test.js, src/components/enterprise-user-subsidy/enterprise-offers/data/utils.js, src/components/program/ProgramCourses.jsx, src/components/program/tests/ProgramCourses.test.jsx
https://2u-internal.atlassian.net/browse/ENT-5973
- initial changes to start support offers with per user bookings limit
- only change affecting current users is the addition of the offer end date
=> feat: initial changes to support per user bookings limit offers

src/components/enterprise-page/data/hooks.js, src/components/enterprise-page/data/tests/hooks.test.js
There could technically be a case where a user is an admin but not a learner in enterprise A (Roles were created manually). Since the jwt roles are ordered in a way that admin roles come first, the first role does not necessarily correspond to the active enterprise. This change handles that edge case.
=> fix: handle edge case with admin role but no learner role

.github/workflows/ci.yml
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
Right now if you push multiple times in succession, each push triggers the workflow to run. This change cancel in-progress runs so we don't waste/hog runner resources.
=> feat: cancel in progress workflow runs

package-lock.json, package.json, src/components/dashboard/main-content/course-enrollments/CourseEnrollmentsContextProvider.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/UnenrollModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/UnenrollModal.test.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/data/index.js, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/data/service.js, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/index.js, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.js, src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/data/utils.js, src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js
Adds "Unenroll" option to overflow menu dropdown items. Upon click, opens an `AlertModal` to confirm unenrollment. If cancelled, modal closes. If "Unenroll" is clicked, makes API request to perform the unenrollment, and closes the modal. Segment events are tracked on modal open, close, and successful unenrollment.
Not screenshotted, but an error `Alert` will appear if the unenrollment API call fails for any reason, with user having an opportunity to try again.
The "Unenroll" option appears for in-progress, upcoming, completed (no certificate earned), and saved for later courses. It does not work for requested courses (a requested course enrollment is not yet unenrollable), or completed courses with a certificate earned.
=> feat: unenroll from courses on dashboard route

package-lock.json, package.json, src/components/enterprise-page/data/hooks.js, src/components/executive-education-2u/ExecutiveEducation2UPage.jsx, src/components/executive-education-2u/ExecutiveEducation2UPage.test.jsx, src/components/executive-education-2u/UserEnrollmentForm.jsx, src/components/executive-education-2u/data/constants.js, src/components/executive-education-2u/data/hooks.js, src/components/executive-education-2u/data/hooks.test.js, src/components/executive-education-2u/data/index.js, src/components/executive-education-2u/data/service.js, src/index.scss
https://2u-internal.atlassian.net/browse/ENT-6134
On the Executive Education (2U) page:
* Fetch content metadata for Executive Education (2U) content based on from `course_uuid` query parameter.
* Display page title, enterprise branding, and a starting point of the enrollment form.
* Tests for the `ExecutiveEducation2UPage` component
=> feat: fetch course title on Exec Ed (2U) enrollment info page

package-lock.json, package.json, src/components/executive-education-2u/ExecutiveEducation2UPage.jsx, src/components/executive-education-2u/FormSectionHeading.jsx, src/components/executive-education-2u/UserEnrollmentForm.jsx, src/components/executive-education-2u/UserEnrollmentForm.test.jsx, src/components/executive-education-2u/data/index.js, src/components/executive-education-2u/data/service.js
Updates the Executive Education (2U) page, where we collect the learner's first and last names, and whether they agree with GetSmarter's Terms and Conditions for Students. Includes form validation for the required fields.
=> feat: add functionality to Executive Education (2U) form and cleanup

src/components/course/EnrollModal.jsx, src/components/course/data/hooks.jsx, src/components/course/data/utils.jsx, src/components/course/enrollment/components/ToEcomBasketPage.jsx, src/components/course/enrollment/tests/ToEcomBasketPage.test.jsx, src/components/course/tests/EnrollModal.test.jsx, src/components/dashboard/main-content/course-enrollments/UpgradeableCourseEnrollmentContextProvider.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/ContinueLearningButton.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/UpgradeCourseButton.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/InProgressCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.js
https://2u-internal.atlassian.net/browse/ENT-5827
- Support upgrading a course to verified track using a coupon code
- Does not have the upgrade message in the card footer yet, we can ship this as a stand-alone or wait for the paragon changes required for the light grey card status (secondary variant).
=> feat: support upgrading course using coupon code

src/components/progress-category-bubbles/ProgressCategoryBubbles.jsx
the 'in progress' text is breaking into lines due to less availability of space.
so reducing gap to original
=> style: reduce gap between progress categories

src/components/skills-quiz/SkillsQuizStepper.jsx, src/components/skills-quiz/constants.js, src/components/skills-quiz/data/service.js, src/components/skills-quiz/data/tests/service.test.jsx, src/components/skills-quiz/data/tests/utils.test.jsx, src/components/skills-quiz/data/utils.jsx
Added ability to save user-selected options on the skills quiz page. For that first fetches the skills Id from backend by passing the skills user selected. Jobs IDs are available on the front end. Jobs and skills IDs are then passed to backend to store the data.
Ticket: https://2u-internal.atlassian.net/browse/ENT-6178
=> feat: Added ability to save user selected options on skill quiz

.github/workflows/ci.yml, src/components/search/SearchPage.jsx, src/components/search/constants.js
Adding a trackingName will make it so this code: https://github.com/openedx/frontend-enterprise/blob/5c2ae6b83da80638c87ee34c0093244819e3cb05/packages/catalog-search/src/SearchBox.jsx#L48-L68 is utilized, and segment events will be sent for search queries.
This will help with analysis of search behavior, e.g. ENT-6241
temporarily unblock PRs with failing codecov
=> feat: add a trackingName to SearchData instance, so that queries are tracked

src/components/search/SearchCourseCard.jsx
ENT-6299
Somewhere in Paragon 20, I think the `h-100` became the default for card headers.
Fixes this:
=> fix: remove h-100 for search course card header.

src/components/pathway-progress/PathwayProgressListingPage.jsx, src/components/program-progress/ProgramListingPage.jsx
This PR is to sync the colors for all the buttons in all the dashboard tabs. Screenshots are attached bellow
=> fix: enterprise colors for explore programs and explore pathways buttons

src/components/enterprise-banner/EnterpriseBanner.jsx, src/components/enterprise-banner/styles/EnterpriseBanner.scss, src/components/layout/data/hooks.js
In talking with Jenn and Alena, they want all primary buttons (even primary-brand) buttons to look the color that they have customized in the admin portal. I recommended that the secondary color (banner color in admin portal) could be used as a brand color so we could have differing styles for different buttons, but since these color's haven't passed accessibility checks, they just made the decision for the first iteration, we will have all buttons be the "button" color. 
[Figma](https://www.figma.com/file/d0I9hSyXdSGtsqgniJPmK2/Admin-Portal-Redesign?node-id=1597%3A53228) | [JIRA ticket](https://2u-internal.atlassian.net/browse/ENT-6101)
=> fix: small learner portal changes for branding

src/components/executive-education-2u/UserEnrollmentForm.jsx, src/components/executive-education-2u/UserEnrollmentForm.test.jsx, src/components/executive-education-2u/data/index.js, src/components/executive-education-2u/data/utils.js
The `/enterprise_allocations` endpoint wants `termsAcceptedAt` to conform to ISO 8601 spec, but _without the milliseconds_ as their API has a character limit on the field.
For example, we generate a timestamp per the following:
```
new Date().toISOString()
'2022-09-28T14:22:11.017Z'
```
However, the GEAG API doesn't want the `.017` at the end, despite being standard spec for ISO 8601.
While we could make this change to get around the GEAG API validation, we've reached out to the GetSmarter team to clarify whether the field should have any valid ISO 8601 input, which we are already passing.
If the validation is changed on the API to support milliseconds per the spec, this PR can be closed. Otherwise, we'll need this fix to properly call the GEAG API.
=> fix: trim milliseconds from termsAcceptedAt

src/components/course/CourseHeader.jsx, src/components/course/SubsidyRequestButton.jsx, src/components/course/tests/SubsidyRequestButton.test.jsx
https://2u-internal.atlassian.net/browse/ENT-6300
Removes useHistory on SubsidyRequestButton callback that redirects on button click after displaying Toast
Remove prop parameter 'enterpriseSlug' used solely to redirect user to dashboard
Remove passed prop within CourseHeader component
Refactored corresponding tests using enterpriseSlug prop
=> fix: Remove redirect to dashboard on course 'request enrollment'

src/components/course/CourseRunCard.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/enrollment/EnrollAction.jsx, src/components/course/enrollment/components/ToDataSharingConsent.jsx, src/components/course/enrollment/tests/EnrollAction.test.jsx, src/components/course/tests/CourseRunCard.test.jsx, src/index.jsx, src/utils/optimizely.js
**Description:**
Hypothesis: IF we show license learners that the course truly is free to them at the moment of enrollment, THEN they will be more likely to enroll, BECAUSE we will be more closely tying together the concepts of “we want you to enroll now” and “this course is free to you”.
Implementation: If the learner has a subscription license, bring the struck out price information in the course sidebar into the enrollment area above the fold. 50% / 50% traffic. Assess whether or not learners are ( 1 ) more likely to enroll in a course based on receiving vs. not receiving the treatment.
**JIRA:** https://2u-internal.atlassian.net/browse/ENT-6204
---
**Control:**
**Variation 1:**
=> feat: Optimizely experiment for learners with a subscription license.

src/components/dashboard/sidebar/CouponCodesSummaryCard.jsx, src/components/dashboard/sidebar/EnterpriseOffersSummaryCard.jsx, src/components/dashboard/sidebar/SubsidiesSummary.jsx, src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/hooks.js, src/components/enterprise-user-subsidy/enterprise-offers/data/tests/hooks.test.jsx, src/components/layout/Sidebar.jsx
https://2u-internal.atlassian.net/browse/ENT-6290
Associated Figma: https://www.figma.com/file/glKHoHBACvTw2oeKs2TO1O/Offers?node-id=314%3A24838
Initial PR to review implementation and test of crossing out the price for a stacked enterprise customer with both Subsidy and Licenses. Additional UI changes would need to be implemented to take into account stacked license and subscription. 
Initial UI changes implemented. Requires consolidation of component display logic, but pushing for feedback on consolidation techniques.
=> feat: Update user subsidy logic to accept stacked subsidy and licence

src/components/search/SearchCourseCard.jsx, src/components/search/data/constants.js, src/components/search/data/hooks.js, src/components/search/tests/SearchCourseCard.test.jsx, src/components/search/utils.js, src/index.jsx, src/utils/optimizely.js
These changes are to show the course length in the course search card footer on the search page. We have this picture for a clear view 
This PR implements the A/B test where 50% of the learners are shown the course length on the course search card while the other users get the regular experience. 
The Algolia Index contains the `course_length` field which specifies the course length as `short`, `medium` or `long` but we just change the footer from the regular text "Course" to "Short Course" when the course length is short. 
JIRA: [ENT-6372](https://2u-internal.atlassian.net/browse/ENT-6372)
=> feat: course length in course search card footer and optimizely A/B test

src/components/search/content-highlights/ContentHighlights.jsx, src/components/search/content-highlights/data/hooks.js, src/components/search/content-highlights/data/service.js
Only fetch the highlight sets for the current enterprise customer (like this PRs predecessor, we're deferring on tests until tomorrow as a fast follow; minimal risk).
=> fix: ensure to only fetch highlight sets for the current enterprise customer

package-lock.json, package.json
Upgrades Paragon to v20.26.2 pull in new `Card` feature related to a default fallback image for the `Card.ImageCap` subcomponent ([docs/example](https://paragon-openedx.netlify.app/components/card/#with-default-fallback-image)).
=> chore: upgrade @edx/paragon to v20.26.2 for Card.ImageCap fallback images

package-lock.json, package.json, src/components/search/content-highlights/HighlightedContentCard.jsx
Instead of the default solid gray background for fallback image in `Card.ImageCap`, opts to use a more style version from the `@edx/brand` packages:
**Note: Test coverage can be ignored; tests for highlights in this repo were intentionally deferred and will be done in a follow-up PR**
=> fix: use imported fallback img from @edx/brand

src/components/enterprise-banner/EnterpriseBanner.jsx, src/components/search/content-highlights/data/hooks.js, src/components/search/content-highlights/data/tests/hooks.test.js
=> fix: ensure learner portal works without curation config

src/components/skills-quiz/SearchJobCard.jsx, src/components/skills-quiz/tests/SearchJobCard.test.jsx
**Problem**
while saving the skill quiz the current_job_id is not sending to the backend and is saved as null.
**Solution**
CurrentJobRole was only set when the goal was 'I want to improve my current role'. So I set the value of currentJobRole in other goals as well. Now, current_job_id is sending every time to the skill quiz endpoint.
=> fix: handle current_job_id while saving skill quiz by learner

src/components/skills-quiz/IndustryDropdown.jsx
This PR allows the refinement of the jobs dropdown on the basis of the value selected In the Industry dropdown.
=> feat: Allow job filtering on the basis of current industry

src/components/dashboard/DashboardPage.jsx, src/components/enterprise-redirects/EnterpriseLearnerFirstVisitRedirect.jsx, src/components/enterprise-redirects/tests/EnterpriseLearnerFirstVisitRedirect.test.jsx, src/index.jsx
__Jira Ticket:__ [ENT-6851](https://2u-internal.atlassian.net/browse/ENT-6851)
IF a learner on their first visit to their enterprise’s learner portal is redirected to the /search page, THEN they will be more likely to enroll, BECAUSE the /search page has the most to offer learners who are entering their organization’s learner portal for the first time.
**Acceptance Criteria:**
1. Detect if this is the user’s first visit to the learner portal.
2. Detect if the page they are going to is the learner dashboard page.
3. If both are true, redirect the learner to the learner portal /search page. 
4. Upon subsequent, future logins, no redirect should happen. It is only on the first time that we redirect.
5. This should be implemented as a 50/50 split in Optimizely.
=> ENT-6851: Redirect the user to search page if he is visiting dashboard for the very first time.

src/components/executive-education-2u/ExecutiveEducation2UError.jsx, src/components/executive-education-2u/ExecutiveEducation2UPage.test.jsx
https://2u-internal.atlassian.net/browse/ENT-7059
Added new message for not enough applications (enrollments) remaining, updated existing balance messages to be consistent with message pattern.
Not enough remaining applications
Not enough balance
Not enough user balance
=> feat: add exec ed no remaining applications failure message. ENT-7059

src/components/enterprise-user-subsidy/enterprise-offers/data/service.js, src/components/enterprise-user-subsidy/enterprise-offers/data/tests/service.test.js
Removes per-user balance/enrollment limit filter from the API request. This will start pulling in enterprise offers with the per-user balance/enrollment limits, though we don't have any validation for these per-user limits. This will result in learners seemingly able to enroll with their learner credit, but will get an error (TBD) in ecommerce after confirming their enrollment.
=> feat: include offers with per-user limits

package-lock.json, package.json, src/components/executive-education-2u/UserEnrollmentForm.jsx, src/components/executive-education-2u/UserEnrollmentForm.test.jsx
If user is not 18 years old then we should block the user from moving forward with course enrollment and do not allow him to simply update the age.
Here is the screenshot of the new error screen.
=> fix: Do not let the user pass if age is not valid.

src/components/course/CoursePage.jsx, src/components/course/tests/CoursePage.test.jsx
Use `isInitialLoading` ([docs](https://tanstack.com/query/v4/docs/react/guides/disabling-queries#isinitialloading)) instead. 
If the query isn't enabled, `isLoading: true` will always be returned but `isFetching` will be false. `isInitialLoading` takes into account both of these with an `&&` instead of the previous implementation's `||`.
=> fix: use `isInitialLoading` instead of using `isLoading || isFetching`

src/components/executive-education-2u/UserEnrollmentForm.jsx
Enforces a max date allowed on the native browser date picker input field, where dates beyond today's date are disabled on the selection. Usability improvement.
=> fix: add max prop to date Form.Control for date of birth

src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx
Ensure the "no enterprise admins" variant of the "org out of funds" message is shown for legacy subsidies like enterprise offers, e.g.:
=> fix: use NO_SUBSIDY_NO_ADMINS reason type when no admins exist

src/components/course/course-header/CourseRunCards.jsx
In the case of production, the EMET feature flag is disabled so we are not making an API request to enterprise-access's `can-redeem` API endpoint. As such `redeemabilityPerContentKey` is undefined, but we are attempting to do a `.find` on it instead of handling the case when its `undefined`.
=> fix: handle undefined `redeemabilityPerContentKey`

src/components/course/CourseContextProvider.jsx, src/components/course/CoursePage.jsx, src/components/course/course-header/CourseRunCard.jsx, src/components/course/course-header/CourseRunCardStatus.jsx, src/components/course/course-header/CourseRunCards.jsx, src/components/course/course-header/data/hooks/tests/useCourseRunCardAction.test.jsx, src/components/course/course-header/data/hooks/useCourseRunCardAction.jsx, src/components/course/course-header/data/hooks/useCourseRunCardData.js, src/components/course/course-header/deprecated/CourseRunCard.jsx, src/components/course/course-header/tests/CourseRunCardStatus.test.jsx, src/components/course/course-header/tests/DeprecatedCourseRunCard.test.jsx, src/components/course/enrollment/tests/utils.test.js, src/components/course/enrollment/utils.js, src/components/course/tests/CourseContextProvider.test.jsx
Disabled enroll button and message saying "No funds" when user can also "Request enrollment" (only 1 CTA should be visible at a time).
Hides enroll button and message, only showing "Request enrollment" button below the course run cards.
=> fix: ensure new CourseRunCard interacts well with Browse and Request

src/components/course/CourseSidebarPrice.jsx, src/components/course/tests/CourseSidebarPrice.test.jsx
Resolves an existing bug related to showing a "Free to me (when approved)" message in the learner portal course sidebar price when subsidy requests are enabled, the user has no subsidy, and the course is not contained by any catalog(s) associated with the subsidy typ being used for Browse & Request.
This PR adds a check to ensure the course is contained by a catalog(s) associated with the subsidy configured for the browse & request feature.
=> fix: resolve bug with showing price is free when approved

src/components/course/CourseContextProvider.jsx, src/components/course/CoursePage.jsx, src/components/course/course-header/tests/CourseHeader.test.jsx, src/components/course/course-header/tests/DeprecatedCourseRunCard.test.jsx, src/components/course/data/constants.js, src/components/course/enrollment/tests/EnrollAction.test.jsx, src/components/course/enrollment/tests/hooks.test.jsx, src/components/course/tests/CourseAssociatedPrograms.test.jsx, src/components/course/tests/CourseContextProvider.test.jsx, src/components/course/tests/CoursePage.test.jsx, src/components/course/tests/CourseRecommendations.test.jsx, src/components/course/tests/CourseSidebarPrice.test.jsx, src/components/course/tests/CourseSkills.test.jsx, src/components/course/tests/CreatedBy.test.jsx, src/components/course/tests/SubsidyRequestButton.test.jsx, src/components/dashboard/tests/DashboardPage.test.jsx, src/utils/tests.jsx
Noticed a bug on local/stage/production where navigating between courses on the course page (e.g., clicking one of the course card recommendations to another related course) makes the expected additional API calls but does not re-render the data once the APIs resolve, leaving the user confused why they're not seeing the other course data. Refreshing the page after clicking the recommendation card shows the correct course.
This issue is due to the `courseState` being used within a `useReducer`, such that it only acts as initial state; not the active, current state representing the latest data available. To mutate the reducer state, you need to dispatch actions, we aren't doing.
To fix this issue, we will no longer use the `useReducer` hook within the `CourseContextProvider`, and simply …
=> fix: ensure new course data renders when switching between courses

src/components/course/data/tests/service.test.js, src/components/stateful-enroll/StatefulEnroll.jsx, src/components/stateful-enroll/StatefulEnroll.test.jsx, src/components/stateful-enroll/data/hooks/useTransactionStatus.js, src/components/stateful-enroll/data/service.js
This PR uses the new `transaction_status_api_url` field from the transaction create response instead of constructing the API url with the transaction UUID.
=> chore: transaction_status_api_url from transaction create response

src/components/dashboard/DashboardPage.jsx, src/components/dashboard/main-content/CoursesTabComponent.jsx, src/components/my-career/AddJobRole.jsx, src/components/my-career/SkillsRecommendationCourses.jsx, src/components/my-career/tests/AddJobRole.test.jsx, src/components/my-career/tests/SkillsRecommendationCourses.test.jsx, src/components/skills-quiz/tests/SkillsQuizPage.test.jsx, src/components/skills-quiz/tests/utils.test.jsx, src/components/system-wide-banner/SystemWideWarningBanner.test.jsx
Moves the `IntegrationWarningModal` and `SubscriptionExpirationModal` to the common parent component `DashboardPage` to avoid rendering from two separate components.
Removes `IntegrationWarningModal` and `SubscriptionExpirationModal` and related dependencies from `CoursesTabComponent` and `AddJobRole` since they are rendered on the same parent component.
Pending Tests.
=> fix: consolidates IntegrationWarningModal to parent to avoid duplicate calls

src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx, src/components/course/routes/tests/ExternalCourseEnrollmentConfirmation.test.jsx
Ticket: [ENT-7206](https://2u-internal.atlassian.net/browse/ENT-7206)
The `/:enterpriseSlug/:courseType/course/:courseKey/enroll` and `/:enterpriseSlug/:courseType/course/:courseKey/enroll/complete` routes also take this into account now when determining whether to show an error screen.
=> fix: ensure we count prior redemption as having subsidy available for the course

src/components/course/CoursePage.jsx, src/components/course/data/hooks.jsx, src/components/course/data/service.js, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx, src/components/course/tests/CoursePage.test.jsx, src/components/search/data/hooks.js
Filters `courseRuns` using an existing filter function to reduce number of query params appended to the `canRedeem` endpoint in the `CoursePage`
Wrote tests to cover code changes
=> feat: Filters courseRuns for canRedeem endpoint

src/components/course/course-header/CourseRunCard.jsx, src/components/course/course-header/data/hooks/useCourseRunCardData.js, src/components/course/course-header/data/hooks/useCourseRunCardHeading.js, src/components/course/course-header/deprecated/CourseRunCard.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx, src/components/executive-education-2u/ExecutiveEducation2UPage.jsx
Uses a recently introduced `getCourseStartDate` function that takes into account course type, pulling the course start date from either the course run or additional metadata when appropriate.
=> fix: use start date from addtl metadata for exec ed course above enroll cta

src/components/course/course-header/data/hooks/tests/useCourseRunCardHeading.test.jsx, src/components/course/course-header/data/hooks/useCourseRunCardHeading.js, src/components/course/course-header/data/utils.js, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx, src/components/course/routes/tests/ExternalCourseEnrollmentConfirmation.test.jsx, src/components/executive-education-2u/components/CourseSummaryCard.jsx
Another start date related fix/hack due to exec ed courses always having availability: "Current" in our system, even if start date is upcoming (ensures the course run card says "Starts" vs. "Started" depending on whether exec ed course is already started based on its start date.
=> fix: ensure we take into account start date when determining if course run is current

src/components/course/course-header/CourseHeader.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/utils.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx, src/components/course/routes/tests/ExternalCourseEnrollmentConfirmation.test.jsx, src/components/course/styles/_CourseHeader.scss, src/components/executive-education-2u/EnrollmentCompleted.test.jsx, src/components/executive-education-2u/ExecutiveEducation2UPage.jsx, src/components/executive-education-2u/ExecutiveEducation2UPage.test.jsx, src/components/executive-education-2u/components/CourseSummaryCard.jsx
**Description:**
[ENT-7241](https://2u-internal.atlassian.net/browse/ENT-7241)
* Ensures we display the organization name/logo override fields (if set) depending on the course type configuration for the course type in question (e.g., an externally hosted course) on the course about page routes.
* Ensures the organization logo on the `/:enterpriseSlug/:courseType/course/:courseKey/enroll` and `/:enterpriseSlug/:courseType/course/:courseKey/enroll/complete` routes links to the organization's marketing url.
* Cleans up the styles for the organization logo to handle the different logo image heights between the override and non-override logo images on the course about page routes by setting a min-height and vertically centering the logo within it.
* Moves existing SCSS under the …
=> fix: use correct overrides for exec ed course partner logos on course page

src/components/executive-education-2u/EnrollmentCompleted.test.jsx, src/components/executive-education-2u/components/EnrollmentCompletedSummaryCard.jsx
GetSmarterDashboard opens in a new tab, updated test to reflect changes
=> feat: GetSmarter dashboard opens in a new tab

src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/constants/course.js
__Jira Ticket:__ [ENT-7186](https://2u-internal.atlassian.net/browse/ENT-7186)
This PR updates the style of the course run card component displayed on the learner dashboard for executive education courses. With this change, executive education course cards will have a dark background and light text, visually distinguishing them from other courses on the dashboard.
=> ENT-7186: Style changes for executive education course cards on dashboard.

src/components/my-career/VisualizeCareer.jsx, src/components/my-career/data/hooks.jsx
Display a loading spinner until we get information about the updated current job on the career chart page.
[JIRA-> ENT-7318](https://2u-internal.atlassian.net/browse/ENT-7318)
=> feat: add loading spinner for updated current job on career chart page

src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/CompletedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/ContinueLearningButton.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/RequestedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/SavedForLaterCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/UnenrollModal.jsx, src/components/dashboard/main-content/course-enrollments/data/constants.js
This PR covers following front-end changes for exec-ed courses on LP
No extraneous button present (email settings/unenroll if EE cannot be modified through LP)
- No extraneous button present (email settings for EE)
- Resume course button brings the learner to GetSmarter Dashboard
- Button is grayed out and presents the course start date if the course has not started
- Relevant course information is presented on the enrollment tile (start date).
- Microcopy ex. ‘This course is self-led. Complete at your own speed before May 26, 2025.’ is updated dynamic with course end-date and EE pacing type. 
- for “Unenroll”, route learners to this link: https://www.getsmarter.com/cancel-defer
- update the 3-dot menu and the footer text to light 300
- change “instructor-paced” to …
=> feat: front-end changes required for EE courses on LP

src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx
During stage QA, noticed a customer having 2 active, subs plan where 1 is expired. The current logic thinks all applicable subscription plans are expired, which isn't true for this test customer; it has 1 active, current subscription plan applicable to the course.
=> fix: ensure multiple subs work properly when 1 has previously expired

src/components/course/CourseSidebar.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx, src/components/course/tests/CourseSidebar.test.jsx
Refactor `useCourseSubject` to be a utility function, instead of using `useState` and `useEffect`. Additionally, the enrollmentUrl function can use existing helper functions `createEnrollWithLicenseUrl` and `createEnrollWithCouponCodeUrl`.
=> chore: Refactor useCourseSubject and enrollmentUrl

src/components/my-career/SearchJobRole.jsx, src/components/search/data/hooks.js, src/components/skills-quiz/SearchJobCard.jsx, src/components/skills-quiz/SkillsQuizStepper.jsx, src/components/skills-quiz/constants.js
__Jira Ticket:__ [ENT-7234](https://2u-internal.atlassian.net/browse/ENT-7234)
Job in Algolia either originate from course skills data or industry skills data. We want to ignore jobs that originate from industry skills data. This PR takes care of that.
=> ENT-7234: Filter jobs based on job source attribute.

docs/decisions/0009-moment-to-dayjs.rst, src/components/course/course-header/data/hooks/tests/useCourseRunCardHeading.test.jsx, src/components/course/data/utils.jsx, src/components/dashboard/SubscriptionExpirationModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/Notification.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx, src/components/dashboard/sidebar/SubscriptionSummaryCard.jsx, src/components/dashboard/sidebar/tests/SubscriptionSummaryCard.test.jsx, src/components/pathway-progress/SubscriptionStatusCard.jsx, src/components/program-progress/ProgramProgressCourses.jsx, src/components/program-progress/SubscriptionExpiringWarningModal.jsx, src/components/program-progress/data/utils.jsx, src/components/program-progress/tests/ProgramProgressCourses.test.jsx, src/utils/common.js, src/utils/dayjs.js
The dayjs implementation needed an additional plugin in order to format using the format('MMMM Do, YYYY')}. string. The 'o' part after the day stands for ordinal, which formats it like 1**st** or 2**nd**. Without this plugin, there's just a random 'o' in the middle of the date.
https://day.js.org/docs/en/plugin/advanced-format
https://2u-internal.atlassian.net/browse/ENT-7495
=> fix: ordinal bug with dayjs

src/components/course/CoursePage.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/utils.jsx
Following the changes for subscription priority in [ENT-7663,](https://2u-internal.atlassian.net/browse/ENT-7663) we need to allow the parent CoursePage to load before rendering the content.
=> fix: add isLoadingAny to useUserSubsidyApplicableToCourse

src/components/course/data/service.js
Remove the client side caching for `fetchUserLicenseSubsidy` to account for cases where a subscription is revoked and the subsidy should fall back to other types.
=> fix: remove caching for fetchUserLicenseSubsidy

src/components/course/CoursePage.jsx, src/components/course/course-header/CourseRunCard.jsx, src/components/course/course-header/tests/CourseRunCard.test.jsx, src/components/course/data/hooks.jsx
* Exposes proper `isLoading` variable from `useAllCourseData`. Previously, we were never truly working with the legit loading state of all the data returned by `useAllCourseData`...
* Switches `CourseRunCard` component to rely on the `userSubsidyApplicableToCourse` from `CourseContext`, rather than relying on the `subsidyAccessPolicy` derived directly from the API. Rationale: the intent is to rely on a single data structure representing the subsidy applicable to course for the entire course page, rather than relying on disparate data that may be different depending on the component re-rendering lifecycle (i.e.,, enroll button CTA for Learner Credit should rely on same data source as the course sidebar price strikeout).
=> fix: use proper isLoading variable and rely solely on userSubsidyApplicableToCourse throughout

src/components/search/data/hooks.js, src/components/search/data/tests/hooks.test.jsx
Ensure only current (non-expired) enterprise offers are considered in the learner portal search.
=> fix: filter out expired offer in search catalogs

src/components/enterprise-user-subsidy/coupons/data/actions.js, src/components/enterprise-user-subsidy/coupons/data/tests/actions.test.js, src/components/enterprise-user-subsidy/data/hooks/useSubscriptions.js, src/components/enterprise-user-subsidy/data/hooks/useSubscriptions.test.js, src/components/search/data/hooks.js, src/components/search/data/tests/hooks.test.jsx
https://2u-internal.atlassian.net/browse/ENT-7743
Ensures content contained by catalog uuids associated with expired subscription plans or coupon codes are excluded from search results.
=> fix: exclude expired subscription plans and coupon codes from search

src/components/course/CoursePage.jsx, src/components/dashboard/sidebar/SubsidiesSummary.jsx, src/components/dashboard/sidebar/utils.js, src/components/dashboard/sidebar/utils.test.js, src/components/enterprise-user-subsidy/UserSubsidy.jsx, src/components/my-career/SkillsRecommendationCourses.jsx, src/components/search/Search.jsx, src/components/search/data/hooks.js, src/components/search/data/tests/hooks.test.jsx, src/components/search/popular-results/PopularResultsIndex.jsx, src/components/skills-quiz/SearchCourseCard.jsx, src/components/skills-quiz/SearchPathways.jsx, src/components/skills-quiz/SearchProgramCard.jsx, src/components/skills-quiz/SkillsCourses.jsx
[ENT-7741](https://2u-internal.atlassian.net/browse/ENT-7741)
> Ensure subsidy access policies are recognized across all usages of `useSearchCatalogs` (e.g., course page recommendations, skills quiz course recommendations, and search page).
=> fix: ensure redeemable subsidy access policies are included in search catalogs

src/components/course/CourseRecommendationCard.jsx, src/components/pathway-progress/PathwayProgressCard.jsx, src/components/pathway/SearchPathwayCard.jsx, src/components/program-progress/ProgramListingCard.jsx, src/components/search/SearchCourseCard.jsx, src/components/search/SearchProgramCard.jsx, src/components/skills-quiz/SearchProgramCard.jsx
When the ImageCap is null, the card component formatting looks like this _(before screenshot):_
Setting a default image that is accessible in the front end will provide a fallback for the image, even if it's null _(after screenshot):_
I also added the fallback image to other `Card.ImageCap` instances.
=> fix: add default image to SearchProgramCard ImageCap

src/components/search/content-highlights/HighlightedContentCard.jsx, src/components/skills-quiz/CourseCard.jsx
=> fix: ensure HighlightedContentCard and skills quiz course cards have fallback card images

src/components/program-progress/ProgramListingCard.jsx, src/components/program-progress/tests/ProgramListingCard.test.jsx
This reverts commit 451b94b85eeef96e7527968ecfe383fab58e71ff.
In a twist of events after QA'ing on stage, I now realize why the `ProgramListingCard` was using the inconsistent `banner_images` data... I didn't realize the data for those cards wasn't coming from discovery's `/programs/{UUID}` API; instead, it's coming from a LMS API (`https://courses.edx.org/api/dashboard/v0/programs/852eac48-b5a9-4849-8490-743f3f2deabf/)`, which does **not** include `card_image_url`...
This previously merged "fix" will essentially never find a `program.cardImageUrl` and always fallback to the textured fallback image (all programs on the dashboard page are currently showing fallback image, as seen below).
=> Revert "fix: ensure program card images are pulled from consistent source (#836)

package-lock.json, package.json, src/components/enterprise-user-subsidy/data/hooks/hooks.js, src/components/enterprise-user-subsidy/data/hooks/hooks.test.jsx
=> fix: auto-applied subs

src/components/course/routes/CourseAbout.jsx, src/components/course/routes/tests/CourseAbout.test.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js, src/components/enterprise-user-subsidy/enterprise-offers/data/utils.js, src/components/my-career/CategoryCard.jsx
When a learner 
- Is assigned a course,
- And has no other subsidy, If they had a subscription, but the license is no longer relevant, we would not want to count that.
we disabled the course search for them.
There are “backdoors” that I have covered in this PR – 
- Course recommendations on the course page.
- My Career Chart recommendations.
- Someone sending a link to another learner of the course page.
JIRA -> [ENT-7854](https://2u-internal.atlassian.net/browse/ENT-7854)
=> feat: hide backdoors for search course

src/components/dashboard/main-content/course-enrollments/CourseSection.jsx
Fix the badge design of the assigned courses count. Previously it was not showing rounded.
Previously:
Now:
=> fix: assigned courses count badge

src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx
**Jira Ticket**: [ENT-7669](https://2u-internal.atlassian.net/browse/ENT-7669)
**Description**:  During testing of ENT-7669, it was discovered that "Assigned" badge is not rendering behind feature flag, thus made the required change.
=> Moved assigned badge behind feature flag

src/components/dashboard/main-content/course-enrollments/data/utils.js
For assigned courses `enrollBy` field was not available in AssignedCourseCard. So fix that issue.
=> fix: enrollBy field value for assigned courses

src/components/dashboard/main-content/course-enrollments/course-cards/CompletedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/ContinueLearningButton.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/SavedForLaterCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/data/utils.js
**Jira Ticket**: https://2u-internal.atlassian.net/browse/ENT-7993
**Description**:  Enabled the usage of `resumeCourseRunUrl` to determine if the learner has made progress on a course.
=> feat: enabled the usage of resumeCourseRunUrl

src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/data/utils.js
This is a bug fix in [response to this](https://2u-internal.atlassian.net/browse/ENT-8065) that got submitted as a Cat 1 on call issue with users getting 404s when trying to resume a course they had already started. After doing some digging I realized that the  resume_course_run_url variable was being set to a (correct) relative path, but that we were using the same domain as the learner portal (enterprise.edx.org), when it reality it should be using http://courses.edx.org/ to start with. Instead of rolling back the changes in edx-enterprise and risk holding up that pipeline, this PR removes the OR statement that defaults to this resume url if it's not null. 
`resume_course_run_url = "/courses/course-v1:LinuxFoundationX+LFS141x+1T2023/jump_to/block-v1:LinuxFoundationX+LFS141x+1T2023+type@h …
=> fix: 404 resume course link error

src/components/dashboard/DashboardPage.jsx, src/components/dashboard/data/utils.js, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/tests/DashboardPage.test.jsx, src/components/enterprise-redirects/EnterpriseLearnerFirstVisitRedirect.jsx, src/components/enterprise-redirects/tests/EnterpriseLearnerFirstVisitRedirect.test.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js
Modifies the logic for redirecting the page to the search page based on whether the `has-user-visited-learner-dashboard` cookie has been set to take into account whether active course assignments exist.
This involves hoisting some of the logic from `CourseEnrollments.jsx` into `DashboardPage.jsx` to avoid partial render before redirect.
=> feat: modifies logic for setting cookies on dashboard page load

src/components/course/CoursePage.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/tests/constants.js
Price on my assignment:
Course page with assignment's list price:
=> fix: use correct listPrice data

src/components/dashboard/main-content/DashboardMainContent.test.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/tests/DashboardPage.test.jsx
***Problem***
After enabling `FEATURE_ENABLE_TOP_DOWN_ASSIGNMENT` on stage it came out that the learner was not able to see his assignments and the course section was blank.
This issue was because of this PR https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/881
Some variable name was used incorrectly which caused the problem.
Solution:
Fix those variables' names and add some additional checks based on the feature flag.
=> fix: blank courses tab issue

src/components/course/CourseSidebarPrice.jsx
Remove extraneous "$0" string from price strikeout. 
|Before|After|
|------|------|
|![Screenshot 2023-12-11 at 12 26 27 PM](https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/71999631/f465c575-46da-46b3-8e9c-7e93f72ffb10)| ![Screenshot 2023-12-11 at 12 26 39 PM](https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/71999631/45599a43-609a-46c8-9ef6-57644d6148c7)|
[JIRA Ticket](https://2u-internal.atlassian.net/browse/ENT-8094)
=> fix: remove "$0" string from pricing strikeout

src/components/course/routes/CourseAbout.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js, src/components/enterprise-user-subsidy/enterprise-offers/data/tests/utils.test.js, src/components/enterprise-user-subsidy/enterprise-offers/data/utils.js, src/components/my-career/tests/CategoryCard.test.jsx, src/components/my-career/tests/MyCareerTab.test.jsx, src/components/my-career/tests/VisualizeCareer.test.jsx
Checks policy types within `redeemableLearnerCreditPolicies` for whether a non-assignable redeemable policy exist, if so, return `false` for `isDisableCourseSearch`.
=> fix: checks for non-assignable policy types to allow course search

src/components/search/content-highlights/data/hooks.js
=> fix: ensure fetchEnterpriseCuration is only called if an enterpriseUUID is present

src/components/course/course-header/data/hooks/useRedemptionStatus.js, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/routes/ExternalCourseEnrollment.jsx, src/components/enterprise-user-subsidy/data/constants.js, src/components/enterprise-user-subsidy/data/hooks/hooks.js, src/components/executive-education-2u/ExecutiveEducation2UPage.jsx, src/components/executive-education-2u/UserEnrollmentForm.jsx, src/components/executive-education-2u/UserEnrollmentForm.test.jsx, src/components/stateful-enroll/data/hooks/useStatefulEnroll.js, src/components/stateful-enroll/data/hooks/useStatefulEnroll.test.js
Invalidates the `redeemablePolicies` query key on success of an external enrollment, and on successful redemption of a course run.
=> fix: invalidate redeemable policies query on enrollment

src/components/course/routes/CoursePageRoutes.jsx, src/components/course/routes/ExternalCourseEnrollment.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx, src/components/executive-education-2u/UserEnrollmentForm.jsx
Updates redirect logic for routes `/:slug/:courseType/course/:courseKey/enroll` to not pass a onCheckoutSuccess function, and depend on the existing `onSuccessfulRedemption` logic in the useEffect to avoid duplicate redirects.
Also refactors the path name generation using `generatePath` instead of pushing (appending) to the end of a url.
=> fix: removes duplicate redirect

src/components/course/data/utils.jsx, src/components/course/routes/CourseAbout.jsx, src/components/course/routes/tests/CourseAbout.test.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/tests/utils.test.js, src/components/enterprise-user-subsidy/enterprise-offers/data/utils.js, src/components/my-career/CategoryCard.jsx
Updates my favorite function, `isDisableCourseSearch`, to take into account existing coupon codes before redirecting. If there exists an available coupon code, then we will not redirect away from the course about page.
We also refactor the `isDisableCourseSearch` to return out of the function as false (can view the course page) in the following order.
- If a `nonAssignablePolicyType` exist where a `nonAssignablePolicyType` is not 'AssignedLearnerCreditAccessPolicy'
- If a user `hasActiveSubPlan` where a subscription plan is active AND the subscription license status is 'activated'
- If a user `hasCouponCodes` where a coupon code is available (active defined as the current date/time falls between a coupon start/end date)
- If a user does NOT have a `allocatedOrAcceptedAssignment` where an …
=> fix: update redirect logic to take into account available coupon codes

package-lock.json, package.json, src/components/course/course-header/data/hooks/tests/useCourseRunCardHeading.test.jsx, src/components/course/course-header/data/hooks/useCourseRunCardHeading.js, src/components/course/course-header/data/utils.js, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx, src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/data/utils.js, src/components/executive-education-2u/UserEnrollmentForm.jsx, src/components/executive-education-2u/UserEnrollmentForm.test.jsx, src/utils/dayjs.js
**Tickets:**
* https://2u-internal.atlassian.net/browse/ENT-8147
* https://2u-internal.atlassian.net/browse/ENT-8149
When learner has a canceled assignment for the course being viewed in the learner portal, there is "Assigned" messaging as if the assignment is applicable to the course. This PR ensures canceled assignments are ignored on the course page.
=> fix: ensure isAssignmentExpired is accurate and ignore canceled assignments on course page

src/components/my-career/VisualizeCareer.jsx, src/components/skills-quiz/SkillsQuizStepper.jsx, src/components/skills-quiz/data/utils.jsx
- When the user fills out the Skills Builder, we take the first job from their list of up to three jobs they are interested in and write it to their career chart.
- If the user selects they want to improve in their current role, we write from the current job field.
- On the UI of the career chart, change the Current Role field name to Desired Role.
=> feat: update career chart to pull interested role not current role

src/components/course/data/hooks.jsx, src/components/dashboard/data/utils.js, src/components/dashboard/main-content/course-enrollments/CourseAssignmentAlert.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/AssignedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js
Updates instances of 'cancelled' to 'canceled'
Cool regex used `(["'].*?)?[Cc]ancell?ed`
=> fix: correct spelling of canceled

src/components/dashboard/data/constants.js, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/CourseSection.jsx, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx
=> feat: ENT-7851 Added course section title for learners's first visit

src/components/academies/AcademyDetailPage.jsx, src/components/academies/CourseCard.jsx, src/components/academies/styles/Academy.scss, src/index.scss
=> feat: ENT-8192 Academy tags connected to Algolia search

src/components/dashboard/DashboardPage.jsx, src/components/my-career/VisualizeCareer.jsx
Replaces the `username` argument passed to the `enterpriseUuid` and correctly places the event name in the correct sequence within `sendEnterpriseTrackEvent` function to align with the `eventName` parameter
=> fix: updates track event parameters

src/components/academies/AcademyContentCard.jsx, src/components/academies/AcademyDetailPage.jsx, src/components/academies/styles/Academy.scss, src/components/academies/tests/AcademyDetailPage.test.jsx
- if the content section in an academy is empty then hide that section.
- Add `clear tag filter` CTA to remove the selected tag on the Academy page
=> feat: hide academy content section if empty

src/components/enterprise-page/data/hooks.js, src/components/search/Search.jsx
__Jira Ticket:__ [ENT-8331](https://2u-internal.atlassian.net/browse/ENT-8331)
Show academies only to those learners whose enterprise has enabled academies. This is to speed up page load and also avoid showing network errors for learners who do not have any academies.
__Blockers:__
This ticket depends on `enable_academies` flag that is added in https://github.com/openedx/edx-enterprise/pull/2007. We would only be able to merge once those changes are deployed.
=> ENT-8331: Only show academies if the learner's enterprise has enabled them.

src/components/course/course-header/data/hooks/useCourseRunCardAction.jsx, src/components/dashboard/data/utils.js, src/components/dashboard/main-content/course-enrollments/CourseAssignmentAlert.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/data/constants.js, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/service.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx, src/components/dashboard/main-content/course-enrollments/data/tests/service.test.js, src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/data/utils.js, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx, src/components/enterprise-subsidy-requests/data/service.js, src/components/enterprise-subsidy-requests/data/tests/service.test.js, src/components/enterprise-user-subsidy/data/constants.js, src/components/enterprise-user-subsidy/data/hooks/hooks.js, src/components/enterprise-user-subsidy/data/hooks/hooks.test.jsx, src/components/enterprise-user-subsidy/data/utils.js, src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js, src/setupTest.js
Ticket: https://2u-internal.atlassian.net/browse/ENT-8162
Related PR: https://github.com/openedx/enterprise-access/pull/390
* Updates the Dashboard page route to handle/display assignments in the `expired` state.
* Instead of relying on a naive `localStorage` solution for keeping track of dismissed/acknowledged cancelled/expired assignments to prevent them from re-appearing on the dashboard, the dismiss alerts make a POST API call to `acknowledge-assignments` with specified assignment uuids to acknowledge. By acknowledging them through the API, already acknowledged cancelled/expired assignments will be excluded from the list of assignments returned by `credits_available` such that invalidating the query cache for the `credits_available` query will force a re-fetch and remove the …
=> feat: rely on API to determine expired state and acknowledge assignments

package-lock.json, package.json
Bumping packages version for the work related to prequery search results in this PR https://github.com/openedx/frontend-enterprise/pull/371 
- `frontend-enterprise` version bump https://github.com/openedx/frontend-enterprise/pull/372
=> chore: update node packages for prequery search

src/components/dashboard/main-content/course-enrollments/data/hooks.js
Instead of using `logInfo` (requires NRQL), opts to utilize `logError` in order to have a bit more proactive observability through New Relic errors into when / how often learners "button-smash" the assignment expired/canceled alert "Dismiss" buttons while an `acknowledge-assignments` POST request is already underway (note: it does prevent duplicate requests), given there is no asynchronous loading feedback on this action.
=> fix: switch to logError in order to alert on button smashing during asynchronous acknowledgement

README.md, package.json, webpack.prod.config.js
Ticket: https://2u-internal.atlassian.net/browse/ENT-8372
Introduces the ability to serve production Webpack builds via a Node.js server (Express) shipped from `@edx/frontend-build`. Running `npm run start` does not adequately do code splitting as it would in a production environment, hence the desire/need for `npm run build:serve`.
=> build: introduce serve command into NPM scripts

src/components/dashboard/main-content/course-enrollments/data/hooks.js
Based on local error I was facing when default enterprise provisioned with no learner credit.
=> fix: early return added on hook

src/components/dashboard/DashboardPage.jsx, src/components/dashboard/data/constants.js, src/components/dashboard/data/useDashboardTabs.jsx, src/components/dashboard/tests/DashboardPage.test.jsx
Updates the logic for the dashboard tab components to conditionally render the children of each tab and abstract the logic into an independent hook.
=> fix: Tabs conditionally render child components and refactor

src/components/dashboard/DashboardPage.jsx, src/components/dashboard/data/constants.js, src/components/dashboard/data/useDashboardTabs.jsx, src/components/dashboard/tests/DashboardPage.test.jsx, src/components/my-career/MyCareerTab.jsx, src/components/my-career/MyCareerTabSkeleton.jsx, src/components/my-career/data/hooks.jsx, src/components/pathway-progress/PathwayProgressListingPage.jsx, src/components/program-progress/ProgramListingPage.jsx, src/components/program-progress/tests/ProgramListingPage.test.jsx
Add tests relating to a related PRs code changes to uphold repository testing coverage.
Adds prefetching on hover of the My Career tab.
Adds Skeleton state for the My Career tab while prefetching
=> feat: improve codecov around dashboard tab changes and adds prefetching

src/components/course/course-header/CoursePreview.jsx, src/components/video/VideoPlayer.jsx, src/components/video/tests/VideoPlayer.test.jsx
Defer importing `VideoJS` component only when a video is being played. This results in pages that don't have a video to not have to import `video.js` and other associated imports at all.
Example of deferred loading:
https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/82611798/ce71ef33-18d7-4201-952c-2f4b8310faa2
=> feat: defer importing videojs only on video play

src/components/app/routes/loaders/rootLoader.js, src/components/site-header/SiteHeaderNavMenu.jsx, src/utils/common.js
Catches errors around the `rootLoader` loader. The rootLoader will throw an error if the returned services are undefined.
=> feat: Catch errors around root loader

src/components/app/App.jsx, src/components/app/routes/loaders/courseLoader.js, src/components/app/routes/loaders/dashboardLoader.js, src/components/app/routes/loaders/rootLoader.js, src/components/app/routes/loaders/updateActiveEnterpriseCustomerUserLoader.js
Resolves all primary data thus far in route loaders **before** the page changes in the UI, with feedback in the form of the progress bar at the top of the page (fairly common loading pattern across the web; relies on popular `nprogress` NPM package.
As a result, we can effectively remove all spinners from the experience and ensure all queries are stored in the client-side query cache to return fresh data instantly and only refetch API calls when they are stale or get invalidated.
https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/2828721/a42f0bb6-c940-4e39-8940-0f433aa09d35
=> feat: resolve all data during route transitions

src/components/app/App.jsx, src/components/app/routes/loaders/courseLoader.js, src/components/app/routes/loaders/dashboardLoader.js, src/components/app/routes/loaders/rootLoader.js, src/components/app/routes/loaders/updateActiveEnterpriseCustomerUserLoader.js, src/components/enterprise-banner/EnterpriseBanner.jsx, src/components/site-header/AvatarDropdown.jsx, src/components/site-header/SiteHeader.jsx, src/components/site-header/SiteHeaderLogos.jsx, src/components/site-header/SiteHeaderNavMenu.jsx
* Switches from `queryClient.fetchQuery` to `queryClient.ensureQueryData` ([docs](https://tanstack.com/query/latest/docs/reference/QueryClient#queryclientensurequerydata)).
> `ensureQueryData` is an asynchronous function that can be used to get an existing query's cached data. If the query does not exist, `queryClient.fetchQuery` will be called and its results returned.
* Resolves [ENT-8474](https://2u-internal.atlassian.net/browse/ENT-8474), ensuring data for the currently viewed enterprise customer does not change when the user's active enterprise customer user changes external to a session (e.g., viewing Admin/Learner Portal for a different customer and coming back to the same Learner Portal window/tab for the original customer).
Note: failing CI is OK right now.
=> fix: handle when active enterprise is changed external to current page view

src/styles/nprogress.scss
Updates the `nprogress` loader progress bar to use `$brand-500` (instead of `$primary-500`) and makes it slightly taller with `3px` height:
https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/2828721/c6975dfd-baa7-4637-bd90-f43b3f9f5821
=> fix: update nprogress color and height styles

src/components/dashboard/DashboardPage.jsx, src/components/enterprise-user-subsidy/AutoActivateLicense.jsx, src/components/enterprise-user-subsidy/data/hooks/hooks.js, src/components/enterprise-user-subsidy/tests/AutoActivateLicense.test.jsx, src/components/license-activation/LicenseActivation.jsx
https://2u-internal.atlassian.net/browse/ENT-8554
Resolves a infinite redirect bug where the license activation route was effectively redirecting to itself. Not quite sure why this suddenly started appearing, but also deferring on figuring that out, given these related code paths will be refactored with the route loader frontend performance work anyways.
=> fix: dont redirect to activation page user is already on

src/components/app/App.jsx, src/components/app/Root.jsx, src/components/app/Root.test.jsx, src/components/app/data/hooks/index.js, src/components/app/data/hooks/useNProgressLoader.js, src/components/app/data/hooks/useNProgressLoader.test.jsx, src/components/app/data/hooks/useNotices.js, src/components/app/data/hooks/useNotices.test.jsx, src/components/app/routes/RouterFallback.jsx, src/components/app/routes/RouterFallback.test.jsx, src/components/app/routes/data/services.js, src/components/app/routes/data/tests/services.test.js, src/components/app/routes/index.js
=> fix: resolve blip of UI before notices redirect, refactor NProgress loader

src/components/app/data/queries/extractEnterpriseId.js, src/components/app/data/queries/queries.js, src/components/app/data/services/enterpriseCustomerUser.js, src/components/app/data/services/enterpriseCustomerUser.test.js, src/components/app/data/services/subsidies/subscriptions.js, src/components/app/data/services/subsidies/subscriptions.test.js, src/components/app/data/utils.js, src/components/app/routes/data/utils.js, src/components/app/routes/data/utils.test.js, src/components/app/routes/loaders/rootLoader.js, src/components/app/routes/loaders/tests/rootLoader.test.jsx, src/types.d.ts
https://2u-internal.atlassian.net/browse/ENT-8597
Currently, on `master`, authenticated staff users can view the learner portal for enterprise customers they are not explicitly linked to. This partial masquerading is occasionally used to QA customer issues (e.g., verify expected content is returning in Algolia) and most staff assume to be able to access customer portals, similar to Admin Portal.
By removing `enterprise-customer` API call to solely rely on `enterprise-learner`, we effectively removed the ability for staff users to view the learner portal for enterprise customers they are not explicitly linked to.
This PR brings back that expected functionality by only relying on `enterprise-customer` API if the user is staff, an enterprise slug is specified in the route URL, and the user …
=> fix: ensure staff users can view unlinked customer portals

src/components/course/CoursePage.jsx, src/components/course/data/service.js, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx, src/config/constants.js
Note: When the "course_run_key" query parameter is supplied with a
qualifying "late" run, the query parameter will behave the way you would
expect: it would show just the requested course run.
Testing table
===
Assume there are three course runs:
* A: enrollment ended more than 60 days ago.
* B: enrollment ended less than 60 days ago.
* C: enrollment is currently open.
```
+----------------------+----------------+-------------+
| any policy with late | course_run_key | course runs |
| redemption enabled   | query param    | displayed   |
+----------------------+----------------+-------------+
| no                   | not supplied   | [C]         |
+----------------------+----------------+-------------+
| no                   | A              | [C]         | …
```
=> feat: display extra course runs when policy allows late redemption

src/components/app/routes/createAppRouter.jsx, src/components/my-career/tests/SkillsRecommendationCourses.test.jsx, src/components/pathway/tests/PathwayModal.test.jsx, src/components/search/content-highlights/tests/ContentHighlightSet.test.jsx, src/components/search/content-highlights/tests/ContentHighlights.test.jsx, src/components/search/content-highlights/tests/HighlightedContentCard.test.jsx, src/components/search/data/hooks/useDefaultSearchFilters.test.js, src/components/search/data/hooks/useSearchCatalogs.test.js, src/components/search/tests/SearchCourseCard.test.jsx, src/components/search/tests/SearchResults.test.jsx, src/components/search/tests/SearchSections.test.jsx, src/components/skills-quiz-v2/tests/SkillsQuiz.test.jsx, src/components/skills-quiz-v2/tests/SkillsQuizForm.test.jsx, src/components/skills-quiz/GoalDropdown.jsx, src/components/skills-quiz/tests/SearchCourseCard.test.jsx, src/components/skills-quiz/tests/SearchCurrentJobCard.test.jsx, src/components/skills-quiz/tests/SearchFilters.test.jsx, src/components/skills-quiz/tests/SearchJobCard.test.jsx, src/components/skills-quiz/tests/SearchPathways.test.jsx, src/components/skills-quiz/tests/SearchProgramCard.test.jsx, src/components/skills-quiz/tests/SelectJobCard.test.jsx, src/components/skills-quiz/tests/SkillsCourses.test.jsx, src/components/skills-quiz/tests/SkillsQuiz.test.jsx, src/components/skills-quiz/tests/SkillsQuizPage.test.jsx, src/components/skills-quiz/tests/SkillsQuizStepper.test.jsx, src/utils/tests.jsx
Reintegrates the skills quiz page to the router.
Update tests to use `useQuery` as the source of data and remove context references within the tests.
=> feat: reintegrate the skills quiz page

src/components/program-progress/ProgramProgressSidebar.jsx, src/components/program-progress/tests/ProgramProgressSidebar.test.jsx
Adds the correct prefix for viewing certificates from a route on the learner portal to the LMS.
=> fix: Update program certificate url

src/index.scss
The webpack's tilde syntax resolves SCSS imports from node_modules to make the development easier.
=> feat: add footer SCSS import and use tilde for module resolution

src/components/course/CourseMaterialsButton.jsx, src/components/course/course-header/CourseRunCard.jsx, src/components/course/enrollment/components/ToCoursewarePage.jsx
https://2u-internal.atlassian.net/browse/ENT-8730
Resolves the "View course" CTA not being a link to courseware: 
Note: At the moment, CI is expected to fail.
=> fix: resolve "View course" CTA link location on course page

src/components/dashboard/tests/DashboardPage.test.jsx, src/components/program-progress/ProgramListingCard.jsx, src/components/program-progress/tests/ProgramListingPage.test.jsx, src/components/program/ProgramCTA.jsx
Previously, if a course was not associated with a catalog but appeared in a program, in the `Enrolling Now` dropdown, the course was clickable but did not redirect anywhere (non interactive button).
We now disable the clickability of the dropdown item by disabling them. This disabled dropdown items only correspond to courses not in the customer catalog. 
Before:
Updated:
The disabled buttons now appeared greyed out and non clickable.
=> fix: disables courses dropdown item not associated with catalog for programs

src/components/app/App.jsx
https://2u-internal.atlassian.net/browse/ENT-8739
When a rendered `useQuery`'s query key changes (e.g., due to a dependent query's automatic background re-fetch returning updated data used as input to another query's `queryKey`), a hard loading state is triggered since the query is new and no existing data is present in the query cache.
In the new routing/data paradigm, UI components generally should assume API data is already resolved (i.e., loading states should generally not need to be considered within UI components). However, if a rendered query observer's `queryKey` changes due to a background re-fetch of a dependent query, this assumption results in trying to access properties on `data`, which changed to `undefined` due to an updated `queryKey`, throwing JS errors in a handful of …
=> fix: enable keepPreviousData for all queries by default

src/components/site-header/AvatarDropdown.jsx
Error triggered when linked to customers that do not have the Learner Portal enabled. Potentially impacting more staff than myself.
=> fix: null enterprise customer bug in AvatarDropdown

src/components/course/CourseReview.jsx, src/components/search/SearchAcademy.jsx
- Changed semi-colon to colon in Academies content section header on /search
- Add comma to enrollment number on Course About Page
Jira -> [ENT-8650](https://2u-internal.atlassian.net/browse/ENT-8650) and [ENT-8467](https://2u-internal.atlassian.net/browse/ENT-8467)
=> fix: made some minor text changes

src/config/constants.js
This keeps the learner portal in sync with the corresponding buffer days behind the GEAG endpoint. If they didn't match, certain course runs would be visible but not enrollable.
=> chore: update late enrollment buffer days to 30

src/components/program/ProgramPage.jsx
During QA of the performance implementation, a [New Relic error](https://onenr.io/0VRV3lXevja) directed us to an instance where the `useProgramDetails` hook would return null, but an object was still being referenced even if the object was undefined. This PR aims to put an additional check on the program details object to return a `NotFoundError` component.
=> fix: cannot read property 'catalogContentProgram' of null fix

src/components/app/App.jsx, src/components/app/Root.jsx, src/components/app/routes/AppSuspenseFallback.jsx, src/components/app/routes/index.js
https://2u-internal.atlassian.net/browse/ENT-8604
To simulate React Query's garbage collection after the default 5 minutes for inactive queries, you can use the React Query Devtools to "reset" a query (simulates garbage collection). Previously, resetting a query would trigger JS errors as its consuming UI components/hooks assume the data exists when it no longer does due to React Query's garbage collection.
With `suspense: true` and a wrapping `Suspense` with a fallback integrated with the NProgress global progress loader bar, we can now catch these garbage collected queries to "suspend" with the global loading state while the garbage collected queries are re-fetched.
https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/2828721/667d4c5a-4198-482f-aeed-00846a52ba42
=> feat: enable suspense for React Query and wrap RouterProvider with Suspense

src/components/app/App.jsx, src/components/enterprise-banner/EnterpriseBanner.jsx, src/components/enterprise-banner/tests/EnterpriseBanner.test.jsx
* Extends default garbage collection time from 5 minutes to 30 minutes. 30 minutes is roughly the 75th percentile of session duration for the last 5000 sessions in the Learner Portal.
* Replaces `useEnterpriseLearner` with `useEnterpriseCustomer`.
=> fix: extend default garbage collection time (`cacheTime`) to 30 minutes

src/components/app/routes/RouteErrorBoundary.jsx, src/components/app/routes/RouteErrorBoundary.test.jsx
If users have the app loaded in their browser when a new production deployment is released and then try navigating to a new page route, due to the code splitting by route for frontend performance reasons, a JS `ChunkLoadError` is thrown because the browser is trying to download a file chunk that no longer exists in the S3 bucket due to the new deployment (i.e., all previous chunks were removed from S3).
At least in the short term, we will catch `ChunkLoadError` and gracefully handle it by displaying a blocking `AlertModal`, encouraging users to refresh the page to leverage latest features/improvements. Long term, we may explore a more infrastructure related fix such as keeping files from previous deployments around longer.
https://github.com/openedx/frontend-app-learner-portal-enterprise/a …
=> feat: gracefully handle ChunkLoadError and stop logging it as an error

src/components/app/data/queries/extractEnterpriseCustomer.js, src/components/app/data/queries/index.js, src/components/app/routes/loaders/tests/enterpriseInviteLoader.test.jsx, src/components/app/routes/loaders/tests/rootLoader.test.jsx, src/components/course/data/courseLoader.js, src/components/course/data/courseLoader.test.jsx, src/components/course/routes/externalCourseEnrollmentLoader.js, src/components/dashboard/data/dashboardLoader.js, src/components/dashboard/data/dashboardLoader.test.jsx, src/components/program/data/programLoader.js, src/components/program/data/programLoader.test.js, src/components/search/data/searchLoader.js
To have access to enterprise customer metadata within route loaders, refactors `extractEnterpriseId` to `extractEnterpriseCustomer` instead.
=> refactor: extractEnterpriseId to extractEnterpriseCustomer

src/components/app/data/hooks/useEnterpriseFeatures.js, src/components/search/Search.jsx
Currently, `enterpriseFeatures?.featurePrequerySearchSuggestions` returns `undefined`. To fix this, we need to update the return of `useEnterpriseFeatures` to `data.enterpriseFeatures](select: (data) => data.enterpriseFeatures)`
https://2u-internal.atlassian.net/browse/ENT-8790
=> fix: update variable destructuring for enterprise features

src/components/course/data/hooks.jsx, src/components/course/routes/ExternalCourseEnrollment.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx
Prior to this fix, the course info displayed at the top of the page (including start date) would correspond to the *advertised* run for the given course, even if the URL contains a non-advertised run.
Now, the info displayed should always correspond to the run specified in the URL.
ENT-8780
=> fix: ExternalCourseEnrollment displays correct run info

src/components/course/data/hooks.jsx
This typo was missed in part due to not being able to unit test query select callback functions.
=> fix: use the selected course run to determine start date

src/components/course/data/hooks.jsx
The only consumer of this hook is currently external enrollment pages, and those actually need the metadata from the requested course run without hiding "unavailable" ones, due to the nature of this particular route being used for late enrollment.
ENT-8780
=> fix: useMinimalCourseMetadata - search for run among ALL runs

src/components/course/course-header/data/hooks/useCourseRunCardHeading.js, src/components/course/course-header/deprecated/CourseRunCard.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx
This results in reading course start dates from the run metadata instead of `additional_metadata` when evaluating Exec Ed runs.
In prod, this should be a no-op because the `start_date` key inside `additional_metadata` is exactly the same as the value of `start` for all 220 Exec Ed runs.
ENT-8780
Companion PR: https://github.com/edx/edx-internal/pull/10640
Testing performed
===
I was able to at least confirm that when I hooked up my local MFE to stage data, the one Exec Ed course still works:
```
https://localhost.stage.edx.org:8734/troy-test-5/executive-education-2u/course/OxfordX+LSC/enroll/course-v1:OxfordX+LSC+1T2024
```
=> fix: remove all remaining usages of additional_metadata

src/components/academies/AcademyContentCard.jsx, src/components/academies/AcademyDetailPage.jsx, src/components/academies/PathwaysSection.jsx, src/components/academies/styles/Academy.scss, src/components/academies/tests/AcademyDetailPage.test.jsx
https://2u-internal.atlassian.net/browse/ENT-8680
Style and text changes on the academy detail page as per [figma](https://www.figma.com/file/Ht9ykk12r2ZcvXjZk69pcr/Pathways-for-Academies?type=design&node-id=383-67713&mode=design&t=I6cQuEpd34GOvfH7-0)
The new pathway section hasn't been integrated yet because it will be integrated as part of [ENT-8678](https://2u-internal.atlassian.net/browse/ENT-8678)
https://github.com/openedx/frontend-app-learner-portal-enterprise/assets/113524403/3ed90871-83c0-48bb-95fa-3fe6dc144046
=> [ENT-8680]: style and text changes on the academy detail page

src/components/app/data/hooks/useContentHighlightSets.test.jsx, src/components/app/data/hooks/useContentHighlightsConfiguration.test.jsx, src/components/app/data/hooks/useCouponCodes.test.jsx, src/components/app/data/hooks/useCourseMetadata.test.jsx, src/components/app/data/hooks/useCourseRecommendations.test.jsx, src/components/app/data/hooks/useCourseReviews.test.jsx, src/components/app/data/hooks/useEnterpriseCustomer.test.jsx, src/components/app/data/hooks/useEnterpriseCustomerContainsContent.test.jsx, src/components/app/data/hooks/useEnterpriseFeatures.test.jsx, src/components/app/data/hooks/useEnterpriseLearner.test.jsx, src/components/app/data/hooks/useEnterpriseOffers.test.jsx, src/components/app/data/hooks/useEnterprisePathwaysList.test.jsx, src/components/app/data/hooks/useEnterpriseProgramsList.test.jsx, src/components/app/data/hooks/useLearnerPathwayProgressData.test.jsx, src/components/app/data/hooks/useLearnerProgramProgressData.test.jsx, src/components/app/data/hooks/useLearnerSkillLevels.test.jsx, src/components/app/data/hooks/useProgramDetails.test.jsx, src/components/app/data/hooks/useRedeemablePolicies.test.jsx, src/components/app/data/hooks/useSubscriptions.test.jsx, src/components/app/data/hooks/useUserEntitlements.test.jsx
Adds the following tests to improve code coverage, follow up to previous code coverage PR https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1055:
useContentHighlightSets
useCouponCodes
useCourseMetadata
useCourseRecommendations
useCourseReviews
useEnterpriseCustomerContainsContent
useEnterpriseLearner
useEnterpriseCustomer
useEnterpriseFeatures
useEnterpriseOffers
useEnterprisePathwaysList
useEnterpriseProgramsList
useLearnerPathwayProgressData
useLearnerProgramProgressData
useProgramDetails
useLearnerSkillLevels
useRedeemablePolicies
useSubscriptions
useUserEntitlements
useCanOnlyViewHighlights
=> feat: Improve code coverage 2

src/components/academies/GoToAcademy.jsx, src/components/app/data/hooks/useRecommendCoursesForMe.js, src/components/app/data/hooks/useRecommendCoursesForMe.test.jsx, src/components/app/data/services/data/__factories__/academies.factory.js, src/components/app/data/services/data/__factories__/enterpriseCustomerUser.factory.js, src/components/app/data/services/data/__factories__/index.js, src/components/dashboard/main-content/DashboardMainContent.test.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollmentsEmptyState.jsx, src/components/dashboard/tests/DashboardPage.test.jsx, src/components/search/data/searchLoader.js, src/components/search/data/searchLoader.test.jsx, src/components/site-header/SiteHeaderNavMenu.jsx, src/components/site-header/data/hooks/index.js, src/components/site-header/data/hooks/useContentDiscoveryNavLink.jsx, src/components/site-header/data/index.js, src/components/site-header/tests/SiteHeader.test.jsx
__Jira Ticket:__ [ENT-8621]()
We anticipate some customers are going to want to purchase only one Academy and the content associated with it. In that case, the Academy detail page becomes a sufficient (and better) alternative to the search page.
**Acceptance Criteria:**
1. SearchPage is replaced with a new component `RedirectToAcademy`
2. "Skills Quiz" CTA is removed.
3. "Find a course" is replaced with "Go to Academy"
1. Screenshot of the dashboard page.
2. Screenshots for error scenarios
=> ENT-8621: Replace /Search with One Academy

.github/workflows/ci.yml, .github/workflows/coverage.yml
Based on #1069, we were able to manually run the `ci.yml` workflow on `master` and successfully saw a coverage report generated and uploaded for most recent merged commit in CodeCov (rather than the previous stale 11 month old commit).
We then attempted to merge another commit to see if the new commit appears in CodeCov via #1070, without luck.
The next step will be to always upload coverage reports to CodeCov on commits to `master` similar to the previous manual run of the `ci.yml` file.
Instead of running `ci.yml` for commits to `master`, I've opted to create a new GitHub Action workflow file (`coverage.yml`) solely responsible for the running of CodeCov on `master`. It does NOT do the `npm run lint` or `npm run build` steps in `ci.yml` since they are not relevant to generating coverage …
=> build: add new coverage.yml workflow github action

src/components/course/routes/ExternalCourseEnrollment.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx
BEFORE this commit: It's possible (and easy) in some cases for a learner to enroll in a course even if late enrollment feature is disabled on the policy.
The exact conditions which allow this bug to manifest:
* The current date is within 30 days after the enrollment deadline of a course run.
* The learner has been given a link to a ExternalCourseEnrollment page (i.e. T's&C's page) for that course run.
* The policy late enrollment is disabled (including cases where late enrollment was enabled, then self-expired).
AFTER this commit: The ExternalCourseEnrollment page (i.e. T's&C's page) will render a 404 page in the above case.
Side effects:
* Now, this view also returns 404 *ANY* time the requested course run is non-redeemable according to can-redeem, or the course run is "unavailable" due …
=> fix: block learners from accessing ExternalCourseEnrollment outside enrollment window

Makefile
__Jira Ticket:__ [ENT-8994](https://2u-internal.atlassian.net/browse/ENT-8994)
This PR enabled translations for the search header component in enterprise learner portal.
**Screenshot:**
=> feat: Added i18n for search header component.

src/components/executive-education-2u/UserEnrollmentForm.jsx
Ticket
https://2u-internal.atlassian.net/browse/ENT-9016
=> [ENT-9016] Added data sharing consent link on exec-ed course enrollment page

src/components/course/routes/ExternalCourseEnrollment.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx
Instead of throwing a JS error, return a 404 page when there are absolutely no applicable subsidies for a given course.
=> feat: ExternalCourseEnrollment page - handle no applicable subsidies

src/components/dashboard/sidebar/SupportInformation.jsx
=> refactor: renamed `careerEngagementNetworkMessage` field

src/components/academies/GoToAcademy.jsx, src/components/dashboard/sidebar/SubsidiesSummary.jsx, src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx, src/components/program-progress/tests/ProgramProgressPage.test.jsx
1. On the learner home page, one of the buttons still says “Find a course” (the one in the subsidy boxes). Change this to “Go to Academy” to match the other buttons.
2. The text on the Learner Dashboard says 'Getting started with edX is easy. Simply find a course from your Academy, request enrollment, and get started on your learning journey'. Remove 'request enrollment,' so this language is not tied to a specific access model (browse and request).
=> fix: UI/UX cleanups for one academy use case

src/components/app/data/constants.js, src/components/app/data/services/contentHighlights.js, src/components/app/data/services/contentHighlights.test.js
Now that I've made the change allowing for a specified page size to be passed in, we are now only making one call to enterprise catalog. There is a limit on highlights to be 12 in admin portal, so it won't be more than that anyway. 
Testing: I created 12 highlights on `https://localhost.stage.edx.org:8734/hooli/search`
[Jira ticket 
](https://2u-internal.atlassian.net/browse/ENT-9210)
=> fix: bug fix to allow for only one highlight call

src/components/app/data/hooks/useCanUpgradeWithLearnerCredit.js, src/components/app/data/hooks/useCanUpgradeWithLearnerCredit.test.jsx, src/components/app/data/queries/queries.js, src/components/app/data/services/course.js, src/components/app/data/services/course.test.js, src/components/app/data/utils.js, src/components/course/EnrollModal.jsx, src/components/course/tests/EnrollModal.test.jsx, src/components/dashboard/main-content/course-enrollments/CourseSection.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/ContinueLearningButton.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/UpgradeCourseButton.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/InProgressCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx
Ticket: [ENT-9066](https://2u-internal.atlassian.net/browse/ENT-9066) (part 1)
[Figma](https://www.figma.com/design/gbMBXoSZRXKk6ExOPGqjOH/Audit-to-Verified-LC?node-id=81-5145&m=dev)
tl;dr; Some clean up on existing logic; display "Upgrade" CTA when audit enrollment is upgradeable via Learner Credit; update `EnrollModal` with Learner Credit audit upgrade confirmation messaging.
* Updates to `useCanUpgradeWithLearnerCredit`
* No longer relies on `isPolicyRedemptionEnabled` util function as it returns true when the course enrollment is associated with a prior successful redemption, whereby the `redeemableSubsidyAccessPolicy` is not returned when `hasSuccessfulRedemption: true` (i.e., no access to `redeemableSubsidyAccessPolicy.policyRedemptionUrl` to use during upgrade).
* TODO: file ticket …
=> feat: account for learner credit audit upgrade modal UI

src/components/app/data/services/subsidies/subscriptions.js, src/components/app/data/services/subsidies/subscriptions.test.js
Fix the `activateOrAutoApplySubscriptionLicense()` function so that it doesn't early-return when there is no subscription license present (which is actually the *expected* case during the auto-apply flow), but *does* early return if there is no current subscription plan associated with the present customer agreement record.
ENT-9221
Local success (after fixing devstack CSRF_TRUSTED_ORIGINS in license-manager):
https://github.com/user-attachments/assets/5b4885b8-6ccf-4d4e-9aac-59df077d0df9
=> fix: fix auto-applied license flow

src/components/course/EnrollModal.jsx, src/components/dashboard/sidebar/SubsidiesSummary.jsx
A recently merged refactor caused the JavaScript event variable `e` to no longer be passed through to the `analyticsHandler` and `optimizelyHandler` functions returned by `useTrackSearchConversionClickHandler` and `useOptimizelyEnrollmentClickHandler`. Those handler functions assume `e` will exist, but seems to have thrown at least 1 error where `e` was `undefined`.
`EnrollModal` defines a ` handleEnroll` function that calls the specified `onEnroll` function passed via props when the confirmation CTA is clicked. However, the JavaScript event associated with this click is now getting lost in certain code paths as a result.
This PR ensures the JavaScript event `e` associated with the click of the confirmation button in `EnrollModal` is passed to the given `onEnroll`.
For a customer with …
=> fix: ensure event is passed through to onEnroll prop in EnrollModal

src/components/microlearning/VideoDetailPage.jsx, src/components/microlearning/tests/VideoDetailPage.test.jsx
Removed the feature flag check from the video detail page, as it has already been applied on the video card that redirects to this page.
=> [ENT-8962] fix: removed feature flag check from video detail page

src/components/app/data/utils.js, src/components/app/data/utils.test.js
=> fix: late enrollment should be less sensitive to courserun state

src/components/app/data/hooks/useLateEnrollmentBufferDays.test.jsx, src/components/app/data/utils.js
Renames:
`isLateRedemptionEnabled` -> `isLateRedemptionAllowed`
I can't quite fathom how this was wrong, but it's [abundantly clear in the API serializer](https://github.com/openedx/enterprise-access/blob/5461be33217cfe873c4db705b271e97edea5b41c/enterprise_access/apps/api/serializers/subsidy_access_policy.py#L192) that the correct value should be `isLateRedemptionAllowed`.
ENT-9259
=> fix: use correct late redemption enablement key

src/components/app/data/hooks/index.js, src/components/app/data/hooks/useVideoCourseMetadata.js, src/components/app/data/hooks/useVideoCourseMetadata.test.jsx, src/components/app/data/hooks/useVideoCourseReviews.js, src/components/app/data/hooks/useVideoCourseReviews.test.jsx, src/components/app/data/services/videos.test.js, src/components/microlearning/VideoCourseReview.jsx, src/components/microlearning/VideoDetailPage.jsx, src/components/microlearning/data/utils.js, src/components/microlearning/data/utils.test.js, src/components/microlearning/styles/VideoDetailPage.scss, src/components/microlearning/tests/VideoDetailPage.test.jsx
I added a course detail section to the video detail page.
=> feat: add course section on video detail page

src/components/microlearning/VideoDetailPage.jsx, src/components/video/VideoJS.jsx, src/components/video/VideoPlayer.jsx, src/components/video/data/hooks.js, src/components/video/data/index.js, src/components/video/data/service.js, src/components/video/data/tests/hooks.test.js, src/components/video/data/tests/service.test.js, src/components/video/tests/VideoJS.test.jsx, src/components/video/tests/VideoPlayer.test.jsx
On stage/production (and seemingly locally on some machines), the "AD" transcripts button, added via `vjstranscribe` plugin for `video.js`, does not consistently appear, preventing users from using the transcript feature as expected.
This PR ensures the "AD" transcripts button always appears, using the out-of-the-box plugin by fetching the asynchronous transcripts data prior to initializing the player with `videojs(...)`:
https://github.com/user-attachments/assets/10e6afd4-21ea-4f52-a592-b7a49dbf9981
=> fix: ensure transcript button appears in video player

src/components/app/data/utils.js, src/components/course/data/utils.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/CourseSection.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/UpgradeCourseButton.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx, src/components/dashboard/main-content/course-enrollments/data/utils.js
[ENT-9070](https://2u-internal.atlassian.net/browse/ENT-9070)
Ensures that when a learner has a (potentially) upgradeable course enrollment (i.e., audit mode and a not-yet-elapsed `enrollBy` timestamp) _and_ an assignment for the same top-level course associated with the existing upgradable enrollment, the assignment card is hidden in favor of encouraging the learner to upgrade their existing "audit" enrollment to "verified" with their assignment instead of navigating to the course about page to choose a (potentially different) course run.
In the below screenshot, my user is enrolled in the audit mode for a course run of "Intermediate Happiness", for which I also have an allocated assignment. Note the assignment card is _not_ displayed, giving priority to the upgrade/upsell messaging on …
=> fix: hide assignment card if existing in-progress enrollment card is upgradeable

src/components/microlearning/VideoDetailPage.jsx, src/components/microlearning/tests/VideoDetailPage.test.jsx, src/components/video/VideoPlayer.jsx
- Temporarily hide skills section because the skills that we are currently retrieving for videos are inaccurate.
- Turned off auto-play mode for videos.
- Added some nits.
=> Video Detail Page Updates

src/components/dashboard/main-content/course-enrollments/data/hooks.js
[ENT-9135](https://2u-internal.atlassian.net/browse/ENT-9135)
Removes the gating (i.e., staff user or feature flag enabled via query parameter) on the API call to `can-redeem` within potentially upgradeable audit course enrollments.
=> chore: remove gating on learner credit enrollment upgrades from Dashboard

package-lock.json, package.json, src/components/search/SearchPage.jsx, src/components/search/tests/SearchPage.test.jsx
**Ticket:**
[ENT-9290](https://2u-internal.atlassian.net/browse/ENT-9290
)
Made changes to show the videos section only to the enterprise learners who have an active subscription.
=> ENT-9290: Show the videos section only to the learners who have an active subscription

src/components/search/Search.jsx, src/components/search/SearchPage.jsx, src/components/search/tests/SearchPage.test.jsx, src/components/search/tests/utils.test.js, src/components/search/utils.js
**Ticket**
https://2u-internal.atlassian.net/browse/ENT-9290
Made changes to ensure the video section and video learning type are only visible to learners with an active subscription.
=> [ENT-9290] Hide video section on search page for learners with inactive subsbcription

src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx
=> fix: ensure email setting model functions as expected

src/components/video/VideoPlayer.jsx
**Ticket**
https://2u-internal.atlassian.net/browse/ENT-9343
Set autoplay to true for YouTube videos on the course about page (restoring previous behavior) and false for videos on the video detail page. This change resolves issues where video previews were breaking on the course about page.
=> [ENT-9343] Fix autoplay setting for YouTube videos on course previews

src/components/app/data/services/subsidies/subscriptions.js, src/components/app/data/services/subsidies/subscriptions.test.js
[(ENT-9373)](https://2u-internal.atlassian.net/browse/ENT-9373)
tl;dr; Some subscription licenses are getting treated as expired in the UX, even though they have activated license in a _current_ subscription plan:
Learners who have an activated subscription license at the time a subscription plan renewal was processed (i.e., where their activated license is copied to the renewal plan), end up incorrectly seeing their activated license as expired for the _current_ subscription plan.
In this case of a processed renewal for a learner who had an activated license, the `learner-licenses` API begins returning the activated renewal license first in the list of licenses tied to the authenticated learner. As a result, the `fetchSubscriptions` logic which parses the list of subscription licenses …
=> fix: sort licenses by whether they are current in ascending order before further processing

src/components/app/data/constants.js, src/components/app/data/hooks/useIsAssignmentsOnlyLearner.test.jsx, src/components/app/data/utils.js, src/components/app/data/utils.test.js, src/components/dashboard/main-content/course-enrollments/CourseAssignmentAlert.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/CourseSection.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/AssignedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx, src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx, src/components/enterprise-user-subsidy/enterprise-offers/data/constants.js
Adds support for the `parentContentKey` on assignment based dashboard course cards to use the `parentContentKey` field to generate the course enrollment link.
=> feat: Support course run based go to enrollment links

src/components/microlearning/VideoDetailPage.jsx, src/components/microlearning/tests/VideoDetailPage.test.jsx
This PR covers the following things
[ENT-9339](https://2u-internal.atlassian.net/browse/ENT-9339)
- Remove breadcrumbs. 
- Ensure there is Paragon spacer 4 (24 px) between header and video title.
[ENT-9340](https://2u-internal.atlassian.net/browse/ENT-9340)
-  Change the course info section links to open the course about page within the same window, instead of a new tab.
[ENT-9357](https://2u-internal.atlassian.net/browse/ENT-9357)
- Restrict the video detail page for learners who doesn't have active subscription
=> feat: implemented some pre release requirements on video detail page

src/components/course/course-header/tests/CoursePreview.test.jsx, src/components/microlearning/styles/VideoDetailPage.scss, src/components/video/VideoJS.jsx, src/components/video/data/hooks.js, src/components/video/data/tests/hooks.test.js, src/components/video/data/tests/utils.test.js, src/components/video/data/utils.js, src/components/video/tests/VideoJS.test.jsx, src/components/video/tests/VideoPlayer.test.jsx
**Tickets**
- [ENT-9342](https://2u-internal.atlassian.net/browse/ENT-9342)
- [ENT-9338](https://2u-internal.atlassian.net/browse/ENT-9338)
- Updated the videos to have a default transcript language that matches the browser's default.
- Fixed an issue where video player controls were missing for a specific video due to inconsistent size.
=> [ENT-9342, ENT-9338] Video transcript updates

src/components/video/data/tests/hooks.test.js, src/components/video/data/utils.js
**Ticket**
https://2u-internal.atlassian.net/browse/ENT-9342
Some language codes returned by `getLocale` include a hyphen, which may not match the codes in the text tracks.
To ensure proper matching, the hyphen is removed from the site language code if present.
=> [ENT-9342] handle site lang with region subtags in text track sorting

src/components/course/course-header/tests/CoursePreview.test.jsx, src/components/video/VideoJS.jsx, src/components/video/data/hooks.js, src/components/video/data/utils.js, src/components/video/tests/VideoJS.test.jsx, src/components/video/tests/VideoPlayer.test.jsx
**Ticket**
[ENT-9375](https://2u-internal.atlassian.net/browse/ENT-9375
)
- Resolved an issue where the "AD" button appeared but didn't work for some videos due to text tracks being lost after `@tanstack/react-query` performed background re-fetches.  When the player is re-initialized or its sources are updated due to re-fetching, it loses the text tracks that were previously added, so made changes to re-add text tracks after background re-fetches.
- Additionally, added some improvements for [ENT-9342](https://2u-internal.atlassian.net/browse/ENT-9342) by using the `getPrimaryLanguageSubtag` method from `edx-platform` to strip full language locales and fallback to English when tracks are unavailable in the site language.
=> [ENT-9375] Fix: "AD" button appears but doesn't work for some videos

src/components/video/VideoJS.jsx, src/components/video/tests/VideoJS.test.jsx
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-9376
Made changes to ensure that the video player does not re-render / restart when `@tanstack/react-query` performs background re-fetches on queries rendered within the video detail page.
**Screen Recording:**
https://github.com/user-attachments/assets/77656631-bdbd-46a7-bec4-7ed1f50d8cc8
=> [ENT-9376] Fix: Actively playing video restarts due to background query re-fetches

src/components/microlearning/BetaBadge.jsx, src/components/microlearning/VideoBanner.jsx, src/components/microlearning/VideoDetailPage.jsx, src/components/microlearning/styles/VideoDetailPage.scss, src/components/microlearning/tests/VideoBanner.test.jsx, src/components/microlearning/tests/VideoDetailPage.test.jsx, src/components/search/Search.jsx, src/components/search/SearchPage.jsx, src/components/search/SearchResults.jsx, src/components/search/SearchVideo.jsx, src/components/search/tests/Search.test.jsx, src/components/search/tests/SearchPage.test.jsx, src/components/search/tests/utils.test.js, src/components/search/utils.js
• Implement "Beta" Badge with Tooltip next to "Video" heading
• Add Beta Announcement Banner to Search Page
=> feat: added Beta banner and Beta badge for videos

package-lock.json, package.json
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-9383
**Description:**
Bumped the version of catalog search to display **Beta** label with videos in the learning type facet.
=> [ENT-9383] chore: upgrade @edx/frontend-enterprise-catalog-search to 10.7.0

src/components/app/data/hooks/useCourseMetadata.js, src/components/app/data/utils.js, src/components/course/CourseSidebarPrice.jsx, src/components/course/course-header/CourseHeader.jsx, src/components/course/course-header/CourseImportantDates.jsx, src/components/course/course-header/tests/CourseImportantDates.test.jsx, src/components/course/data/courseLoader.ts, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/utils.jsx, src/components/course/routes/ExternalCourseEnrollment.jsx, src/components/course/tests/CourseSidebarPrice.test.jsx, src/components/microlearning/VideoBanner.jsx, src/components/microlearning/tests/VideoBanner.test.jsx
Ensures the course about page recognizes run-based assignments, displaying the `Assigned` badge and assignment-specific price strikeout messaging in the sidebar on the Course About page. This was supported by slightly refactoring to extend `useIsCourseAssigned` to utilize the util function `determineAllocatedAssignmentsForCourse`.
=> fix: ensure course about page acknowledges run-based assignments

src/components/app/data/constants.js
Changing the maximum number of highlights allowed
Associated PRs in https://github.com/openedx/frontend-app-admin-portal/pull/1306 and [enterprise-catalog](https://github.com/openedx/enterprise-catalog/pull/944)
[Jira ticket](https://2u-internal.atlassian.net/browse/ENT-9493)
=> fix: changing number of max highlights allowed

src/components/app/data/constants.js, src/components/app/data/hooks/useEnterpriseCourseEnrollments.js, src/components/app/data/utils.js, src/components/course/course-header/CourseImportantDates.jsx, src/components/course/data/constants.js, src/components/course/data/utils.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js
Based on a heuristic, default stale course start dates to today to display in various locations in the learner journey
=> feat: default stale start dates to today

src/components/course/course-header/CourseImportantDates.jsx, src/components/course/data/utils.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/BaseCourseCard.test.jsx
=> fix: variant based assignment bug fixes

src/components/course/data/courseLoader.test.jsx, src/components/course/data/courseLoader.ts
When a learner only has an assignment available, there is logic on the course about page that checks whether or not the learner _only_ has an allocated assignment (i.e., no other subsidies available). If the learner is assignment-only and the course is not assigned, we redirect back to the dashboard.
In the case of a run-based assignment, we were missing a check for assignment-only learners against both the `assignment.contentKey` vs. `assignment.parentContentKey` when comparing to the top-level course key in the course page route URL.
https://github.com/user-attachments/assets/7aa8e385-c273-4ba1-9a27-5341497bc1b2
=> fix: ensure run-based assignments are taken into account on course page redirect

src/components/course/routes/ExternalCourseEnrollment.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx, src/components/executive-education-2u/components/RegistrationSummaryCard.jsx
https://2u-internal.atlassian.net/browse/ENT-9423
=> fix: prevent `NotFoundPage` on successful redemption while still on `ExternalCourseEnrollment`

src/components/app/routes/createAppRouter.test.jsx, src/routes.tsx
The existing universal link route does not contain the enterprise slug, so for unauthenticated users, the frontend has no knowledge of which customer’s branded logistration for which to redirect. This is typically relied upon based on the `:enterpriseSlug` route parameter in the URL, which is missing for the existing universal link route. This change adds a new invite key route that includes the enterprise slug. This will enable us to produce slug-aware invite URLs from the admin portal, that receiving learners can use to become linked to the enterprise via the B2B-specific auth flow (which is customer-aware). 
ENT-9428
=> feat: create a route to handle invite keys that includes the customer slug

src/components/app/routes/loaders/rootLoader.ts, src/components/course/course-header/data/hooks/tests/useCourseRunCardHeading.test.jsx, src/components/course/course-header/data/hooks/useCourseRunCardHeading.js, src/components/course/data/utils.jsx
Adds parity with start-based assignments by updating business logic around which start is displayed on the available course run cards in the Course page route.
=> fix: ensure consistency around start dates on course run cards in Course page

src/components/course/ExpiredSubscriptionModal.jsx, src/components/course/course-header/CourseRunCardStatus.jsx, src/components/course/course-header/tests/CourseRunCardStatus.test.jsx, src/components/course/routes/CourseAbout.jsx, src/components/course/routes/tests/CourseAbout.test.jsx
- Conditionally override the "Disabled_enroll_Reason" on the Course about Page
- Create AlertModal to Display Custom Text when `has_custom_license_expiration_messaging` Enabled
=> feat: add alert modal and conditional text for expired subscriptions

src/components/app/data/hooks/useCourseMetadata.js, src/components/app/data/hooks/useCourseRedemptionEligibility.js, src/components/course/CourseSidebarPrice.jsx, src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx, src/components/course/routes/tests/ExternalCourseEnrollment.test.jsx, src/components/course/routes/tests/ExternalCourseEnrollmentConfirmation.test.jsx, src/components/course/tests/CourseSidebarPrice.test.jsx, src/components/dashboard/SubscriptionExpirationModal.jsx, src/components/executive-education-2u/components/CourseSummaryCard.jsx, src/components/executive-education-2u/components/RegistrationSummaryCard.jsx, src/components/microlearning/VideoDetailPage.jsx, src/components/microlearning/tests/VideoDetailPage.test.jsx, src/utils/common.js
This change would take into account price ranges for the course sidebar based on the run price. 👍🏽 
Example UI:
[Bug fix]
Fixed a bug I ran into where the subscription expiration modal became a blocking modal.
=> feat: update course about sidebar to take into account usd fixed price

src/components/app/data/services/subsidies/subscriptions.js, src/components/app/data/services/subsidies/subscriptions.test.js
Uses the net new field on the customer agreement labled `enable_auto_applied_subscriptions_with_universal_link` to allow a customer without SSO enabled to use auto applied licenses via universal link.
Dependent on : https://github.com/openedx/license-manager/pull/718
=> feat: allow auto applied with universal link via toggle

src/components/app/routes/data/utils.js, src/components/app/routes/loaders/rootLoader.ts, src/components/app/routes/loaders/tests/rootLoader.test.jsx, src/components/dashboard/data/dashboardLoader.test.jsx, src/components/dashboard/data/dashboardLoader.ts
[ENT-9583](https://2u-internal.atlassian.net/browse/ENT-9583)
* Moves call to `redirectToSearchPageForNewUser` from `rootLoader` to `dashboardLoader`.
* Requires bringing in `queryClient.ensureQueryData(queryRedeemablePolicies(...))` alongside the query to fetch enrollments to determine whether the dashboard -> search redirect is applicable based on both the enrollments but also assignments from `credits_available`.
* Refactors `redirectToSearchPageForNewUser` to accept `enterpriseCourseEnrollments`, and only trigger redirect from the dashboard route to search route for learners with no enrollments to display on their dashboard, in addition to the existing check on the displayed assignments.
* Returns early if navigating from a different route (e.g., search) to the dashboard route, as …
=> feat: take into account enrollments in dashboard -> search route redirect for new users

src/components/expired-subscription-modal/index.jsx, src/components/expired-subscription-modal/tests/ExpiredSubscriptionModal.test.jsx
- Updated the custom expiration model design
- Make that modal truly blocking
JIRA -> [ENT-9616](https://2u-internal.atlassian.net/browse/ENT-9616), [ENT-9618](https://2u-internal.atlassian.net/browse/ENT-9618)
=> feat: updated the custom expiration model design and truly blocking

src/components/expired-subscription-modal/index.jsx
Issue:
- Modal title text was showing some unnecessary spaces
Fix:
-  Override base class to fix the issue
=> fix: styles on expiry modal

src/components/course/data/hooks.jsx, src/components/course/data/tests/hooks.test.jsx
Update check on returned list price length to correctly go into the fallback check for price.
=> fix: check length on empty array for list price

src/components/app/data/services/subsidies/subscriptions.js, src/components/app/data/services/subsidies/subscriptions.test.js, src/components/expired-subscription-modal/index.jsx, src/components/expired-subscription-modal/tests/ExpiredSubscriptionModal.test.jsx
Prevents original/standard subscriptions expiration modal from renders simultaneously with the custom subs messaging modal.
=> Prevent SubscriptionExpirationModal from displaying when custom messages enabled.

src/components/app/data/services/enterpriseCustomerUser.js, src/components/app/data/services/enterpriseCustomerUser.test.js, src/components/expired-subscription-modal/index.jsx, src/components/expired-subscription-modal/tests/ExpiredSubscriptionModal.test.jsx
JIRA Ticket -> https://2u-internal.atlassian.net/browse/ENT-9665
=> feat: unlink the enterprise learner in non blocking manner

src/components/app/data/hooks/useCourseMetadata.js, src/components/app/data/hooks/useCourseMetadata.test.jsx, src/components/app/data/hooks/useCourseRedemptionEligibility.js, src/components/app/data/hooks/useCourseRedemptionEligibility.test.jsx, src/components/app/data/services/course.js, src/components/app/data/services/course.test.js, src/components/app/data/utils.js, src/components/course/course-header/CourseRunCards.jsx, src/components/course/course-header/tests/CourseRunCards.test.jsx, src/components/course/data/hooks.jsx, src/constants/course.js, src/index.jsx
=> feat: display restricted runs on course about page

src/components/app/data/hooks/useBFF.js, src/components/app/data/hooks/useBFF.test.jsx, src/components/app/data/queries/queries.ts, src/components/app/data/queries/queryKeyFactory.js, src/components/app/data/services/bffs.js, src/components/app/data/services/bffs.test.js, src/components/app/data/services/index.js, src/components/app/data/utils.test.js, src/components/app/routes/data/utils.js, src/components/dashboard/DashboardPage.jsx
Adds a query key for the BFF layer.
Adds a custom hook for utilizing the BFF call for the learner dashboard. _Note_: We do not make the BFF call yet.
As part of adding the custom hook which initially utilizes the enterprise slug to make the BFF call, we create a method for copying over the BFF data to a query cache with the updated query key that is populated with the enterprise customer uuid from the API response to avoid duplicate calls in the future. 
Adds related tests, pending 1 test.
=> feat: add query key and hooks for BFF layer

package-lock.json, package.json
**Ticket:**
https://2u-internal.atlassian.net/browse/ENT-9791
**Description:**
Bumped the version of catalog search to [10.8.0](https://github.com/openedx/frontend-enterprise/releases/tag/%40edx%2Ffrontend-enterprise-catalog-search%4010.8.0) in order to log segment event to track the selected value for "Learning Type" dropdown
=> [ENT-9791] chore: upgrade @edx/frontend-enterprise-catalog-search to 10.8.0

src/components/app/Layout.jsx, src/components/app/Layout.test.jsx
Learners signed in with their personel accounts were not able to see the custom 404 which tells to change account (when they click on the assigned license email link)
=> feat: fixed bug that prevents learner from seeing custom 404

src/components/app/routes/data/utils.js, src/components/dashboard/data/dashboardLoader.ts
Update usages of `resolveBFFQuery` to correctly pass the enterpriseCustomer uuid as an options field.
=> fix: correctly pass arguments into resolveBFFQuery

src/components/app/routes/data/utils.js
Upon testing locally, after the nProgressLoader bar completes there was a brief moment a blank was shown. This is not normal. Updates conditionally blocked queries based on whether the BFF is enabled for the customer.
=> fix: update conditionally blocked BFF queries

src/components/course/course-header/deprecated/CourseRunCard.jsx, src/components/course/course-header/tests/DeprecatedCourseRunCard.test.jsx, src/components/course/data/utils.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/UpcomingCourseCard.jsx
Resolves "Invalid Date" messages on course about page in Learner Portal in Firefox (appears fine in Chrome). The error seems to be due to different browsers' parsing/handling of datetime strings.
Locally, there was a JS error triggers by `react-intl`'s `FormattedDate` component:
```
Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting date.
Locale: en
date value is not finite in DateTimeFormat.format()
```
The solution was to ensure the raw date string was passed to `FormattedDate` vs. passing the already-formatted date via `dayjs(...).format(DATE_FORMAT)`. 
This PR also switches to use `getNormalizedStartDate` within the deprecated `CourseRunCard` component to ensure today's date is used for display, where relevant (i.e., self-paced courses with time-to-complete).
=> fix: invalid date formatting on course route

src/components/app/data/services/subsidies/index.js, src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/SavedForLaterCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/UnenrollModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/unenroll/UnenrollModal.test.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx, src/components/executive-education-2u/UserEnrollmentForm.jsx, src/components/executive-education-2u/UserEnrollmentForm.test.jsx, src/components/stateful-enroll/data/hooks/useStatefulEnroll.js, src/components/stateful-enroll/data/hooks/useStatefulEnroll.test.jsx
Where existing query invalidations and optimistic updates exist for cached query data related to metadata also retrieved from the BFF layer, we add identical logic to invalidate/optimistic update the BFF query cache.
Fixes bug related to passed in args into optimizely within `useStatefulEnroll`.
=> feat: optimistic query update with the BFF inclusion

src/components/app/data/constants.js, src/components/app/data/hooks/useEnterpriseCourseEnrollments.js, src/components/app/data/hooks/useEnterpriseCourseEnrollments.test.jsx, src/components/app/data/hooks/useSubscriptions.js, src/components/app/data/hooks/useSubscriptions.test.jsx, src/components/app/data/services/subsidies/index.test.js, src/components/app/data/utils.js, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx
https://2u-internal.atlassian.net/browse/ENT-9857
In both `useSubscriptions` and `useEnterpriseCourseEnrollments`, this PR ensures any optional `queryOptions.select` functions passed in follow the established convention of being called with an object containing the following:
```js
return select({
original: data, // the original query data, untransformed
transformed: transformedData, // the transformed query data, as determined by the hook's internal `select` logic.
});
```
This pattern ensures any custom `select` functions passed to the helper query hooks (e.g., `useSubscriptions`) are given a choice of using the original query data or transformed query data from the parent hook.
=> fix: ensure useSubscriptions and useEnterpriseCourseEnrollments uses queryOptions.select from args

src/components/app/data/hooks/useBFF.js, src/components/app/data/hooks/useBFF.test.jsx, src/components/app/data/hooks/useIsBFFEnabled.js, src/components/app/data/hooks/useIsBFFEnabled.test.js, src/components/app/data/hooks/useSubscriptions.test.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/CourseEnrollmentsEmptyState.jsx, src/components/dashboard/main-content/course-enrollments/tests/CourseEnrollments.test.jsx, src/components/search/tests/SearchSections.test.jsx
A previous PR incorrectly changed the expected data structure return value of the `useEnterpriseFeatures` hook. The hook returns a `useQuery` result, not a direct pass-thru of the `enterpriseFeatures` object as is currently assumed in the code per the prior PR.
This PR changes the usages of `useEnterpriseFeatures` back to the expected `const { data: enterpriseFeatures } = useEnterpriseFeatures()` throughout the application.
=> fix: correct usages of useEnterpriseFeatures

src/components/app/data/queries/extractEnterpriseFeatures.test.js, src/components/app/data/queries/extractEnterpriseFeatures.ts, src/components/app/data/queries/index.js, src/components/app/routes/loaders/rootLoader.ts, src/components/dashboard/data/dashboardLoader.test.jsx, src/components/dashboard/data/dashboardLoader.ts, src/types.d.ts
Currently, the loaders are incorrectly assuming `enterpriseFeatures` is a property on the `enterpriseCustomer`; however, this is not actually correct.
The `enterpriseFeatures` actually comes from the `enterpriseLearnerData` data, not as a nested property under the `enterpriseCustomer`.
As such, enabling the BFF via the Waffle-based feature flag is never working properly in the loaders since `undefined` is currently passed into `isBFFEnabled`.
This PR:
1. Implements an `extractEnterpriseFeatures` method similar to `extractEnterpriseCustomer`, used within `dashboardLoader`.
2. Ensures the correct `enterpriseFeatures` is passed to `ensureEnterpriseAppData`.
=> fix: use correct enterpriseFeatures in loaders

src/components/app/data/hooks/useBFF.test.jsx, src/components/app/data/utils.js, src/types.d.ts
Current code assumes `enterpriseFeatures.enterpriseLearnerBFFEnabled` vs. the actual `enterpriseFeatures.enterpriseLearnerBffEnabled`...
=> fix: typo in BFF feature flag key via `enterpriseFeatures`

docs/decisions/0013-backend-for-frontend-api.md
ADR for the frontend integration of the backend for frontend API call and and overview of resulting changes.
=> docs: BFF ADR

src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx
https://github.com/user-attachments/assets/15286030-823d-47b9-b829-717d1a5bb327
Updates upcoming course titles on the dashboard to be static `Card.Header` files. Still retains original component styling and behavior for all other course `type` based on existing behavior.
Slight refactor to match current code style of the component.
=> fix: set static titles for upcoming courseware

src/components/course/data/hooks.jsx, src/components/course/data/tests/utils.test.jsx, src/components/course/data/utils.jsx
[ENT-9729](https://2u-internal.atlassian.net/browse/ENT-9729)
The displayed message pertains to the "Not in catalog" case, but the button CTA corresponds to revoked subscription license.
The displayed message corresponds to the revoked subscription license.
=> fix: ensure matching reason types and user messages on course page

src/components/app/data/constants.js, src/components/app/data/hooks/useCatalogsForSubsidyRequests.test.jsx, src/components/app/data/hooks/useSubscriptions.js, src/components/app/data/hooks/useSubscriptions.test.jsx, src/components/app/data/services/subsidies/subscriptions.js, src/components/app/data/services/subsidies/subscriptions.test.js, src/components/app/data/utils.js, src/components/app/routes/data/utils.js, src/components/app/routes/loaders/tests/rootLoader.test.jsx
No longer uses `transformSubscriptionsData` on the BFF data, since the BFF does the same transforms itself now. `transformSubscriptionsData` is still needed, though, for the non-BFF supported page routes which still calls `learner-licenses` API directly.
Corresponding backend BFF PR (should be merged/released first): https://github.com/openedx/enterprise-access/pull/621
=> refactor: remove BFF transform for subscriptions data

src/components/app/data/hooks/index.js, src/components/app/data/hooks/useHasValidLicenseOrSubscriptionRequestsEnabled.js, src/components/app/data/hooks/useHasValidLicenseOrSubscriptionRequestsEnabled.test.jsx, src/components/microlearning/VideoDetailPage.jsx, src/components/microlearning/tests/VideoDetailPage.test.jsx, src/components/search/Search.jsx, src/components/search/SearchPage.jsx, src/components/search/tests/Search.test.jsx, src/components/search/tests/SearchPage.test.jsx, src/components/search/tests/SearchSections.test.jsx, src/components/search/tests/utils.test.js, src/components/search/utils.js
When the learner doesn’t have an activated/current subscription license, the “New! Videos Now Available with Your Subscription” messaging will only appear if the customer is configured for BnR with subscriptions.
=> fix: videos will show only to bnr active subscriptions

src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx, src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/tests/enrollment-testutils.js
During the transition to run based assignments, a refactor was missed related to filtering out duplicative learner credit allocations on a potentially upgradable audit enrollment on the learner dashboard page. This did **not** affect the user's ability to upgrade their audit enrollment. It presented a confusing UI experience on which course card to proceed on (Upgrade or learner credit enrollment.)
This PR removes duplicative course cards by filtering on the course run vs the content key which may either be a top level course or a course run id.
Prior to fix:
After fix:
=> fix: remove duplicative course run card on allocation

src/components/microlearning/data/videosLoader.test.jsx, src/components/microlearning/data/videosLoader.ts, src/components/program-progress/data/programProgressLoader.ts, src/components/program-progress/data/tests/programProgressLoader.test.jsx
This PR fixes forward an issue identified after releasing https://github.com/openedx/frontend-app-learner-portal-enterprise/pull/1256, which removes a parent `Suspense` fallback that previously caught asynchronous query loading states.
On the video detail and program progress pages routes, there was an increase in errors containing the message "a component suspended without a fallback UI specified", which suggests there are queries used during render that have not been pre-fetched in a route loader.
Replicating the issues for these 2 page routes locally, the relevant queries are now pre-fetched in the appropriate loaders, mitigating these observed errors in development.
=> fix: ensure relevant queries are pre-seeded for video and program progress routes

src/components/app/data/utils.js
Adds a check to the isMarketableExternal flag to the `standardAvailableCourseRunsFilter`
=> fix: adds check for isMarketableExternal to course run filter

renovate.json
This is further refinement on the role of renovate in generating PRs for package updates. This change allows for the user to generate PRs for major upgrades by navigating to the renovate [dashboard ](https://github.com/openedx/frontend-app-learner-portal-enterprise/issues/302)found in the issues tab.
=> chore: allow users to opt into major upgrades

src/components/microlearning/VideoBanner.jsx, src/components/search/Search.jsx, src/components/search/SearchCourse.jsx, src/components/search/SearchPathway.jsx, src/components/search/SearchProgram.jsx, src/components/search/SearchResults.jsx, src/components/search/SearchVideo.jsx, src/components/search/tests/Search.test.jsx, src/components/search/tests/SearchResults.test.jsx, src/components/skills-quiz/__mocks__/react-instantsearch-dom.jsx, src/constants/index.js, src/constants/search.js
**Ticket:** [ENT-9893](https://2u-internal.atlassian.net/browse/ENT-9893)
**Description:** Made some changes to hide videos' banner initially and display it only if videos' section is populated. For the Id's issue, I noticed that we are using hard-coded strings as Ids for Algolia's Index component. I have moved them to a separate file and these Ids are now being used in `SearchResults` component instead of using a simple Id based on `showBetaBadge`'s boolean condition.
=> fix: hide video banner if no videos are available

src/components/app/data/services/bffs.ts
[ENT-10028](https://2u-internal.atlassian.net/browse/ENT-10028)
The constant `learnerDashboardBFFResponse` ([source](https://github.com/openedx/frontend-app-learner-portal-enterprise/blob/2c41e5ad4a493de927c569e6fb69ea143328ddd0/src/components/app/data/services/bffs.ts#L22-L27)) intends to be the base empty state response for the Dashboard BFF, containing the empty fields where appropriate for downstream consumers of these data to access instead of erroring:
```js
export const learnerDashboardBFFResponse = {
...baseLearnerBFFResponse,
enterpriseCourseEnrollments: [],
allEnrollmentsByStatus: {
[COURSE_STATUSES.inProgress]: [],
[COURSE_STATUSES.upcoming]: [],
[COURSE_STATUSES.completed]: [],
[COURSE_STATUSES.savedForLater]: [],
},
};
```
However, in the `allEnrollmentsByStatus` object, we …
=> fix: use camelCase course statuses as keys in fallback BFF response

src/components/app/routes/LicenseActivationRoute.jsx, src/components/dashboard/SubscriptionExpirationModal.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/CompletedCourseCard.jsx, src/components/site-header/AvatarDropdown.jsx
now that the legacy account and profile applications are gone, the redirect from these legacy links no longer works, so I am replacing them with direct links to the MFEs.
FIXES: APER-3884
=> chore: replacing legacy links

.github/workflows/ci.yml, package.json
* Ensures TypeScript types are validated in CI.
* Parallelizes GitHub Action workflow steps for more efficient CI (e.g., running tests in parallel with `npm run build`).
=> build: add tsc typecheck in CI

src/components/app/data/queries/extractEnterpriseCustomer.test.js, src/components/app/data/queries/extractEnterpriseCustomer.ts, src/components/app/data/queries/utils.js, src/components/app/routes/RouteErrorBoundary.jsx
We return null and log an error as opposed to throwing the error. If the user reaches this state, they are most likely unauthenticated or do not have access to the learner portal and refreshing the page as part of this error message will not yield different results.
=> fix: return null on extractEnterpriseCustomer

src/components/course/CreatedBy.jsx
See https://enterprise.edx.org/bestrun-successfactors-test-co/course/TUMx+QPLS1x for example with quite large partner logo. Not sure why this particular's partner's logo is not the standard partner logo image size of `200x100`, but our UI should handle any image size regardless.
https://2u-internal.atlassian.net/browse/ENT-10119
=> fix: use fluid image in course page partner logos

src/components/app/data/services/data/__factories__/enterpriseCustomerUser.factory.ts, src/components/app/data/utils.js, src/components/app/routes/data/utils.test.js
Adjust the display logic for the Integration Warning modal in the Learner Portal. Previously, the modal displayed when search was enabled and an identity provider was configured. This resulted in confusion for customers who did not have an LMS integration but saw the modal due to having SSO enabled.
Changes:
- Update the condition to display the Integration Warning modal only if the enterprise customer has an active LMS integration.
- Use the active_integrations field from the BFF or direct LMS API call as the new condition.
- Ensure customers without LMS integrations do not see the modal, regardless of SSO setup.
Ticket Reference: [ENT-10068 - IntegrationWarning showing for a customer with search enabled and no identity provider.](https://2u-internal.atlassian.net/browse/ENT-10068)
=> fix: update integration warning logic to check active LMS integrations

src/components/app/data/hooks/useCanUpgradeWithLearnerCredit.js, src/components/app/data/hooks/useCanUpgradeWithLearnerCredit.test.jsx, src/components/app/data/hooks/useCourseRedemptionEligibility.js, src/components/app/data/utils.js, src/components/dashboard/main-content/course-enrollments/data/hooks.js, src/components/dashboard/main-content/course-enrollments/data/tests/hooks.test.jsx
Fixes an issue where a course run was displayed as enroll-able despite no redeemable subsidy access policy despite policy redemption being enabled. 
For customers who have already redeemed a single course run and navigate back to the course about page of their redeemed course, if there exist more then one available run, the user should no longer be able to enroll if they are not allocated an assignment. 
Updates data structure for upgrade learner credit path to be in-line with redemptions and respect the newly added validation for `redeemableSubsidyAccessPolicy` 
To test locally: 
On a learner credit enabled customer, allocate and redeem a course with multiple course runs available to enroll in.
Navigate back to the course about page and the remaining runs should show as enroll-able …
=> fix: Add logic check on learner credit subsidy

src/components/app/data/queries/utils.ts, src/components/app/routes/data/utils.js
During the rollout of the React 18 upgrade for this MFE in production, a handful of new error instances from an Online Campus Free/Essentials customer surfaced related to a 404 error on the B&R configuration API request, preventing the app from displaying (i.e., the error caught by parent error boundary). A 404 is raised by this API if learners are accessing the Learner Portal where that customer's Admin Portal was not yet visited (which triggers a create of the B&R configuration record).
After investigation, the API request is properly caught in the route loader (`rootLoader`) via `safeEnsureQueryData`, but it doesn't set a `fallbackData` (i.e., `fallbackData=undefined`). As such, when the UI components render and consume that query via `useBrowseAndRequestConfiguration`, having no data …
=> fix: ensure B&R config query falls back to null vs undefined

src/components/app/data/hooks/useEnterpriseLearner.ts, src/components/app/data/queries/utils.ts, src/components/app/data/services/bffs.ts, src/components/app/data/services/enterpriseCustomerUser.test.js, src/components/app/data/services/enterpriseCustomerUser.ts, src/components/dashboard/sidebar/LearnerCreditSummaryCard.jsx, src/components/dashboard/sidebar/tests/DashboardSidebar.test.jsx, src/components/dashboard/sidebar/tests/LearnerCreditSummaryCard.test.jsx, src/types/enterprise-access.openapi.d.ts, src/types/openapi-schemas/enterprise-access.yaml, src/types/types.d.ts
Show an appropriate message in the subsidy box if B&R is enabled on a budget. 
JIRA -> [ENT-10291](https://2u-internal.atlassian.net/browse/ENT-10291)
=> feat: Modify Learner Credit Subsidy Box on Dashboard for B&R Budgets

src/components/app/data/hooks/useEnterpriseCourseEnrollments.js, src/components/app/data/hooks/useEnterpriseCourseEnrollments.test.jsx, src/components/app/data/queries/utils.ts, src/components/app/data/services/subsidies/index.test.js, src/components/app/data/services/subsidies/index.ts, src/components/app/data/utils.js, src/components/dashboard/main-content/course-enrollments/CourseEnrollments.jsx, src/components/dashboard/main-content/course-enrollments/CourseSection.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/ApprovedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/BaseCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/LCRequestedCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/index.js, src/components/dashboard/main-content/course-enrollments/course-cards/tests/ApprovedCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/LCRequestedCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/RequestedCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/data/tests/utils.test.js, src/components/dashboard/main-content/course-enrollments/tests/CourseSection.test.jsx, src/constants/course.js
Ticket: [ENT-10290](https://2u-internal.atlassian.net/browse/ENT-10290)
Description: I've displayed the requests returned by `credit_available` endpoint along with assignments. I've transformed them to match the assignments structure so that they can be integrated in the existing flow of rendering assignments. I've also added 2 new course card components which utilize the base card component for `approved` and `requested` state.
=> feat: add learner credit requests in learner dashboard

src/components/app/AppErrorBoundary.tsx, src/components/app/data/services/enterpriseCustomerUser.ts
https://2u-internal.atlassian.net/browse/ENT-10495
These errors has impacted roughly ~10 sessions of the past week.
This PR addresses the above stack trace to ensure we handle when `authenticatedUser` is missing within `fetchEnterpriseLearnerData` and `AppErrorBoundary`. Note, however, it's still unclear _why_ we're getting into this `fetchEnterpriseLearnerData` code path given the upstream code seems to properly gate this code path when `authenticatedUser` is missing but this change should at least mitigate the immediate error we're seeing.
=> fix: ensure`fetchEnterpriseLearnerData` and `AppErrorBoundary` handles null authenticated user

src/components/app/data/services/subsidies/subscriptions.js, src/components/app/data/services/subsidies/subscriptions.test.js
Adds a `page_size` query parameter to allow more license request to pass through to the user to supercede a upstream error related to the paginated response from learner licenses.
=> fix: add page size to supercede license manager

src/components/course/data/hooks/hooks.jsx, src/components/course/data/hooks/hooks.test.jsx
Added a new hook to check if a user has a Learner Credit Request (LCR) for a course.
To preserve the original behavior, I did not modify useUserHasSubsidyRequestForCourse, since it’s used in multiple components and changing it could unintentionally disrupt existing functionality.
=> feat: add useUserHasLearnerCreditRequestForCourse hook

src/components/dashboard/main-content/course-enrollments/course-cards/InProgressCourseCard.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/UpgradeCourseButton.jsx, src/components/dashboard/main-content/course-enrollments/course-cards/tests/InProgressCourseCard.test.jsx, src/components/dashboard/main-content/course-enrollments/data/hooks.js
Ticket: https://2u-internal.atlassian.net/browse/ENT-10510
Since the React 18 upgrade, when an enterprise learner had an audit enrollment and a code available but no active subsidy access policies (learner credit), the audit->verified skeleton loader was persistent and never going away for the learner. While replicating the issue, it was observed the `can-redeem` API was constantly being re-fetched.
This bug was not widespread given we only have ~8 legacy codes customers remaining, and requires to be enrolled in audit (atypical for enterprise).
The fix introduced in this PR removes the usage of `useCourseUpgradeData` from `UpgradeCourseButton` in favor of prop drilling the requisite data into `UpgradeCourseButton` from its parent component `UpgradeableInProgressCourseCard`.
Stuck on …
=> fix: remove nested `useCourseUpgradeData` hooks for audit upgrades

src/components/app/data/hooks/useAlgoliaSearch.test.tsx, src/components/app/data/hooks/useAlgoliaSearch.ts, src/components/app/data/hooks/useDefaultSearchFilters.test.jsx, src/components/app/data/hooks/useDefaultSearchFilters.ts, src/types/types.d.ts
Removing feature flag related to the secured_algolia_api_key which validated if the enterprise customer had the catalogQuerySearchFiltersEnabled enabled. The feature is currently enabled for all customers deprecating the usage of the waffle flag itself.
=> chore: Remove feature flag for secured algolia api key

src/components/course/course-header/CourseHeader.jsx, src/components/course/course-header/tests/CourseHeader.test.jsx
=> fix: do not show 'Request Enrollment' CTA on an archived course

src/components/app/data/hooks/useEnterpriseOffers.test.jsx, src/components/app/data/hooks/useEnterpriseOffers.ts, src/components/app/data/queries/utils.test.ts, src/components/app/data/queries/utils.ts
This pull request updates how enterprise offers are handled in the codebase to reflect the deprecation of offers as of 09/15/2025. Instead of fetching real offer data, the logic now returns hardcoded values indicating that no enterprise offers are available and related features are disabled.
Deprecation of enterprise offers:
* Updated `useEnterpriseOffers` hook to return hardcoded empty offers and set all related flags (such as `canEnrollWithEnterpriseOffers` and `hasCurrentEnterpriseOffers`) to indicate that offers are deprecated and unavailable. (`src/components/app/data/hooks/useEnterpriseOffers.ts`)
* Updated `safeEnsureQueryDataEnterpriseOffers` utility to use a hardcoded query function that returns empty offers and appropriate flags, matching the deprecation logic in the hook. …
=> fix: deprecate use of offers
